### ISSUE TITLE
Linux server - mission won't start after #mission

### ISSUE THREAD

**Issue by ichigo29** [Vdauphin/HeartsAndMinds#1001]
Hi, 
We are running Hearts & Minds on our windows server and to save money we are trying to recreate this server on Linux.
For now, everything is OK, we get inside the mission, and spawn on the base.
Problem, we are not able to do #mission.
After doing it, we get back into the role selctecion menu everytime we try to get into the mission.
Here is my startup command : 
`./arma3server -config=./TADST_config.cfg -cfg=./TADST_basic.cfg -mod="./mods/symblinks/@3cb_baf_equipment;./mods/symblinks/@3cb_baf_units;./mods/symblinks/@3cb_baf_units_ace_compatibility;./mods/symblinks/@3cb_baf_units_rhs_compatibility;./mods/symblinks/@3cb_baf_vehicles;./mods/symblinks/@3cb_baf_vehicles_rhs_reskins;./mods/symblinks/@3cb_baf_vehicles_servicing_extension;./mods/symblinks/@3cb_baf_weapons;./mods/symblinks/@ace;./mods/symblinks/@ace_3_extension_animations_and_actions;./mods/symblinks/@ace_compat-rhs_armed_forces_of_the_russian_federation;./mods/symblinks/@ace_compat-rhs_gref;./mods/symblinks/@ace_compat-rhs_saf;./mods/symblinks/@ace_compat-rhs_united_states_armed_forces;./mods/symblinks/@acex;./mods/symblinks/@achilles;./mods/symblinks/@armafxp;./mods/symblinks/@backpackonchest;./mods/symblinks/@cba_a3;./mods/symblinks/@ch_view_distance;./mods/symblinks/@community_factions_project_cfp;./mods/symblinks/@cup_terrains-core;./mods/symblinks/@cup_terrains-maps;./mods/symblinks/@cup_terrains-maps_2.0;./mods/symblinks/@cup_units;./mods/symblinks/@cup_vehicles;./mods/symblinks/@cup_weapons;./mods/symblinks/@discontinued_burnes_armories-fv4034_challenger_2_tes;./mods/symblinks/@dynasound_2;./mods/symblinks/@enhancedmovement;./mods/symblinks/@fir_aws_airweaponsystem;./mods/symblinks/@gruppe_adler_trenches;./mods/symblinks/@ilbe_assault_pack-rewrite;./mods/symblinks/@interiorsfor_cup;./mods/symblinks/@lambs_danger.fsm;./mods/symblinks/@lambs_rpg;./mods/symblinks/@lambs_turrets;./mods/symblinks/@project_opfor;./mods/symblinks/@rhsafrf;./mods/symblinks/@rhsgref;./mods/symblinks/@rhssaf;./mods/symblinks/@rhsusaf;./mods/symblinks/@rksl_studios_attachments_v3.02;./mods/symblinks/@rksl_studios_aw159_wildcat;./mods/symblinks/@task_force_arrowhead_radio_beta;./mods/symblinks/@vcom_ai_v3.4.0;./mods/symblinks/@virolahti-valtatie_7;./mods/symblinks/@zeus_enhanced;./mods/symblinks/@zeus_enhanced-ace3_compatibility"`

and here are [my logs](https://www.dropbox.com/s/4tf0hrdgua2rpks/log.txt?dl=0)

**Comment by Vdauphin** [comment]
Hello,

I never used `#mission`.
What I see here: https://community.bistudio.com/wiki/Multiplayer_Server_Commands is you are missing the mission name after the `#mission`.

For server management, you will find better help in A3 forum or Discord.

Cheers

**Comment by ichigo29** [comment]
OK,
Thank you for the fast reply.
while I have you, there's another question I have. 
When we are saving the progress in the mission, where are the saves going ??
I ask you that because when we take the mission pbo to another server, it reset the mission to its begenning and the saves are not carried out.

**Comment by Vdauphin** [comment]
See here: https://github.com/Vdauphin/HeartsAndMinds/issues/449#issuecomment-352271515
And here: https://community.bistudio.com/wiki/Profile
