### ISSUE TITLE
Units still spawn inside rock on hills with large and wide spread rocks

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#1022]
**Arma 3 Version:** `2.00` (stable)
**CBA Version:** `3.15.2` (stable)
**ACE3 Version:** `3.13.5` (stable / dev + commit hash)
**Hearts and minds Version:** `master-daily` (5e15500)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- On Altis, I notice in some hills with large and wide spread rocks, AI units will spawn inside rock, making players unable to find them and free the city.

**Steps to reproduce:**
- Trigger city spawn, the city should have large and wide spread rocks.
- Sometimes AI will spawn inside rock.

**Screenshots:**
![Arma3_x64 2021-01-09 16-06-42](https://user-images.githubusercontent.com/26923626/104086909-aca50500-5296-11eb-977e-cf4d4b739478.png)

![Arma3_x64 2021-01-09 16-06-48](https://user-images.githubusercontent.com/26923626/104086925-c7777980-5296-11eb-89ae-d9e03028d3ef.jpg)

![Arma3_x64 2021-01-09 16-07-01](https://user-images.githubusercontent.com/26923626/104086920-baf32100-5296-11eb-9940-69afdc1834c9.png)

**Comment by Vdauphin** [comment]
I need .rpttttttttttttt
Look like those are patrol which doesn't persist after server restart.

**Comment by GoldJohnKing** [comment]
I'm pretty sure this is the one.

The screenshot is taken at 16:06, and I activated a city at 16:03. You can search 16:03 and 16:04 get the log during city activation.

[Arma3_x64_2021-01-09_15-34-31.zip](https://github.com/Vdauphin/HeartsAndMinds/files/5792173/Arma3_x64_2021-01-09_15-34-31.zip)

**Comment by Vdauphin** [comment]
to quickly test the fix: `player setPos ([getpos(btc_city_all select 99), 0, 150, 10, false] call btc_fnc_findsafepos)` looks fine

**Comment by GoldJohnKing** [comment]
> to quickly test the fix: `player setPos ([getpos(btc_city_all select 99), 0, 150, 10, false] call btc_fnc_findsafepos)` looks fine

Yep, seems fine.
