### ISSUE TITLE
UNSUNG Faction make crash the mission

### ISSUE THREAD

**Issue by Pochtron** [Vdauphin/HeartsAndMinds#1041]
(Use English only.)

## Before reporting

If you have found an issue with Hearts and Minds please make sure that Hearts and Minds really is the cause of the problem. To do this try to reproduce the issue with using only `@CBA_A3`, `@ace` and `@RHSUSAF` on a stable and unchanged Hearts and minds available [here](https://github.com/Vdauphin/HeartsAndMinds/releases) on a dedicated server.
I have all the last version of Ace, H&M, RHS etc...

**Description:**
- When I choose the faction 300 (NVA-Unsung) as ennemy and 26 as Civilian - Unsung for civilian and civ vehicle in parameter file, the server start well and pop some ennemies and civilian but after 2 or sometime 5 min. the mission crash automatically. It didn't do that with basic faction (6 for ennemy and 1 for civilian for instance) with same Mod pack.
Here is the rpt file corresponding to the crash of the server.

Thanks very much =) 

[arma3server_x64_2021-02-10_00-40-57.txt](https://github.com/Vdauphin/HeartsAndMinds/files/5969215/arma3server_x64_2021-02-10_00-40-57.txt)

**Comment by Vdauphin** [comment]
Hello,

I tested on a dedicated server and there is no crash
![20210212112901_1](https://user-images.githubusercontent.com/14364400/107757488-e9e13480-6d25-11eb-85f0-bc51aec8f8a9.jpg)

Please fill correctly the issue template
Remove each mod one by one until the crash disappear

Cheers

**Comment by Pochtron** [comment]
Oh I tried on rhapkl map I forgot to mention but Perfect I'm going to do
that! Thanks very much
