### ISSUE TITLE
Custom Init on "Require Object"

### ISSUE THREAD

**Issue by Sora012** [Vdauphin/HeartsAndMinds#1044]
How can I setup a custom init on an object spawned through "Require Object" action?

I've tried add_actions.sqf and veh_init.sqf but neither are working. I just would like to copy the code from //Arsenal section from add_actions.sqf to all supply crates "ReammoBox_F". to enable the appropriate addaction for Arsenal

**Comment by Vdauphin** [comment]
Hello,

I would add this to https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/init_player.sqf#L20
```sqf
["ReammoBox_F", "InitPost", {
    [(_this select 0), !(btc_p_arsenal_Restrict isEqualTo 1), false] call ace_arsenal_fnc_initBox;
    (_this select 0) addAction [localize "STR_BTC_HAM_ACTION_ARSENAL_OPEN_ACE", "[_this select 0, player] call ace_arsenal_fnc_openBox;"];
}, true, [], true] call CBA_fnc_addClassEventHandler;
```

Cheers

**Comment by Sora012** [comment]
Thanks so much!! This is exactly what I needed, and has helped me greatly.
