### ISSUE TITLE
No suicide bomber in Chernarus 2020

### ISSUE THREAD

**Issue by RoqueTHEGAMER** [Vdauphin/HeartsAndMinds#1048]
Testing in single player and multiplayer solo I had no suicide bomber in my mission with the lowest reputation possible, I used the latest build with no modifications to the mission or files

the mods are as follow:

RHSAFRF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843425103
-- | -- | --
CBA_A3 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
RHSUSAF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843577117
ace | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=463939057
RHSGREF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843593391
RHSSAF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843632231
NIArms All in One | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1208517358
BackpackOnChest | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=820924072
ACEX | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=708250744
ACE Compat - RHS United States Armed Forces | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=773125288
ACE Compat - RHS Armed Forces of the Russian Federation | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=773131200
ACE Compat - RHS: GREF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=884966711
task_force_radio | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=620019431
ACE 3 Extension (Animations and Actions) | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=766491311
Project OPFOR | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=735566597
CUP Terrains - Core | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=583496184
Enhanced Movement | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=333310405
ACE Compat - RHS: SAF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2174495332
CUP Terrains - Maps 2.0 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1981964169
NIArms All in One - RHS Compatibility. | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1400574293
YuEmod | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1195262135

**Comment by Vdauphin** [comment]
![20210221182417_1](https://user-images.githubusercontent.com/14364400/108633106-c3806f00-7472-11eb-9635-94c2b5d86eae.jpg)

**Comment by RoqueTHEGAMER** [comment]
I had a weird inconsistency, If I load my custom modified mission and then the unmodified mission the problem carries over, but if I restart my game and load the unmodified mission it works.

**Comment by RoqueTHEGAMER** [comment]
I also noticed that in the map, the unmodified shows [false.false] and the modified shows [false,empty]

**Comment by Vdauphin** [comment]
> I had no suicide bomber in my mission with the lowest reputation possible, I I used the latest build with no modifications to the mission or files

> but if I restart my game and load the unmodified mission it works.

**Comment by RoqueTHEGAMER** [comment]
> If I load my custom modified mission and then the unmodified mission the problem carries over

**Comment by Vdauphin** [comment]
then the issue is due to your custom modified version

**Comment by RoqueTHEGAMER** [comment]
And I can't point were is the problem, the files I modified were small things like change unit weapons and configuration settings, and also the parameters are set in the mission file so the server don't need to do it manually.

its a problem soo problematic that carries over to another mission.

**Comment by Vdauphin** [comment]
Your first message said it is not working with no modifications
Then you are telling me it is not working after your modification

> its a problem soo problematic that carries over to another mission.

It is up to you to ask help and share your problem. If you want accurate help, please share your change (like your .pbo may be?) because I am not god, I don't know what you have done.
Also, I don't care if you go to an other mission.

**Comment by RoqueTHEGAMER** [comment]
Here is the pbo, the files changed are:
mission.sqm
init.sqf
description.ext
stringtable.xml
initPlayerLocal.sqf
onPlayerRespawn.sqf
onPlayerKilled.sqf

mission.sqf
param.hpp

core\fnc\city
init.sqf

core\fnc\ied
allahu_akbar.sqf

core\fnc\mil
unit_create.sqf
create_hideout_composition.sqf
hd_hideout.sqf

core\fnc\side
rescue.sqf
kill.sqf

[Persistente_Chernarus.cup_chernarus_A3.zip](https://github.com/Vdauphin/HeartsAndMinds/files/6018409/Persistente_Chernarus.cup_chernarus_A3.zip)

**Comment by Vdauphin** [comment]
Thank you.

**Comment by Vdauphin** [comment]
You changed player side and it looks like the initial author didn't handle that case for suicider. The suicider still look for west side instead of east.

**Comment by RoqueTHEGAMER** [comment]
oh, makes sense. I was on the east side playing as russians and I tried to change the suicider voice to be a oorah charge like company of heroes 2, since they are not islan.
