### ISSUE TITLE
Heal Civilian task is stuck in single player

### ISSUE THREAD

**Issue by RoqueTHEGAMER** [Vdauphin/HeartsAndMinds#1072]
in the file civtreatment.sqf
in the line 85

`
waitUntil {sleep 5; (_taskID call BIS_fnc_taskCompleted || !(playableUnits inAreaArray [getPosWorld _unit, 5000, 5000] isEqualTo []))};
`
playableUnits does not work in single player, it will always return a empty array, it makes impossible to test and debug the task
switchableUnits works for single player but is unreliable for multiplayer

My recommendation is swap for this line of code:

`
if (isMultiplayer) then {
	waitUntil {sleep 5; (_taskID call BIS_fnc_taskCompleted || !(playableUnits inAreaArray [getPosWorld _unit, 5000, 5000] isEqualTo []))};
	} else {
	waitUntil {sleep 5; (_taskID call BIS_fnc_taskCompleted || !(switchableUnits inAreaArray [getPosWorld _unit, 5000, 5000] isEqualTo []))};
};
`

**Comment by RoqueTHEGAMER** [comment]
The same issue happens in the file mines.sqf line 108
and civtreatment_boat.sqf line 56

**Comment by Vdauphin** [comment]
Hello,

This mission doesn't work in singleplayer as said in readme

> playableUnits does not work in single player,

Yes, BI should fix that I think

> it makes impossible to test and debug

Just use the arma3server.exe instead of the arma3.exe
Or just use the multiplayer then host tap for quick test, the `playableUnits` works here

Cheer

**Comment by RoqueTHEGAMER** [comment]
It's because I like the single player version for debug purposes and is faster for in and out.

**Comment by Vdauphin** [comment]
there are no difference between single player and hosted multiplayer
