### ISSUE TITLE
Rally point system is unreliable

### ISSUE THREAD

**Issue by RoqueTHEGAMER** [Vdauphin/HeartsAndMinds#1074]
Some players can't teleport to the rally point, some join later in the game and they are from the same group as the one who placed it.
All those players are inside the same group that was set up in the mission.
I am using the latest Version of the mission.

**Comment by Vdauphin** [comment]
Well, this is the BI Respawn system so you should create a ticket to BI if something doesn't work.

**Comment by RoqueTHEGAMER** [comment]
I don't remember BI adding compatibility with ACE interaction, the arsenal box does not show the action to teleport to the rally point for some players.

**Comment by Vdauphin** [comment]
Create a proper issue with the template then

**Comment by RoqueTHEGAMER** [comment]
Never mind about it, we will just avoid use it, too much trouble reporting it.
