### ISSUE TITLE
Save file loads but doesn't change mission parameters.

### ISSUE THREAD

**Issue by PixelEgor** [Vdauphin/HeartsAndMinds#1105]
**Arma 3 Version:** `2.04` stable
**CBA Version:** `3.15.3.210310` stable
**ACE3 Version:** `3.13.6` stable
**Hearts and minds Version:** `1.21.3` stable

**Mods:**
```
- CBA_A3
- ace
- ACEX
- ACE EXTENSION (Animations and Actions)
- RHSAFRF
- RHSUSAF
- RHSGREF
- RHSSAF
- RHS ACE COMPAT
- 3CB FACTIONS
- ACRE2
```

**Description:**
- Save file doesn't change Mission Parameters
- Mission file loads changes such as, an object spawned from the logistic point. But the database doesn't actually change the mission parameters on complete server restart.

**Steps to reproduce:**
- Load the mission on a dedicated server
- Save the game
- Log off the server
- Restart the server
- Log back in

**Mission FIle**
[BTC.co@30_Hearts_and_Minds.Altis.zip](https://github.com/Vdauphin/HeartsAndMinds/files/6562069/BTC.co%4030_Hearts_and_Minds.Altis.zip)

**RPT log file:**
- Before Restart https://pastebin.com/SUeL5ntY
- After Restart https://pastebin.com/jZY2wFsx

**Side Notes**
- It is probably my own server coding that breaks stuff, since i basically know nothing about Arma servers
- I used Fox's Arma Server Tool Extended Rewrite (FASTER) to set it up.

**Comment by Vdauphin** [comment]
Hello,

> Mission file loads changes such as, an object spawned from the logistic point. But the database doesn't actually change the mission parameters on complete server restart.

Database doesn't save mission parameter because you may want to change them between restart.
You can setup default value here: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/param.hpp

Cheers

**Comment by PixelEgor** [comment]
Oh, thank you for such a fast answer!
