### ISSUE TITLE
save issue

### ISSUE THREAD

**Issue by valdirsegadas** [Vdauphin/HeartsAndMinds#1117]
Gentlemen, I'm having a problem when I try to save my H&M campaign, because whenever I try to save or with auto save I get the following error.

what could it be????
I imagine it's some modified vehicle from the btc_veh_ VARIABLES??...
Can someone help me?

14:06:58 Client "PLAYER NAME edited for secure" - client's ticket has become invalid. Code: 6
14:06:58 Client: Remote object 10:57 not found
14:06:58 Error in expression <_data pushBack [];

private _fakeViV = isVehicleCargo attachedTo _x;
if (
isNul>
14:06:58 Error position: <isVehicleCargo attachedTo _x;
if (
isNul>
14:06:58 Error isvehiclecargo: Type Array, expected Object
14:06:58 File mpmissions__cur_mp.UMB_Colombia\core\fnc\db\save.sqf..., line 163
19:29:57 Server: Object 0:0 not found (message Type_184)

**Comment by Vdauphin** [comment]
Hello,
Try to remove what you have changed until it works
Cheers
