### ISSUE TITLE
Change Addon Config

### ISSUE THREAD

**Issue by fidaperkasa** [Vdauphin/HeartsAndMinds#1122]
When I changed addon config  using our daily config mission also I change the default helicopter to RHS, then, I got a problem when running this in server dedicated, the slot list is not available, but when I run it in local, all slot is available. whats wrong with this?

**Comment by Vdauphin** [comment]
Hello,

> the slot list is not available, but when I run it in local, all slot is available.

This mean your server doesn't load some mod

Cheers

**Comment by fidaperkasa** [comment]
ahh i see. but if I directly upload its mission, its no problem

**Comment by Vdauphin** [comment]
>  if I directly upload its mission, its no problem

If you upload the H&M vanilla version, it is normal that you don't have problem
The vanilla doesn't use any mod you are try to load from your server
