### ISSUE TITLE
Replace btc_veh already save with a new

### ISSUE THREAD

**Issue by canprod** [Vdauphin/HeartsAndMinds#1133]
Salut Vdauphin, 
J'espere que ça va, on te vois plus trop sur le ts. 
I have a question, is it possible to replace a btc_veh already save by a new one different. Thanks

**Comment by Vdauphin** [comment]
Hello
Yea I am trying to enjoy bar before the next wave!

> I have a question, is it possible to replace a btc_veh already save by a new one different.

You can't but you still can add vehicle with the garage and delete with Zeus old vehicles

Cheers

**Comment by canprod** [comment]
if u delete old vehicule, there is a probleme during the load of the save ?

**Comment by Vdauphin** [comment]
Well, it has been fixed in 1.17 see https://github.com/Vdauphin/HeartsAndMinds/pull/451

**Comment by canprod** [comment]
yes but a example, i have a vehicule that is sanitarian, and i delete it. I want a new vehicule that is sanitarian ( ace thing) too. How do i do that ?

**Comment by canprod** [comment]
thanks for the reply with zeus

**Comment by Vdauphin** [comment]
The ace compat should make it sanitarian. It is the point of ace compat (ie: adding feature to mod which doesn't provide such feature)
Also are you sure you can't make a vehicle sanitarian with Zeus? I remenber that I fixed this feature a while ago https://github.com/acemod/ACE3/pull/7107
Then the https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/common/getVehProperties.sqf fonction should capture this sanitarian statu and apply it again after server restart

**Comment by canprod** [comment]
ok thanks, it's a good test i will try it
