### ISSUE TITLE
How Do I Save The Game?

### ISSUE THREAD

**Issue by SenjyMaster** [Vdauphin/HeartsAndMinds#1150]
The Save on the esc dont work and the game dont autosave...

**Comment by Vdauphin** [comment]
https://github.com/Vdauphin/HeartsAndMinds/issues/1120#issuecomment-866539495

**Comment by SenjyMaster** [comment]
The Mission Is 100 Original and the database option dont show... And I Hosting From The Game itself...

**Comment by Vdauphin** [comment]
http://vdauphin.github.io/HeartsAndMinds/#introduction-

**Comment by SenjyMaster** [comment]
What iam supossed to read on it?

**Comment by Vdauphin** [comment]
> This mission is built for...

**Comment by SenjyMaster** [comment]
Ok... Dont have any workaround on it?

**Comment by Vdauphin** [comment]
No: 
- some feature are built to work on dedicated server
- this is supposed to be played in coop
- splitting client rendering and ai calculation will drasticly increase your fps
Also, every Arma client have a dedicated A3 .exe already install (`arma3server_x64.exe`)
