### ISSUE TITLE
Logistics Box not working

### ISSUE THREAD

**Issue by SleekSycko** [Vdauphin/HeartsAndMinds#1153]
### Discussed in https://github.com/Vdauphin/HeartsAndMinds/discussions/1148

<div type='discussions-op-text'>

<sup>Originally posted by **SleekSycko** July 30, 2021</sup>
When trying to acquire an item from the logistics box it give error: Line26 ((count _main_class) - 1) do { in core\fnc\log creat_load.sqf
is not a variable. How do I fix this? 

Sorry if easy answer. new to scripting.</div>

**Comment by SleekSycko** [comment]
I have not messed with any of the base code other than the mission params. Ported the map to lythium

**Comment by Vdauphin** [comment]
Create an issue with the bug report template
