### ISSUE TITLE
New faction dont spawn

### ISSUE THREAD

**Issue by Skyrbose** [Vdauphin/HeartsAndMinds#1170]
Hi, I created a new faction with custom weapon and more to have a custom insurgency for this mode in a Star Wars RP. The factions is all good, all works fine, but the mode dont spawn any enemy IA when I use only that faction. Can be cause it dont have groups or dont have a parameter (like _lmg or _teamleader) ?

[config.txt](https://github.com/Vdauphin/HeartsAndMinds/files/7078818/config.txt)

**Comment by Vdauphin** [comment]
Hello,
You just have to follow this: http://vdauphin.github.io/HeartsAndMinds/Add-factions
Cheers
