### ISSUE TITLE
ARMA crash when towing vehicle with ARMA 2.06

### ISSUE THREAD

**Issue by M3dinar** [Vdauphin/HeartsAndMinds#1195]
**Arma 3 Version:** `2.06` (stable)
**CBA Version:** `CBA_A3 v3.15.6.211004` (stable)
**ACE3 Version:** `3.13.6` (stable)
**Hearts and minds Version:** `1.21.7` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
ARMA 3 crashed when "tow" option is released in ace menu.
It worked fine before ARMA 2.06.

**Steps to reproduce:**
-Launch ARMA
-Start the EDEN editor and select Tanoa
-Open the scenario
-Hit play
-Move the towed car next to the towing one (make sure to avoid the "too far" message when tow option is released)
-Interact with the towed car > Logistic > Hook
-Interact with the towing car > logistic > Tow
-ARMA 3 freeze, task manager tells that it get no response from ARMA.
-Kill ARMA 3 from task manager or hard reset your computer

**Add mission file:**
- 1.21.7, tanoa mission pack

**RPT log file:**
[Arma3_x64_2021-10-08_17-25-52.txt](https://github.com/Vdauphin/HeartsAndMinds/files/7312459/Arma3_x64_2021-10-08_17-25-52.txt)

**Comment by Vdauphin** [comment]
Hello,
Thanks for the report, I am investigating
Looks like an BI issue: https://feedback.bistudio.com/T161256
Cheers

**Comment by M3dinar** [comment]
Thanks for the quick answer.
I will apply the patch for our current mission.
