### ISSUE TITLE
Side mission hostage would throw error about _pos not found if a building has only one position inside

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#1287]
**Arma 3 Version:** `2.06`
**CBA Version:** `irrelevant`
**ACE3 Version:** `irrelevant`
**Hearts and minds Version:**  `master_daily (036ffa1)`

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Side mission hostage would throw error about _pos not found in cities without enterable buildings, error report below:
```
20:50:51 Error in expression <tive = _group_civ createUnit [_civType, _pos, [], 0, "CAN_COLLIDE"];
waitUntil {>
20:50:51   Error position: <_pos, [], 0, "CAN_COLLIDE"];
waitUntil {>
20:50:51   Error undefined variable:_pos
20:50:51 File C:\Users\GoldJohnKing\Documents\Arma 3\mpmissions\H&M_Daily.lythium\core\fnc\side\hostage.sqf..., line 60
```

**Steps to reproduce:**
- Spawn hostage side mission in a city without enterable buildings, the error will occurs immediately.
- For example, MozaratDeath is a `NameVillage` without any buildings, see below picture.
![Arma3_x64 2022-01-13 21-00-00](https://user-images.githubusercontent.com/26923626/149334957-858dd703-ddef-4c19-8183-bd772f2548b9.png)

**Comment by Vdauphin** [comment]
Hello,

Missing .rpt

Cheers
