### ISSUE TITLE
Interaction doesn't existy anymore on the Camera and intels

### ISSUE THREAD

**Issue by Raz0rLegend** [Vdauphin/HeartsAndMinds#1315]
**Arma 3 Version:** `2.06.148819` Profiling
**CBA Version:** `3.15.6.211004` Stable
**ACE3 Version:** `3.14.1.65` stable
**Hearts and minds Version:** `1.22` Stable

**Mods:**
```
- CBA_A3
- ace
- H&m
```

**Description:**
-I don't have any interactions on the camera anymore. 

**Steps to reproduce:**
-activate a city, spawn on the camera

**Add mission file:**
- This is the zip downloaded from the Master branch.

![20220215123055_1](https://user-images.githubusercontent.com/75459640/154054523-142f7275-5028-4a38-b84f-e104ecc70b8e.jpg)

**Comment by Raz0rLegend** [comment]
I had some issues with a new arma Objects. Like the computer where i used to put the Add_Actions Day & Night. And the Jerrycan too.
I tried to write the code inside the int like this.
```c++
{[_x, 0, ["ACE_MainActions"], _action] call ace_interact_menu_fnc_addActionToClass;} forEach [
    "Land_Camera_01_F", 
    "Land_HandyCam_F"];
```

**Comment by Vdauphin** [comment]
Hello,

![20220215131013_1](https://user-images.githubusercontent.com/14364400/154059798-f036b2d5-e3cc-40fb-b562-dd2ae1509cc0.jpg)


Please fill up the issue template

Cheers

**Comment by Raz0rLegend** [comment]
I tried several times and i just rebooted the arma 3 Launcher. Just with Ace and CBA it works now.
I know for the h&m mod, it was to say "running h&m with those 2 mods".

It should come from a mod. I''ll investigate.
