### ISSUE TITLE
Mission loading not correctly

### ISSUE THREAD

**Issue by WillemsMaes** [Vdauphin/HeartsAndMinds#1353]
Hello,

I have a problem with my mission which doesn't load properly on my dedicated server.

I see everything like if I was launching my mission in eden editor. How can I fix this problem ? See the screen below :
![Map_problem](https://user-images.githubusercontent.com/101825322/163684653-c0f20097-fdb7-4de2-974b-682b61b1bec6.png)

**Comment by Tetlys** [comment]
What about it isn't loading properly?

**Comment by WillemsMaes** [comment]
I found the problem myself, I just launched the server in debug mode x)
