### ISSUE TITLE
Loading problem 

### ISSUE THREAD

**Issue by SayliTv** [Vdauphin/HeartsAndMinds#1368]
Hi, I have a problem when I try to load the game. 
I still respect everything correctly 

https://zupimages.net/viewer.php?id=22/17/of3w.png

**Comment by Vdauphin** [comment]
Hello,

Check your .rpt for error and correct them until they disappear
https://community.bistudio.com/wiki/Crash_Files

Cheers

**Comment by SayliTv** [comment]
Yes tank's  <3
