### ISSUE TITLE
No save option?

### ISSUE THREAD

**Issue by UnRealxInferno** [Vdauphin/HeartsAndMinds#1374]
**Arma 3 Version:** `x.xx` (stable)
**CBA Version:** `3.x.x` (stable)
**ACE3 Version:** `3.x.x` (stable)
**Hearts and minds Version:** `1.x.x` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
No save option when logged as admin

**Steps to reproduce:**
attempt to save, there is no option to save in the ace menu

**Add mission file:**
- Zip your .pbo mission file, drag and drop it here.

**RPT log file:**
Not available

[=BTC=co@30_Hearts_and_Minds.Beketov.zip](https://github.com/Vdauphin/HeartsAndMinds/files/8696968/BTC.co%4030_Hearts_and_Minds.Beketov.zip)

**Comment by Vdauphin** [comment]
Hello,

See http://vdauphin.github.io/HeartsAndMinds/#introduction-
and this for the how to save http://vdauphin.github.io/HeartsAndMinds/InGame-documentation#headless--database

Cheers
