### ISSUE TITLE
Error problem that prevents enemy spawn

### ISSUE THREAD

**Issue by SayliTv** [Vdauphin/HeartsAndMinds#1379]
Hello, I have a problem with spawn IA, it puts me the error as in this photo: https://zupimages.net/viewer.php?id=22/21/tmql.jpg
and then it keeps me from spawn I don’t know that comes

**Comment by Vdauphin** [comment]
Hello,

No idea also here
Check your .rpt for errors and correct them until they disappear
https://community.bistudio.com/wiki/Crash_Files

Cheers

**Comment by SayliTv** [comment]
Ho ok nice
