### ISSUE TITLE
Syntax Error?

### ISSUE THREAD

**Issue by Linxuski** [Vdauphin/HeartsAndMinds#1384]
I just downloaded the newest version of H&M and tried to host a server with it but it just closes my game, stating that it encountered a 'c' instead of a ']'.
![20220623_114710](https://user-images.githubusercontent.com/50371587/175282397-e9cc6759-f566-41d2-b7bc-bfaaf9d00189.png)

**Comment by Vdauphin** [comment]
Hello,
Fill the issue template
No error here
Cheers

**Comment by Linxuski** [comment]
Hi,
Yeah, so it turns out the error was caused by the program I was using to unpack the pbo. My apologise for that.
