### ISSUE TITLE
Add: Project Opfor Support

### ISSUE THREAD

**Issue by sargken** [Vdauphin/HeartsAndMinds#145]

**Comment by Vdauphin** [comment]
Did you already implement any faction from this mod ? 
- If yes, could you please share your code/class name you are using ?
- if not, which faction would you like to play ?

**Comment by Vdauphin** [comment]
@sargken ?

**Comment by Vdauphin** [comment]
https://github.com/ShuraDE/co_Hearts_and_Minds.Altis/commit/2d5bdb1f5541227623eafb1fabeb5cafdfa8edf3

**Comment by Vdauphin** [comment]
@ShuraDE can you push this commit https://github.com/ShuraDE/co_Hearts_and_Minds.Altis/commit/2d5bdb1f5541227623eafb1fabeb5cafdfa8edf3 to https://github.com/Vdauphin/HeartsAndMinds/tree/master_daily . Others people are interesting by this mod support.
Thank you!

**Comment by sargken** [comment]
@Vdauphin - Sorry I have been away from my computer for a long time. I think we should change the name to Project Opfor as Leights Opfor is Depreciated and I will look into it tonight about pushing some commits your way.
