### ISSUE TITLE
Inverted values in "Intel from dead bodies" fields

### ISSUE THREAD

**Issue by STyx2909** [Vdauphin/HeartsAndMinds#1469]
It took me too many hours to figure it out, LOL. It was so obvious...

```
  class btc_p_info_chance { // Intel from dead bodies chance:
        title = __EVAL(format ["      %1", localize "STR_BTC_HAM_PARAM_CACHE_DEADINFO"]);
        values[]={0,10,20,30,40,50,60,70,80,90,100};
        texts[]={"100 %","90 %","80 %","70 %","60 %","50 %","40 %","30 %","20 %","10 %","0 %"};
```
The values are inverted regarding the text, meaning setting it at 30% is in fact a 70% chance to find something. Or the parameter is not explained in a correct way.

I discovered it, because I am experiencing problems to set parameters up to my server I modify the config file and upload it afterwhile.
Similar results on my dedicated server and local multiplayer.

Hope it helps.

Joining screeenshots and config files.
![Arma3_x64 2023-01-07 11-35-33](https://user-images.githubusercontent.com/76572473/211146051-b2aea5e5-7ef4-4c34-b104-7d8ef3ef821e.png)
[param.zip](https://github.com/Vdauphin/HeartsAndMinds/files/10366001/param.zip)

**Comment by Vdauphin** [comment]
Hello,
There is no bug here
If it is too much confusing for you, you can make a pull request to change that
Cheers

**Comment by STyx2909** [comment]
Hi!
Sorry.
