### ISSUE TITLE
Resupply Rearm Source

### ISSUE THREAD

**Issue by eric963** [Vdauphin/HeartsAndMinds#1496]
Arma 3 Version: 2.12.150301
Branch: main 
CBA Version: 3.15.2
ACE3 Version: 3.15.8
Hearts and minds Version: 1.23.1 Tanoa

Mods:
 CBA_A3
 ACE
 RHS

When using the logistics point to resupply our ammo vehicle we select "Resupply rearm source" we are getting the message "Fueling completed" and the ammunition points in the ammo vehicle remain unchanged.

I could find nothing in the rpt file.

![20230324002929_1](https://user-images.githubusercontent.com/20633883/227428487-d31a2369-2ed4-41a9-a3a2-905a76c88e6f.jpg)
![20230324002942_1](https://user-images.githubusercontent.com/20633883/227428499-1331846a-e494-4dca-8b06-a09effcecd13.jpg)

**Comment by Vdauphin** [comment]
Hello,

Looks like you didn't select the correct option

I just notice the `ace_rearm_fnc_makeSource` must be executed server side, fix incoming

Cheers

**Comment by eric963** [comment]
Just verified that i am selecting the "Resupply rearm source" option.

Line 44 of the rearmSource.sqf is calling for the refuel hint, should it be some type of rearm hint?

(localize "STR_ACE_Refuel_Hint_Completed") call CBA_fnc_notify;

Thanks!!

**Comment by Vdauphin** [comment]
The french translation look different, I will create a dedicated string entry
