### ISSUE TITLE
Capture of cities

### ISSUE THREAD

**Issue by LeonFAM** [Vdauphin/HeartsAndMinds#1522]
**Arma 3 Version:** 2.14.150957 stable
**CBA Version:** v3.15.8.220912 stable 
**ACE3 Version:** 3.15.2 stable
**Hearts and minds Version:** 1.23.3 

**Mods:**
- CBA_A3
- ace

**Description:**
 since version 1.23.3 the cities capture from the rest not after restarting the server an idea?

**Comment by Vdauphin** [comment]
Hello,

Thank you for your report.
Please fill the issue template with all the required information.

Cheers
