### ISSUE TITLE
More civilians and traffic?

### ISSUE THREAD

**Issue by UncreatedLemon** [Vdauphin/HeartsAndMinds#157]
Would this be possible to increase the ambient feel to the mission?

**Comment by Vdauphin** [comment]
civilians number depend on city type and number of house. In big city with lot of house, you will find more civilian.  Launch the mission in debug mode, you will see the civilian spawn behavior. It is pretty realistic.

I realized a lot of civilian spawn in "close house" like you can see here for container : https://github.com/Vdauphin/HeartsAndMinds/pull/151 (after this FIX I realized there are more building affected by this bug ^^). So if you are playing on map with a low open house number you could have less civilian. To resolve that I am working on https://github.com/Vdauphin/HeartsAndMinds/pull/155 

For traffic, I will check what I can do :)

**Comment by Vdauphin** [comment]
For Civ traffic the main issue is coming from Arma 3 1.60, a lot of vehicle have accident. So they don't travel correctly. Actually, the mission remove them to avoid performance issue.

The APEX improve AI driving and feedback are here : https://forums.bistudio.com/topic/191515-ai-driving-feedback-topic/

**Comment by Vdauphin** [comment]
https://github.com/Vdauphin/HeartsAndMinds/pull/158

**Comment by Vdauphin** [comment]
-
