### ISSUE TITLE
"Require Object" can cause massive amounts of damage to player(s)

### ISSUE THREAD

**Issue by Sora012** [Vdauphin/HeartsAndMinds#1592]
**Arma 3 Version:** `2.16` (stable)
**CBA Version:** `3.16` (steam workshop)
**ACE3 Version:** `3.16` (steam workshop)
**Hearts and minds Version:** `1.23.7` (stable + git master with base location change)

**Mods:**
`https://steamcommunity.com/sharedfiles/filedetails/?id=1798015776`

**Description:**
Using "Require Object" can cause a massive amount of damage or even death to a player after touching the objects

**Steps to reproduce:**
1) "Require Object" at the logistics point and swap to a h-barrier and apply -> touch object and receive no damage and no death even after raising/lowering
2) "Require Object" at the logistics point and swap to a h-barrier then swap away and then swap back and apply -> touch object (may need to raise/lower) and receive massive amounts of damage or death

- [Youtube Example](https://www.youtube.com/watch?v=pXPRiMpfF5o)

**RPT log file:**
- [A3 Log](https://gist.github.com/Sora012/a5ee15faf4d1d1eeebbc369cebedc64d)

**Comment by Vdauphin** [comment]
Hello,

Can you try with only CBA and ACE?

Cheers

**Comment by Sora012** [comment]
With the only exception of the base having been moved to a different location. I nuked the server profile, disabled all mods excluding CBA/ACE, and the issue still occurs.

I have updated the RPT in the above original comment, uploaded another [video](https://www.youtube.com/watch?v=s_r151VsDZo)

**Comment by Vdauphin** [comment]
Open the chemical detector and check if you are not contaminated

**Comment by Sora012** [comment]
Here is another [video](https://www.youtube.com/watch?v=IGJ8qEyli_g) with chemical detector shown. This is the only mission I've played that has this issue.

**Comment by Vdauphin** [comment]
Please provide the requested .rpt and .pbo

**Comment by Sora012** [comment]
Vanilla Release, ONLY CBA/ACE, with RPT, and Screenshot of proof it occurs.

[A3.zip](https://github.com/Vdauphin/HeartsAndMinds/files/14813233/A3.zip)

**Comment by Vdauphin** [comment]
From what I see, you just have to avoid to press any key when releasing an object

**Comment by Sora012** [comment]
It was originally discovered when we were moving props under fire, and air dropping them, but we were unsure what was causing it. However waiting about half a second or longer between releasing the key and releasing the prop, I wasn't able to recreate it..  But that was only with a small amount of testing, Is this fixable?

**Comment by Vdauphin** [comment]
> Is this fixable?

I investigated yesterday but no luck, I will try this week end

**Comment by Vdauphin** [comment]
Apparently it is a A3/ACE that ACE team fixed by disabling damage
Here is a quick code to reporduce the bug. 
_Note that you must run when the object detach to reproduce the bug_

```sqf
btc_log_placing_obj = cursorObject;
private _bbr = 0 boundingBoxReal btc_log_placing_obj; 
 
btc_log_placing_h = (btc_log_placing_obj modelToWorldVisual [0, 0, 0] select 2) - (player modelToWorldVisual [0, 0, 0] select 2); 
btc_log_placing_d = 1.5 + abs(((_bbr select 1) select 1) - ((_bbr select 0) select 1));


btc_log_placing_obj attachTo [player, [0, btc_log_placing_d, btc_log_placing_h]];

[player, "blockDamage", "fixCollision", true] call ace_common_fnc_statusEffect_set;
[btc_log_placing_obj, "blockDamage", "fixCollision", true] call ace_common_fnc_statusEffect_set;

[] spawn {sleep 5; detach btc_log_placing_obj};
```

**Comment by Vdauphin** [comment]
The fix prevent player from getting damage for 2s https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_fixCollision.sqf#L24
If you don't smash your head endlessly you should be fine
