### ISSUE TITLE
CTD when "engineOn" with specific vehicle.

### ISSUE THREAD

**Issue by TheLocalPub** [Vdauphin/HeartsAndMinds#1608]
**Description:**
 When a user gets in the drivers seat of a specific humvee, and turns on the engine, the user will instantly hard crash back to desktop.
We know it's related to Hearts and minds as the humvee classname(s) in question were then tested on a blank mission and there was no problems.
Also, every other vehicle (no matter the type) works just fine in H&M. You can enter the drivers seat, turn on the engine, and drive/fly.
I've disabled the spectrum stuff in the params, as when searching through the files, I could only find references to "engineOn" in the 
checkLoop.sqf and also electronicFailure.sqf - of which both relate to the spectrum stuff.

What makes this a very strange bug is that it only occurs on a very specific type of humvee. Classname `rhsusf_m1151_usarmy_d`
If you search M1151 and try to use _any_ of those humvees, either armed or unarmed, it'll hard crash back to deskstop.
If you use any other unarmoured version of the humvees, for instance `rhsusf_m1025_d_m2`, it's totally fine, no crashes or any other problems.
The bug only happens with this armoured humvee type and I do not know why, even after disabling the spectrum stuff.

**Steps to reproduce:**
- Be in local or dedicated multiplayer - Doesn't work in SP.
- Get into a humvee with any kind of weapon, of the class name `rhsusf_m1151_usarmy_d`, turn on the engine, crash.

**RPT log file:**
- No RPT log due to hard crash.

**Comment by Vdauphin** [comment]
Hello,

Please fill the issue template
No crash from here:
![20240413101527_1](https://github.com/Vdauphin/HeartsAndMinds/assets/14364400/8ab84beb-1e7b-49ca-be7f-05d02163f1d5)

Cheers

**Comment by TheLocalPub** [comment]
You're engine isn't on....

**Comment by Vdauphin** [comment]
I moved both vehicle.
Tested on a dedicated server.

**Comment by TheLocalPub** [comment]
Wow. 
Very strange.
I've done absolutely nothing to these vehicles to cause this or edited anything related to vehicles.

I'm going to try placing the same vehicle in the example mission of your but with our mods and seeing if the same thing occurs.
If not, then I can narrow it down to my specific mission, although yet again... I have utterly no idea why this is happening

Thanks. I'll probably report back sometime.

**Comment by TheLocalPub** [comment]
> Wow. Very strange. I've done absolutely nothing to these vehicles to cause this or edited anything related to vehicles.
> 
> I'm going to try placing the same vehicle in the example mission of your but with our mods and seeing if the same thing occurs. If not, then I can narrow it down to my specific mission, although yet again... I have utterly no idea why this is happening
> 
> Thanks. I'll probably report back sometime.

Nope. It works in your mission.
I really don't know.

**Comment by TheLocalPub** [comment]
So we found out what the issue was... I changed the `btc_startDate` to a British format, using dd/mm/yy, instead off yy/mm/dd.

Fixed!

**Comment by TheLocalPub** [comment]
Reopening with an update.
So after changing the date format to a yy/mm/dd. It appears to now work in SP and local MP, but upon dedicated server testing, it still CTDs.

I saw above you mentioned you tested it on a dedicated server and it worked fine, which I find odd considering my version now works in SP and local MP but not dedicated MP, as before it didn't work in any.
It's almost like I partially fixed it. 

Will continue to look into it.

**Comment by TheLocalPub** [comment]
And again.... it was magically fixed.
For whatever unknown reason, It's chosen to finally start working in dedicated MP. Very odd.
