### ISSUE TITLE
Guide to rearming?

### ISSUE THREAD

**Issue by UncreatedLemon** [Vdauphin/HeartsAndMinds#163]
Does anyone have a guide on how to rearm with the spawn box (Spawning ammo for vehicles?)

**Comment by Vdauphin** [comment]
Admin need actually to add the ACE3 rearm module in editor (mission.sqm). This only works if rearming is setting on entire magazine or amount based on caliber (not for entire vehicle setting).

Here is your vehicle with low amo : 
![107410_20160709102349_1](https://cloud.githubusercontent.com/assets/14364400/16706929/48a6c0e0-45bf-11e6-83b6-1dc709d50c20.png)

Select on logistic point red box your vehicle type and the corresponding caliber : 
![107410_20160709102032_1](https://cloud.githubusercontent.com/assets/14364400/16706931/4bc04e4a-45bf-11e6-8f9f-792b27b0484d.png)

Take amo in your hands (important), interact with the vehicle and select rearm option :
![107410_20160709102204_1](https://cloud.githubusercontent.com/assets/14364400/16706934/5a67e37c-45bf-11e6-8fc5-addea77f06ba.png)

Wait : 
![107410_20160709102210_1](https://cloud.githubusercontent.com/assets/14364400/16706932/4dfdd524-45bf-11e6-8561-1693fb7b52d1.png)

Done !
![107410_20160709102244_1](https://cloud.githubusercontent.com/assets/14364400/16706940/7c55b090-45bf-11e6-93b4-209d28e2fa71.png)
