### ISSUE TITLE
Reduce number of large enemy force spawning in map to respond to attacking cities.

### ISSUE THREAD

**Issue by ZaidRehan** [Vdauphin/HeartsAndMinds#1655]
Hello, during my Hearts and Minds runs with my unit, we have been dealing with a huge increase in lag due to a large enemy force spawning in the corner of the map which seems to be responding to cities/towns we have attacked, most likely a reinforcements unit. However, the issue I have is that its a very large force about 50-100 units that get spawned in which cause an immense amount of lag.

I have looked through the settings and dumbed them down but I may be missing something or not tweaking the right setting. Was wondering where I can find the reinforcements function and lessen the amount of responding units.

**Comment by Vdauphin** [comment]
Hello,

This should not happen
Might be a map not following BI standard

Cheers
