### ISSUE TITLE
Attempting to use SPE Wehrmacht West Faction but spawns FIA Independent Faction instead

### ISSUE THREAD

**Issue by ZaidRehan** [Vdauphin/HeartsAndMinds#1660]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)
**Hearts and minds Version:** `1.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- Spearhead DLC
- IFA3 AIO
- Faces of War
- US General Equipment & Accessories
- simc_lhd
- Free World Armoury
- Flying Legends
- Naval Legends
- Secret Weapons
- ACRE2
- WW2_SPEX
- CUP Terrains - Core
- CUP Terrains - Maps
```

**Description:**
- A clear and concise description of what the bug is.
- Add a detailed description of the error. This makes it easier for us to fix the issue.

Hello, when making a custom H&M Mission in the Utah Beach map from the WW2 SPEX mod, I set the parameters to use the SPE Wehrmacht Faction, however, whenever I attempt to play it, instead of the Wehrmacht faction being spawned in, the FIA takes their place and is on the Independent side, not even the West/Blufor side like the Wehrmacht Faction is.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
- Add screenshots by drag and drop it here.

Set parameters to Wehrmacht Faction SPE, click play. Test by teleporting to danger areas. FIA spawns instead.

**Add mission file:**
- Zip your .pbo mission file, drag and drop it here.
[Deployment%20-%20Utah%20WW2.spex_utah_beach.zip](https://github.com/user-attachments/files/17268635/Deployment.20-.20Utah.20WW2.spex_utah_beach.zip)

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and server RPT file (you can also change the file extension to a .txt file and drag and drop it here). An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Location).
[Arma3_x64_2024-10-06_03-16-12.txt](https://github.com/user-attachments/files/17268636/Arma3_x64_2024-10-06_03-16-12.txt)

**Comment by Vdauphin** [comment]
Hello,

You selected `99 - SPE Heavy Ordnance Works: [SPE] Wehrmacht (Side: WEST)` and player side is `west`
You can't fight AI with the same side as you

Cheers

**Comment by ZaidRehan** [comment]
Yes, I forgot to mention. I changed the player units to independent. Is
there something else I need to do to change the player side?

**Comment by Vdauphin** [comment]
http://vdauphin.github.io/HeartsAndMinds/faction_player 
:)
