### ISSUE TITLE
Bonjour la mission secondaire réparer un véhicule ne fonctionne plus ,malgré avoir fait une réparation complète avec le véhicule de réparation.

### ISSUE THREAD

**Issue by djibout60** [Vdauphin/HeartsAndMinds#1665]
<!-- Hello, the secondary mission to repair a vehicle no longer works, despite having done a complete repair with the repair vehicle.

J'utilise un serveur dédié et ça depuis la mise a jours 2.18

**Comment by Vdauphin** [comment]
Hello,
Please use english next time.
Fix #1663 
Cheers

**Comment by djibout60** [comment]
Hello, the secondary mission to repair a vehicle no longer works, despite having done a complete repair with the repair vehicle
