### ISSUE TITLE
Question: Is this playable without ACE3?

### ISSUE THREAD

**Issue by Dexious** [Vdauphin/HeartsAndMinds#200]
Hello as title says,

Can i remove ACE3 and still be able to play this mission?

Thanks :)

**Comment by Vdauphin** [comment]
Hello!
This mission is oriented for military simulation and has a deep ACE3 implementation. So yea you can't play it without ACE3. 
ACE3 gives all interaction (talk to civil and enemy), logistic system, rearm system, more complex side mission, possible.
See you soon.

**Comment by Dexious** [comment]
Thank you very much for your answer :)

Keep up the good work!

**Comment by Vdauphin** [comment]
Thanks !
