### ISSUE TITLE
Spawning tons of AI upon callup of Side Missions

### ISSUE THREAD

**Issue by Breech99** [Vdauphin/HeartsAndMinds#207]
![heartmindbug](https://cloud.githubusercontent.com/assets/21293496/18774003/468258c4-811a-11e6-8ac3-2cf0bdd31881.jpg)

I'm not sure what I did, but I may have broken it or a bug. Reporting as a bug as to try and find a fix to this issue. When commander player requests side mission, -dedicated server fps 48 with i7 6700k - spawns side mission, also north of the side mission in this instance, spawns extra AI about 100 clumped, server fps drops to 8fps.

**Comment by Vdauphin** [comment]
Hello, you should lauch your mission in debug mod and create side mission to check if it happen everytime.
I never saw this bug. Try different side mission to see if you have this type of behavior. But I think it is link to your create_veh.sqf you created.
Good luck

**Comment by Breech99** [comment]
Ugh. I didn't have a create_veh.sqf file but, I did find that somehow I got an extra copied file of create_traffic over from the core/fnc/civ folder also pasted into core/fnc/city sub folder. Holy crap, that's what I get for staying up too late and staring at a screen for too long! lol. I'll have to go over the other folders and test.

**Comment by Breech99** [comment]
I'm not finding the issue with the mission. I have mixed some of the working 1.16 coding into the 1.15. So far it's been stable all but for that one issue of a clump spawn. I'll email you the mission file folder so you can take a look at it Vdauphin.

**Comment by Vdauphin** [comment]
I am not at home until monday but after i will take a look. But if in debug mode you dont see any unwanted spawn i dont see what i could do more :/ .

Goood luck

**Comment by Breech99** [comment]
I went back in to the core/def/mission and removed the tank and a few other extra spawns for the mil spawn groups. That, might have done something to create that issue. I'm having trouble recreating but so far seems to make finding main base camps less noticeable by air, which is a good thing.  Maybe the indy AA emplacement via cup or rhs might be in order. I'll keep looking at it.

**Comment by Vdauphin** [comment]
sorry I can't test your mission too much mod. 
I checked the stable branch and I didn't see any issue about tones of IA.
