### ISSUE TITLE
Request: Autosave feature

### ISSUE THREAD

**Issue by Dexious** [Vdauphin/HeartsAndMinds#220]
Hello,

Do you have any plans to make the mission Autosave?

Like have a parameter every X seconds to Autosave.

If not can you tell me what do i have to change to make it call itself and Autosave? Like a "while true" statement.

I'm asking that feature since we auto-restart the server every few hours and in case no admin is online i would like to save the progress. (It's a public server)

Also what is it getting saved right now and in what area?

If i place down an object i bought from the crate will it save anywhere or do i have to use Zeus Curator to build stuff?

Thanks

**Comment by Vdauphin** [comment]
Hello !

> Do you have any plans to make the mission Autosave?

No plan for that at the moment ;) . 

> Like have a parameter every X seconds to Autosave.
> If not can you tell me what do i have to change to make it call itself and Autosave? Like a "while true" statement.

During the saving process you are not suppose to play :/ . Typically if you are playing and saving in same time you will see AI disappearing ... It is needed because the mission need to get all AI alive so after restart you will see the same AI at the same position.

> Also what is it getting saved right now and in what area?

What do you mean ? On the server ? I didn't investigate a lot sorry (see this : https://github.com/Giallustio/HeartsAndMinds/issues/27#issuecomment-147523374) or check BI wiki. Before I implemented Initdb mod for a better database but it is not linux compatible so I dropped the pullrequest (see here)

> If i place down an object i bought from the crate will it save anywhere or do i have to use Zeus Curator to build stuff?

Yes, everything are saved. From player action (create box, store it in a vehicle , ammo in vehicle etc...) to Zeus !!!

**Comment by Dexious** [comment]
Thanks for the answer :+1:

**Comment by Vdauphin** [comment]
> Also what is it getting saved right now and in what area?

It is in your user profile file with extension : .vars.Arma3AlphaProfile
 https://forums.bistudio.com/topic/143834-varsarma3alphaprofile/

**Comment by Dexious** [comment]
It's OK Vdauphin.

I was asking on what was the save script saving. I found it and read on what was being saved. :)

**Comment by Dexious** [comment]
Hello Vdauphin,

I have added "Auto Save" in my edition, if you want have a look at it. It works on my server.

Repository:
https://github.com/Dexious/HeartsAndMinds_Dex

Files edited:
[core\init_server.sqf](https://github.com/Dexious/HeartsAndMinds_Dex/blob/master/%3DBTC%3Dco%4040_Hearts_and_Minds_Altis_Dex.Altis/core/init_server.sqf)
[core\fnc\compile.sqf](https://github.com/Dexious/HeartsAndMinds_Dex/blob/master/%3DBTC%3Dco%4040_Hearts_and_Minds_Altis_Dex.Altis/core/fnc/compile.sqf)
[core\fnc\common\show_hint.sqf](https://github.com/Dexious/HeartsAndMinds_Dex/blob/master/%3DBTC%3Dco%4040_Hearts_and_Minds_Altis_Dex.Altis/core/fnc/common/show_hint.sqf)

Files added:
[core\fnc\db\autosave.sqf](https://github.com/Dexious/HeartsAndMinds_Dex/blob/master/%3DBTC%3Dco%4040_Hearts_and_Minds_Altis_Dex.Altis/core/fnc/db/autosave.sqf) [Added hint at the end]
[core\fnc\db\request_autosave.sqf](https://github.com/Dexious/HeartsAndMinds_Dex/blob/master/%3DBTC%3Dco%4040_Hearts_and_Minds_Altis_Dex.Altis/core/fnc/db/request_autosave.sqf) [It saves every 5 hours and 55 minutes for my needs, change the sleep value]

If you want i can fork and push all the changes but i think i have added and edited too many stuff.
Can i push like selected files?

**Comment by Vdauphin** [comment]
Sorry but I already did it One hour ago ^^ just check before  your last post ;)

https://github.com/Vdauphin/HeartsAndMinds/pull/233

**Comment by Dexious** [comment]
Cheers :+1:

**Comment by Vdauphin** [comment]
Good work man!
