### ISSUE TITLE
Question: Ability to spawn persistent vehicles (Without Zeus)

### ISSUE THREAD

**Issue by Dexious** [Vdauphin/HeartsAndMinds#224]
Hello again! :)

Do you think it could be possible to use VVS (Virtual Vehicle Spawner) script to spawn persistent vehicles so that we can either reinforce an FOB or just use different vehicles?

I know i can spawn them with Zeus, just asking if i could make it so players can spawn too.

Maybe we could use the crate that spawns objects for vehicles too?

**Comment by Vdauphin** [comment]
Hello!

Actually vehicule spawn by Zeus are not persisitant :)
But It is possible to make them persisitant from Zeus or a vehicule spawner (or use the logistic point, if I remember you just have to add the class name of the vehicule and it will spawn and will be persisitant)

But, from my point of view it is against how the mission should be play ... You are suppose to have only  vehicle spawned at the begining and if there are destroyed you are suppose to do a "mission" to recover them. I like it a lot.

**Comment by Dexious** [comment]
We just need a logistic point where we can spawn some vehicles to move them to our FOBs.

I'm not telling you to change the mission at all. It's fine.

Just how we enjoy playing with a bit more freedom and open map.

Spawning FOBs, Checkpoints and all that good stuff.

I might try to add vehicles to "mission.sqf" file with more categories/objects?

You might point me if i need to do something specific?

Although if i could just change VVS where the vehicle is getting spawned, to add the line of code that's being used from your Logistic crate to add the vehicle in the saving list.

**Comment by Dexious** [comment]
Oh and yea objects that i spawn with Zeus are getting saved.

**Comment by Vdauphin** [comment]
> I might try to add vehicles to "mission.sqf" file with more categories/objects?

Yes, you can add a new category like "vehicles" and add class name of vehicles.
Fork my repo and do your change. I will be allow to help you and may be add it has an option in the main branch who know ^^

**Comment by Dexious** [comment]
Instead of doing that i decided to use VVS script that already spawns vehicles so i don't have to write down all the vehicles classes again.

Forum link on the code:
https://forums.bistudio.com/topic/165948-mp-btc-hearts-and-minds/page-23#entry3104081

Mission .pbo here:
https://github.com/Dexious/HeartsAndMinds_Edit

How to test:
Go to crate that spawn objects.
Select Virtual Vehicle Spawn.
Spawn a car.
Save mission.
Load mission.

Sorry i don't know how to use github to send you the changes.
I'll look into it to figure it out.

**Comment by Vdauphin** [comment]
Hello, I think you execute this client side. But the saving process only check server side variabe. So you need to do it : 
`[[_vehicle],{btc_log_obj_created = btc_log_obj_created + [_this select 0];}] remoteExec ["call", 2];`

**Comment by Dexious** [comment]
:+1:  You were right Vdauphin the command was executed client side. It works perfectly fine now! Thank you very much!

I also made it to work with R3F Logistics where i can spawn all that objects without having them placed one by one in the "mission.sqf".

Thanks for all the support so far, making this mission enjoyable to people like me who enjoy it by building FOBs and slowly progress in an open world sandbox :)

I also found out how to Fork and Push changes but it was quite late since you answered me already :)

You can close this.
