### ISSUE TITLE
Question: Interaction with Civs or Enemies spawned from other scripts?

### ISSUE THREAD

**Issue by Dexious** [Vdauphin/HeartsAndMinds#226]
Hello,

I would like to add these:

1) [Enigma Civilians](https://forums.bistudio.com/topic/187810-engimas-civilians-script-release/)
2) [Enigma Traffic](https://forums.bistudio.com/topic/186976-engimas-traffic-script-release/)
3) [Dynamic Combat Generator](https://forums.bistudio.com/topic/188156-dynamic-combat-generator/)

Am i going to be able to interact with the units that the above spawn?
Do they impact the mission in any way? (Killing enemy units that these scripts spawn give reputation?)
Civilian interaction to ask info etc would work?

Just to have a more ambient world to travel on :)

Thanks!

**Comment by Vdauphin** [comment]
Helllo!


> 1) Enigma Civilians
> 2) Enigma Traffic

The mission do it for you x) ! Copy and paste new script is a waste of time and bug source... Prefer to tweak the mission has explain above.

> Am i going to be able to interact with the units that the above spawn?

Yes I think

> Do they impact the mission in any way? (Killing enemy units that these scripts spawn give reputation?)

Yes, performance issu ! and the reputation system will not work.

> Civilian interaction to ask info etc would work?

> Just to have a more ambient world to travel on :)

see : https://github.com/Vdauphin/HeartsAndMinds/issues/157
and  https://github.com/Vdauphin/HeartsAndMinds/wiki/8:-Tweak-civilian-spawn-in-town

**Comment by Dexious** [comment]
Ok thanks for the info :)
