### ISSUE TITLE
Problem with loaded vehicles?

### ISSUE THREAD

**Issue by Dexious** [Vdauphin/HeartsAndMinds#234]
Hello Vdauphin,

I noticed that if i save the vehicles in a non flat area they are getting loaded damaged or not in the exact position they were supposed to be, sometimes they collide with walls or objects nearby.

Did you notice anything similar?

Maybe spawn them 1 meter above the ground to eliminate the chance the vehicle to take damage?

**Comment by Vdauphin** [comment]
hello,
i had a similar issue in the past it should be resolve https://github.com/Vdauphin/HeartsAndMinds/pull/172.
What you are saying sound a little diffrent. I also notice sometimes when vehicles are too close to walls could get damage. But, I don't think I can do more. 
I could test https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/db/load.sqf#L217 : 
- `setPosATL` to have a more accurate position
- `(_x select 0) createVehicle (_x select 1)` with ` CAN_COLLIDE` option to avoid damage
- use `setVectorUp surfaceNormal position`

But I am not sure to have results :/

can you give me some pitures to reproduce the issue?

**Comment by Dexious** [comment]
Here is the link from the base location and vehicle position.
http://imgur.com/a/oTCgn

I have the vehicles away from walls but after each mission load they keep getting closer to objects etc.

I'm sharing you a piece of code that has the same save mechanism in Liberation mission and works.
Objects, vehicles etc spawn on the exact same position after laod without getting damaged or anything with this code.

http://pastebin.com/BaqGBVu6

I'm looking at it to see if it does anything differently with "setVectorUp" or anything else.
Hope it helps.

**Comment by Dexious** [comment]
I see that when you load back the objects you use:
`_obj setPosASL`
but for vehicles you use:
`_veh setPos`

Maybe try setPosASL in vehicles too? Since objects load fine.

I'll give it a shot when i get some free time.

**Comment by Vdauphin** [comment]
Yes I said   that https://github.com/Vdauphin/HeartsAndMinds/issues/234#issuecomment-254661334 I also want to investigate that point when I get free time :) :) :)

**Comment by Vdauphin** [comment]
I resolved the bridge issue with `setPosASL`
https://github.com/Vdauphin/HeartsAndMinds/pull/236
