### ISSUE TITLE
Add: CBA Per Frame Handlers

### ISSUE THREAD

**Issue by Vdauphin** [Vdauphin/HeartsAndMinds#235]
- http://ace3mod.com/wiki/development/arma-3-scheduler-and-our-practices.html

Always use call whenever possible. You should be calling functions chains exclusive and not be relying on spawn/execVM ever. All code should be a chain of execution which is traceable, and not triggered between separate threads.
waitUntil and sleep are banned. If you need to use them, use CBA_fnc_waitUntilAndExecute and CBA_fnc_waitAndExecute instead.
If you need to run code regularily, you should utilize a PFH. spawn/execVM are subject to the Arma 3 scheduler and as such, cannot be relied upon. In order to give your players a consistent gameplay experience, you need to have total control over how and when all of your code runs.
PFHs with a delay of 0 should be utilized at all possible times when the player can see the result of whatever the code is. This applies to missile guidance, bullets, wind, optics, interactive UI, HUDs, rendering and so on. Only if something is not directly visible for the player a larger delay can be used.
- `_veh_type = selectRandom (btc_type_motorized + [selectRandom btc_civ_type_veh]);`

**Comment by Breech99** [comment]
The error code shows that class Destroy {
		icon = \A3\ui_f\data\igui\cfg\simpleTasks\types\destroy_ca.paa;     is already defined. Might be even more of these already defined and kicks back error message defined.
