### ISSUE TITLE
Bug: tasktypes.hpp

### ISSUE THREAD

**Issue by Breech99** [Vdauphin/HeartsAndMinds#241]
Bug in https://github.com/Vdauphin/HeartsAndMinds/pull/239
The error code shows that Line 25 tasktypes.hpp

class Destroy {icon = \A3\ui_f\data\igui\cfg\simpleTasks\types\destroy_ca.paa; is already defined.

Might be even more of these already defined and kicks back error message defined.

**Comment by Breech99** [comment]
Removal coding out destroy line 25 seems to fix the issue, no further issues with script.

**Comment by Vdauphin** [comment]
should fix : https://github.com/Vdauphin/HeartsAndMinds/pull/239/commits/f8c6c9ccd22279f5860317036ac504843bf511a4
