### ISSUE TITLE
Map bug on server.

### ISSUE THREAD

**Issue by MasonAdam** [Vdauphin/HeartsAndMinds#245]
So when my friends and I where playing on my server last night we where running the Hearts and Minds mission I edited it a little bit in the editor replacing vehicles with others, and when we went to look on the map we could see all of the red circles that the scripts where picking up as hostile just like when you check the map when previewing in the editor. I was wondering if you had any clue to and Idea of what that could be? Nothing else shows up, no info on caches or hideouts just the red circles.

Cheers,
Mason

**Comment by Vdauphin** [comment]
hello, has you or your friend destroy all hideouts (5 by default) ?

**Comment by MasonAdam** [comment]
No we didn't I don't know what made the bug happen, I couldn't recreate it but when I deleted the mission off of sever and put a new one on it fixed the map bug.

**Comment by Vdauphin** [comment]
hello, thanks for report. Strange, what you are discribing is not a bug but If you have destroy all hideouts, this is the final phase of the H&M. civilian give you now all city with enemies activity (red circle). So the mission looks more like a classic insurgency as you need to clear all city you didn't clear during the first phase! keep in minds you can still help local population (side mission etc) and search for amo cache. have fun !!
