### ISSUE TITLE
Add preprocessing to BIS arsenal 

### ISSUE THREAD

**Issue by Breech99** [Vdauphin/HeartsAndMinds#252]
Seems like in a lot of missions the arsenal box has to reload each time for every player. 

using preProcessFile for the arsenal box would help preload and save on fps and lag spikes that occur.

**Comment by Vdauphin** [comment]
Hello!

hum, I don't see what I could do ... It is normal that each player load the arsenal box. If you don't do it, you will have no access to the arsenal.

`preProcessFile` (https://community.bistudio.com/wiki/preprocessFile) is to 

> Reads and processes the content of the specified **file**.

BIS_fnc_arsenal is a function so it is already preprocessed.

Do you have a code suggestion ?

byebye

**Comment by Breech99** [comment]
My friend Midnight showed me an example he uses when the arsenal is called in a script. I'll ask him to elaborate. It's another preprocessfile called up in the initserver file. The load time is like 0.3 seconds.  How it's set up now causes the arsenal to be loaded every time from scratch and causes the server to dip into the teens, sometime's crash clients.   Sample:

  _HPTH = preProcessFile "aso.sqf";_HPF = preProcessFile "as.sqf";

**Comment by Vdauphin** [comment]
`preProcessFile` speed up a lot the time of execution of function. It is what is used in H&M in https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/compile.sqf

For BIS_fnc_arsenal is already compile by Arma 3.
 I think you are talking about this : `["Preload"] call BIS_fnc_arsenal; ` (https://community.bistudio.com/wiki/BIS_fnc_arsenal)

> "Preload" - Preload item configs for Arsenal (without preloading, configs are parsed the first time Arsenal is opened)

**Comment by MidnightGH** [comment]
Hey there Vdauphin, I tried using your `["Preload"] call BIS_fnc_arsenlal`
Method, seems like this would just preload the listings for the arsenal.
Not the execution of the arsenal.
So, what the preProcessFile would do for the arsenal would in a sense remember the same execution for round two and save the extra exeuction.

**Comment by Vdauphin** [comment]
Hello!
I am not really sure to understand you guys x)
What do you want to preProcessFile guys ? (I expect a argumentation with code )

**Comment by Breech99** [comment]
I think I was using an old mission version where the arsenal was being loaded in from init_server and now it's moved to it's new location in  core/fnc/int/add_actions.sqf where the updated versions where it's now loading in a lot faster and probably being preprocessed.

**Comment by Vdauphin** [comment]
May be ... everything is here : https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/init_player.sqf#L37

`['Open',true] spawn BIS_fnc_arsenal;` the BIS fonction are already preprocessed ...
