### ISSUE TITLE
Wreck Respawn: Vehicles respawn half way in ground

### ISSUE THREAD

**Issue by Breech99** [Vdauphin/HeartsAndMinds#258]
Wrecks that are being fixed at the repair point are respawning half way under ground. I think it's due to the game respawning it where it last was storing the last elevation position with wheels destroyed on both aircraft and wheeled vehicles.  Did you or I change some x,y,z positining in the "repair wreck" spawn settings?  

It was a repeatable event but I didn't notice it happening in previous versions

**Comment by Vdauphin** [comment]
Hello,
I never tuch this. You can see it here : https://github.com/Vdauphin/HeartsAndMinds/blame/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf

**Comment by Vdauphin** [comment]
here is an exemple of the bug you are discribing:
![107410_20161203195314_1](https://cloud.githubusercontent.com/assets/14364400/20861508/3560f41e-b992-11e6-8b9a-60ba01755689.png)
