### ISSUE TITLE
BIS_fnc_MP should  it be remoteExec or remoteExecCall instead?

### ISSUE THREAD

**Issue by Breech99** [Vdauphin/HeartsAndMinds#261]
I see in some of the code the use of BIS_fnc_MP but a lot of people tell me to be using the more efficient remoteExec in place of it that replaced awhile back but was left in for backward compatibility. 

For example in hd_cache line 37--- [[0],"btc_fnc_show_hint"] spawn BIS_fnc_MP;

This function is now provided for backward compatibility only. Please use the engine based commands remoteExec or remoteExecCall instead.

From version 1.50 the function bis_fnc_mp will use the engine based remote execution.

The syntax and functionality of bis_fnc_mp will remain same to retain the backward compatibility.
To prevent abusing of the remoteExec and remoteExecCall commands the bis_fnc_mp will use, the content authors will be able to define the operation modes as well as white-lists for commands/functions for clients and server separately.

Notes from biki but is it good or bad to leave in BIS_fnc_MP?  Would it improve code if using remoteExec instead or by using remoteExec too often cause issues?

**Comment by Vdauphin** [comment]
Hello,
BI say it is better but in fact I never see issue link to this. I only use `remoteExec` for new code and leave `BIS_fnc_MP` because I have no time to replace all of them. 
In the past I choosed to do that instaed https://github.com/Vdauphin/HeartsAndMinds/pull/90  https://github.com/Vdauphin/HeartsAndMinds/pull/101  https://github.com/Vdauphin/HeartsAndMinds/pull/102 and use more `pushback` also https://github.com/Vdauphin/HeartsAndMinds/pull/211
I think the https://github.com/Vdauphin/HeartsAndMinds/issues/235 PFH of CBA will help more than this change but I don't really know in fact ^^

You are free to create a pull request for that ;) (If you do it please use the https://github.com/Vdauphin/HeartsAndMinds/tree/master_daily see [this](https://github.com/Vdauphin/HeartsAndMinds/wiki/7:-For-developer-and-tester) for explanation)

**Comment by Breech99** [comment]
I think code to change to [] remoteExec["btc_fnc_showhint",0]

Executing commands/functions via remoteExec is more faster than using BIS_fnc_MP. Tested with BIS_fnc_codePerformance in ArmA 3 1.52.
['"string" remoteExec ["hint",player];',[],100] call BIS_fnc_codePerformance; //Result ~0.1ms
['["string","hint",player ] call BIS_fnc_MP;',[],100] call BIS_fnc_codePerformance; //Result ~0.6ms

good to squeeze out every bit we can. Doesn't show much difference in small stuff, but on larger scripts, it looks apparent it does make a difference in load time.

**Comment by Breech99** [comment]
Also I found with core/init_player.sqf Line 25 should possibly be converted over to 

["5","nil","player"] remoteExec ["bis_fnc_int_ask_var",0];   <---new way

[[5,nil,player],"btc_fnc_int_ask_var",false] spawn BIS_fnc_MP; <----old alpha method

**Comment by Vdauphin** [comment]
> `["5","nil","player"] remoteExec ["bis_fnc_int_ask_var",0];` <---new way

Is it not : `["5","nil","player"] remoteExec ["bis_fnc_int_ask_var",2];` ?
This need to be execute server side, not on client.

Check the old syntax: `[params, functionName, target, isPersistent, isCall] call BIS_fnc_MP;  `
```
[
 [5,nil,player],    ---> params
 "btc_fnc_int_ask_var",  --->  functionName
 false                 ---> target : Boolean - false to execute it on server only
] spawn BIS_fnc_MP; 
```

**Comment by Breech99** [comment]
the 2 targets each client. Comparatively the 0 only targets first connected client.

**Comment by Vdauphin** [comment]
nop :) 

> When 2, it will be executed only by server.

 https://community.bistudio.com/wiki/remoteExec

**Comment by Breech99** [comment]
ah I see now  

Number - the function will be executed only on client with the given owner ID. When 0, the function will be executed on each client including the one where remoteExec was called from. When 2, it will be executed only by server. When negative, it will be executed everywhere except for machines with the given client ID. Use -2 to target everyone except the server.

yeah so 2 is correct  sorry I was getting confused trying to understand the format

**Comment by Vdauphin** [comment]
yea me too. This syntax is sooo bad!
