### ISSUE TITLE
Check For Intel bugged for Enemies who were run over

### ISSUE THREAD

**Issue by MidnightGH** [Vdauphin/HeartsAndMinds#272]
For each enemy you run over, you are not able to check for intel.
The action appears, however the checking isn't performed when you got to select.
Only have seen this happen with enemies I have run over with cars.

**Comment by Vdauphin** [comment]
Hello!

I run over a couple of man (pretty funny :) ) but I can't reproduce the bug. The interaction is here, the ProgressBar also and give me intel when I am lucky ... 

Can you send me rpt from server and client ?

**Comment by MidnightGH** [comment]
Lol.
Here is the RPT file: http://pastebin.com/yRrbciP3
unfortunately I was not able to produce a server rpt or log file.

**Comment by Vdauphin** [comment]
the first 14 lignes are missing ... please send me ALL rtp lines.

**Comment by MidnightGH** [comment]
I can assure you, the paste bin I had provided above is the full rpt from that client session.

**Comment by Vdauphin** [comment]
x) strange, I expected this also : 
```
=====================================================================
== C:\Program Files (x86)\Steam\steamapps\common\Arma 3\arma3.exe
== "C:\Program Files (x86)\Steam\steamapps\common\Arma 3\arma3.exe" -skipIntro -noSplash -showScriptErrors "-mod=C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@ace3;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@cba_a3;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\@rhs_usf3"

Original output filename: Arma3Retail_DX11
Exe timestamp: 2016/12/07 10:50:01
Current time:  2017/01/02 12:08:41

Type: Public
Build: Stable
Version: 1.66.139586

Allocator: C:\Program Files (x86)\Steam\steamapps\common\Arma 3\dll\tbb4malloc_bi.dll
=====================================================================
```
never mind, I can't reproduce and don't see anything strange in your rtp. 

Sorry but from my point of view everything is working on the last H&M https://github.com/Vdauphin/HeartsAndMinds/releases/tag/1.15.3.

**Comment by MidnightGH** [comment]
Understood, I just had a lot of bodies to loot for intel. But I couldn't check any of them.
Doesn't make for the best situation.

**Comment by Vdauphin** [comment]
Did you use zeu ?
