### ISSUE TITLE
Typo spelling error on final task Seize the last enemies positions

### ISSUE THREAD

**Issue by Breech99** [Vdauphin/HeartsAndMinds#274]
It shows for final task after destroying all hideouts "Size the last enemies positions"

Corrected grammar would be "Seize the last of the enemies positions"
(Sorry I cannot remember location of task file or line)

**Comment by Vdauphin** [comment]
https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/=BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/set_done.sqf
