### ISSUE TITLE
View Restriction

### ISSUE THREAD

**Issue by WSIContractor** [Vdauphin/HeartsAndMinds#301]
It seems that 1.16.1 doesn't have the 3rd person view restriction? I seem to recall in 1.15 it did?
Is that by design or an omission?

**Comment by Vdauphin** [comment]
H&M never restrictic the 3rd person view. It is your server config or mission modification which add restriction.
Bye!

**Comment by WSIContractor** [comment]
My apologies, Yes, one of the admins had ACEX enabled.
