### ISSUE TITLE
Add: Face of War (FOW)

### ISSUE THREAD

**Issue by Vdauphin** [Vdauphin/HeartsAndMinds#302]
@Giallustio works on [Face of War](https://forums.bistudio.com/topic/198194-faces-of-war-ww2/) (FOW).
There are a lot of request for this mission ported into the WW2 settings.

- [x] Add enemy faction FOW 
- [x] Add civilian FOW, where are they ? go IFA
- [ ] Use IED which fit the ww2 or let player disable it
- [ ] add\remove side missions that fits more with the ww2 setting or give player the choose ?

**Comment by Giallustio** [comment]
If you use http://steamcommunity.com/sharedfiles/filedetails/?id=660460283 you'll have a lot of assets!

**Comment by Vdauphin** [comment]
I don't think I will do more WW2 port. I prefered to make a semi automatic mod support to allow player an easier mod integration. Actually, H&M 1.17 will support 136 factions. They can be selected inside the mission parameter.

For WW2, I leave to player the choice for IED and side mission witch are easy to tweak directly inside : https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L216
and : https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L136
