### ISSUE TITLE
FRIES equipped helicopters cause logistics pad to detect that it is not a wreck.

### ISSUE THREAD

**Issue by Doctor-Butts** [Vdauphin/HeartsAndMinds#305]
Helicopters that have an ACE_friesAnchorBar attached to them cause the repair_wreck.sqf to not work.

examples of vehicles that do have friesAnchorBar:
RHS_UH60M
RHS_UH60M_d
Arma 3 Ghosthawks.

(I believe that your script call to add fastroping attaches the AnchorBar to the helis that are capable, and the above are just the ones I've confirmed I get the bug with)

The script finds the AnchorBar first, before the helicopter wreck, and then detects that since the anchorbar isn't destroyed, exits the script with 'it is not a wreck'.

In our customized mission, we've created an inelegant solution to the problem by modifying repair_wreck.sqf to first look for, and then to delete any anchorbars, and then to repair the wreck:

```
private ["_object","_array","_anchorb"]; 
 
_object = btc_create_object_point;
_anchorb = nearestObjects [position _object, ["LandVehicle","Air"], 10]; 

 
if (count _anchorb == 0) exitWith {hint "No wreck";}; 
 
{
  if (typeOf _x == "ACE_friesAnchorBar") then 
  { 
     hint "rogue anchorbar spotted";
     deleteVehicle _x; 
  };
} forEach _anchorb;

sleep 2;

_array = nearestObjects [position _object, ["LandVehicle","Air"], 10]; 

if (damage (_array select 0) != 1) exitWith {hint "It is not a wreck!"}; 
 
[[(_array select 0)],"btc_fnc_log_server_repair_wreck",false] spawn BIS_fnc_MP;
```

Known issues with our script above is that if the vehicle is not a wreck, and had an anchorbar added, it will delete the anchorbar.

**Comment by Vdauphin** [comment]
Thank you again for this report very clear and documented. I hope you will enjoy the "elegant" fix ;)
