### ISSUE TITLE
New Possible Side mission ideas for 2017

### ISSUE THREAD

**Issue by Breech99** [Vdauphin/HeartsAndMinds#320]
**Prison` camp rescue -  kill enemy at prison camp and bring back x number of hostages to a hidden marker at base. hostages join team so you can control and move to base, unload and move to flag or whatever place at base.  Possible code example:**

`private` ["_prisspawncnt","_wincnt","_location","_poss","_newgroup","_unit_array","_gdog", "_roadrecovery"];
d_x_sm_pos = "d_sm_21" call d_fnc_smmapos; //   Prison camp
d_x_sm_type = "rescue"; // "convoy"
_wincnt = 10; //minimum number of pris at base for win
_prisspawncnt = 13; //number of prisoners to spawn
_roadrecovery = true;
if (!isDedicated && {!d_IS_HC_CLIENT}) then {
	d_cur_sm_txt = [(d_x_sm_pos select 0), d_x_sm_type, _dispname, _wincnt] call d_fnc_t_nearsm;
	publicVariableServer "d_cur_sm_txt";
	diag_log format ["***Side mission starts # %1, %2", d_cur_sm_idx, d_cur_sm_txt ];
	d_current_mission_resolved_text = localize "STR_Sideprisoners_End";
	};
if (call d_fnc_checkSHC) then {
	waitUntil {sleep 1; ((!isNil "d_cur_sm_txt") and (d_cur_sm_idx > -1))};
	diag_log format ["***Side mission starts # %1, %2", d_cur_sm_idx, d_cur_sm_txt ];
    _poss = d_x_sm_pos select 0;
	_newgroup = [d_own_side] call d_fnc_creategroup;
	_unit_array = ["civilian", "CIV", _prisspawncnt] call d_fnc_getunitlist;
	[_poss, _unit_array select 0, _newgroup] call d_fnc_makemgroup;
	_leader = leader _newgroup;
	_leader setSkill 1;
	_unit_array = nil;
	sleep 2.0112;
	_newgroup allowFleeing 0;
	[_newgroup, 1] call d_fnc_setGState;
	_units = units _newgroup;
	{
		removeAllWeapons _x;
		_x setCaptive true;
		_x disableAI "MOVE";
		_x switchMove "AmovPercMstpSsurWnonDnon";
	} forEach _units;
	sleep 2.333;
	["specops", 2, "basic", 2, _poss,100,true] spawn d_fnc_CreateInf;
	_gdog = [];
	[_poss, _newgroup, _gdog,_wincnt,_roadrecovery] spawn d_fnc_sideprisoners;
};

**Comment by Breech99** [comment]
Possible other ideas:

Destroy Hanger Research Facility

Destroy Radio Tower on top of a mountain

Destroy a Cargo truck or train car with chemical weapons. (using CUP_Terrain_Core 1.3.0   train car objects)

Along same lines Destroy a Cargo vessel ship with chemical weapons. (Trawler using CUP_Terrain_Core 1.3.0 Trawler object)

Find and eliminate a drug cartel leader

**Comment by Vdauphin** [comment]
https://github.com/Vdauphin/HeartsAndMinds/issues/738
