### ISSUE TITLE
Confirm param.hpp "Intel from dead bodies chance:" ?

### ISSUE THREAD

**Issue by Doctor-Butts** [Vdauphin/HeartsAndMinds#324]
values[]={0,10,20,30,40,50,60,70,80,90,100};
		texts[]={"100 %","90 %","80 %","70 %","60 %","50 %","40 %","30 %","20 %","10 %","0 %"};
		default = 70;

I haven't been able to find exactly where in the scripts the info chance is selected, but it looks like the numbers are reversed. For instance, if default is 70, 30% shows as the text. Does this mean that the values are a percentage of how much of a chance it _won't_ show up on a dead body?

**Comment by Vdauphin** [comment]
Hello,
`default = 70;` mean you have 30% of chance to have intel for a dead body.
Best regards.
