### ISSUE TITLE
Bug: Side missions not showing task locations

### ISSUE THREAD

**Issue by Breech99** [Vdauphin/HeartsAndMinds#335]
Side missions are broken after new update. No task message given and no task location on map is broadcasted. #333 #332

**Comment by Breech99** [comment]
I should say rather that a black flag is shown but no task message to let the players know a description of the mission with task message and assignable bohemia task icon.

**Comment by Vdauphin** [comment]
can you post in the corresponding branch the bug you see ?

**Comment by Vdauphin** [comment]
Report bug in the corresponding branch.
