### ISSUE TITLE
Suicide Car bombs

### ISSUE THREAD

**Issue by Breech99** [Vdauphin/HeartsAndMinds#347]
Idea: How about rez suicide bomber civie and then rez a car and then have him get in and drive at blufor. I do see complications that others have  tried in the past with civilian driving at blufor. I think car bombs would be another crazy addition to this mission. Samples of real life situations with bombers seen on funker video  https://www.funker530.com/insane-svbied-montage-mosul/  very sad and a good reference video.

**Comment by Breech99** [comment]
Possible implementation of vehicle bomber:  Take the suicider_create clone that script into something like suicidercar_create
add in parts from traffic_create to add civil placed in car  (selectRandom btc_civ_type_units) createUnit [_Spos, _group, "this moveinDriver _veh; this assignAsDriver _veh;"]; and of course instead of attachTo don't do the DemoCharge_Remote_Ammo. try a much larger Remote explosive if possible. Should be a fun idea. Some friends of mine have tried with civilian and it seems to not work as well as previously thought. Just tossing ideas into think tank to see the feasibility of the idea.

**Comment by Breech99** [comment]
I was thinking of incorporating something like this with the gbu. but maybe attach it to the car or just have it delete and create bomb effect. I like it attached to the car and then set off.
 _men = crew _car;      
 {deleteVehicle _x} foreach _men;
 _null = "Bo_GBU12_LGB" createVehicle getPos _car; //or should it be createVehicle (position _this); ??
 deleteVehicle _car;

or have it _null attachTo ???

**Comment by Breech99** [comment]
Someone a few years back came up with something similar 
init would be = 
null [CAR, CHANCE, SUICIDE YELL, DELAY, SIZE, ATTACH TO VEHICLE, DISTANCE FROM TARGET, SIDE] execVM "suicidebomber.sqf";

null = [BOMBER, 10, "Die!", 1, "MEDIUM", 1, 5, "WEST"] execVM "suicidecarbomb.sqf";

then for possible script:

`_car = _this select 0;
_possibility = _this select 1;
_shoutout = _this select 2;
_delay = _this select 3;
_size = _this select 4;
_wait = _this select 5;
_distance = _this select 6;
_enemyside = _this select 7;
 
if(_enemyside == "WEST") then
{
        while {_wait == 1} do
        {
                if(alive _car) then
                {
                        sleep 0.75;
                        if((driver _car isKindOf "Man") && (side driver _car != west)) then
                        {
                                _types = _car nearObjects ["All", _distance];
                                {if(side _x == west) then {_wait = 0}} foreach _types;
                        };
                }
                else
                {
                        _wait = 0;
                        _possibility = 0;
                };
        };
};
 
if(_enemyside == "EAST") then
{
        while {_wait == 1} do
        {
                if(alive _car) then
                {
                        sleep 0.75;
                        if((driver _car isKindOf "Man") && (side driver _car != east)) then
                        {
                                _types = _car nearObjects ["All", _distance];
                                {if(side _x == east) then {_wait = 0}} foreach _types;
                        };
                }
                else
                {
                        _wait = 0;
                        _possibility = 0;
                };
        };
};
 
if (_possibility > 0) then
{
        _achance = random 10;
        _rchance = round _achance;
        if(_rchance <= _possibility) then
        {
                hint _shoutout;
                sleep _delay;
                if (_size == "SMALL") then
                {
                        _men = crew _car;      
                        {deleteVehicle _x} foreach _men;
                        _null = "R_80mm_HE" createVehicle getPos _car;
                        _updatepos = [(getPos _car) select 0, ((getPos _car) select 1) + 1];
                        sleep 0.25;
                        _null = "R_80mm_HE" createVehicle _updatepos;          
                        _car setDammage 1;
                };
                if (_size == "MEDIUM") then
                {
                        _men = crew _car;      
                        {deleteVehicle _x} foreach _men;
                        _null = "Sh_122_HE" createVehicle getPos _car;
                        _car setDammage 1;
                };
                if (_size == "LARGE") then
                {
                        _men = crew _car;      
                        {deleteVehicle _x} foreach _men;
                        _null = "Bo_GBU12_LGB" createVehicle getPos _car;
                        deleteVehicle _car;
                };
        };
};`
or the possibility for using the old stalking command to search for Bluefor targets in a radius scan Not sure if this is a performance hit, just trying out ideas  How about BIS_fnc_stalk ????  an old function but should work for finding Blufor.

**Comment by Breech99** [comment]
_stalking = [BIS_grpStalkers,BIS_grpPlayer,5,0,{dayTime > 20},[3600,600,0]] spawn BIS_fnc_stalk;   Let me know if you guys come up with some better idea. Something tracks distance to target like this example and hunts. I'm sure it's been done for dayz and the like to have AI track and find Players easy.

**Comment by Breech99** [comment]
Alias came up with an interesting way to have the AI hunt the blufor players. I think it's a pretty common concept, but one worth trying in his kamikaze script.  I tried it by rezzing a vehicle with a person in it, Very interesting. http://www.armaholic.com/page.php?id=33096

**Comment by Doctor-Butts** [comment]
Hi,

I modified a car bomb script that I believe incorporated some of the things the original H&M mission did with IED's with putting an actual 'bomb' in the car.

The objects are of course specific to that mission but this is just a way it can be implemented:

carbomb.sqf:

`_bombcar = _this;

_cbomb = "Land_MetalBarrel_F" createVehicle [0, 0, 0];
_cbomb attachTo [_bombcar, [0, -1, -0.2] ]; 
_cbomb setVectorDirAndUp [ [1, 90, 0], [0, 1, 0] ];
waitUntil { sleep 0.2; alive (driver _bombcar) && (foodVeh distance _cbomb) < 20; };

_cbomb execVM "ied\boomcar.sqf";`

boomcar.sqf:

`_pos = getPos _this;
"Bo_GBU12_LGB_MI10" createVehicle [_pos select 0, _pos select 1, -0.1];
playSound3d["A3\Missions_F_EPA\data\sounds\combat_deafness.wss", objNull, false, _pos, 1, 1];`

**Comment by Vdauphin** [comment]
Hello,
Thank you for this code. Looks clear how you see this feature. But, I have a problem with the initial concept.
Actually, civilian bomber give you different step before explosion : 
- civilian don't follow  "civilian orders"
- civilian run into player
- after, charge appearing
- then a big screaming
- and If player didn't kill the civilian, an explosion occur.

Each step give to player a good understanding what is going on.

Infortunatly, by nature, a car bomb attacking can't really have a slow step like civilian bombers have. Player will have no way to see the difference between civilian bomber and civilian car, resulting in just more war crime. Also, if the bomb is clearly apparent, players will not have time or enough power to stop the attack.
I will accept this type of feature with an option in mission parameter to disable it.

An other way to take adventage of civilian car could be to make civilian try to drive over player. This  making the effective impact on player lower due to no big explosion often used in H&M (IED and civilian bomber) but still terrorize the player.

- when a walking player is around (20m)
- [`doMove`](https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf#L45-L48) car civilian into  player
- give a [weapons to civilian](https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/civ/add_weapons.sqf) to allow him to defend against you if the car crash.

Best regards

**Comment by Doctor-Butts** [comment]
Yea, I was hoping that attaching a barrel object to a car would make it more obvious to player that it is a bomb car. The script could be modified where the explosion only goes off if:

1. Car is between 0 and X meters from player for X amount of time.
AND
2. Car bomb driver is still alive.

The car can be limited in speed, but in playing a lot of the mission so far: the AI are notoriously bad at driving.

An alternative could be the car bomb driver only targets blufor vehicles, or car bomb drivers only target the base and/or FOBs.

**Comment by Vdauphin** [comment]
> An alternative could be the car bomb driver only targets blufor vehicles, or car bomb drivers only target the base and/or FOBs.

I like  this alternative where player will need to protect their FOB or base.

**Comment by Vdauphin** [comment]
https://github.com/Vdauphin/HeartsAndMinds/issues/738
