### ISSUE TITLE
False medical reads on ace patients

### ISSUE THREAD

**Issue by MidnightGH** [Vdauphin/HeartsAndMinds#352]
I'm not quite sure as to if this is a ace error or mission error.
The problem is that sometimes when checking pulse and bp it'll read perfectly healthy but the patient is definitely dead. But the player controlling the unit is still able to see everything happening. But they are in a infinite loop of unconsciousness.

**Comment by Vdauphin** [comment]
Hello!
Don't know, Ask to the ACE team :)
See you !
