### ISSUE TITLE
stop civilians from running crazy

### ISSUE THREAD

**Issue by awesomestmaximus** [Vdauphin/HeartsAndMinds#356]
First of all, Great $&#^%*& mission dude, me and some buddies of mine been playing it for a long time

one irritating thing about civilians is the fact that they keep running like crazy and it becomes difficult to issue orders to them

is it possible to have the civ stand still for a few seconds while a player is aimed at them to give him a chance to select the order he wants to give the civ?

**Comment by Vdauphin** [comment]
Hello, thank you

Lol. Just interact on you and select civil order and ask them to STOP .

Have a good day

**Comment by Vdauphin** [comment]
This mecanic is also clearly explained in the in game documentation here: https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/doc.sqf#L121

**Comment by awesomestmaximus** [comment]
thanks for the reply @Vdauphin, I'll read more next time before asking stupid questions :-P

**Comment by Vdauphin** [comment]
You welcome :)
