### ISSUE TITLE
Portable Medical facility

### ISSUE THREAD

**Issue by Breech99** [Vdauphin/HeartsAndMinds#357]
An idea of possible deployable Medical facility similar to the FOB blue box, have it a red or orange box (Land_Cargo20_orange_F), then it deploys a level 2 medical facility (Land_Medevac_house_V1_F) which would be set to Ace is medical facility and have module ace map settings to vehicles and facility treatment by medic/doc surgical kit sew use and pak. Wish they would get that ACE medical rewrite fixed soon.  Just throwing in another idea.

Setting a structure to ace medical facility using 

 _facility setVariable [ace_medical_isMedicalFacility, true];

**Comment by Vdauphin** [comment]
Hello, it is already implemented by the medical truck!
Best regards.
