### ISSUE TITLE
Destroyed vehicle markers not appearing on dedicated server after a server restart

### ISSUE THREAD

**Issue by eric963** [Vdauphin/HeartsAndMinds#372]
Using default Altis mission.

Take a vehicle a couple hundred meters from the base and destroy it and a vehicle marker appears on the map where the vehicle was destroyed.

Do a save and then restart the dedicated server.  Rejoin the server and when the base overview begins to display you can hear the vehicle explode and when you finally load into the game all the way thedestroyed vehicle is in in the proper place (destroyed) but when you look at the map there  is no marker for it.

It's like its being destroyed too soon for whatever script tracked destroyed vehicles.

**Comment by Vdauphin** [comment]
Hello, 
Thank you for this clear feedback. A fix will come soon ;)
Have fun !
