### ISSUE TITLE
Side Mission Idea : Save the spilled cargo

### ISSUE THREAD

**Issue by Breech99** [Vdauphin/HeartsAndMinds#391]
Save the spilled cargo from a passing Cargo container ship!
 
Interesting idea for a side mission I based off from take on helicopters : Mission starts leaving off where a tanker passing through a channel way, has spilled it's cargo.  Your job is to lift out the remaining floating containers to clear the path for shipping lanes and rescue the cargo  

[http://takeonthegame.com/full/wp-content/uploads/2012/03/LUKAS_1280x800_2.jpg](url)

**Comment by Breech99** [comment]
Maybe looping the above sea level when you rez boxes in water via a script. Then in script loop the ASL

`
"_i" from 0 to 1 step 0 do {_box setPosASL[(getPosASL _box select 0),(getPosASL _box select 1),0];};`

**Comment by Vdauphin** [comment]
https://github.com/Vdauphin/HeartsAndMinds/issues/738
