### ISSUE TITLE
Please add Fuel Truck fuel cargo refill option (if not already there)

### ISSUE THREAD

**Issue by Doctor-Butts** [Vdauphin/HeartsAndMinds#392]
I have added an object that has some addactions attached to it, one of them being an ace command to refill the amount of fuel in the tank of a fuel truck:

if (typeOf player == "B_officer_F") then {
hint "Fuel cargo being refilled..";
sleep 5;
[btc_veh_12, 10000] call ace_refuel_fnc_setFuel;
hint "Fuel Truck Fuel reset";} else { hint "You're not the officer, you cannot access this command"};

**Comment by Vdauphin** [comment]
Hello,
This is a ACE3 feature. See this https://youtu.be/-OQbjZhmxOQ?list=PLy5Q_pNVt87ik70ByyuMhtYkre2EaBWvt&t=105
You can also rearm has explained here: https://github.com/Vdauphin/HeartsAndMinds/wiki/Guide-to-rearming
See you!
