### ISSUE TITLE
Please add ability to move/delete/mark checked IED _wrecks

### ISSUE THREAD

**Issue by Doctor-Butts** [Vdauphin/HeartsAndMinds#393]
I was hoping that there was a way to delete checked wrecks or to mark them in some persistent manner that every one knows it's been checked.

**Comment by Vdauphin** [comment]
Hello,
Now players markers (not lines) are saved if there are on global channel (https://github.com/Vdauphin/HeartsAndMinds/pull/351). Very usefull for this !
https://github.com/Vdauphin/HeartsAndMinds/wiki/InGame-documentation#headless--data-base
See you soon!
