### ISSUE TITLE
 Problems Found in Version 1.17.X

### ISSUE THREAD

**Issue by danielmjmarques** [Vdauphin/HeartsAndMinds#412]
Problems
- Documentation is no longer appearing when it is on dedicated servers.
- The interpreter option is not working
- The creation of AIs is making them very close to each other and not taking advantage of houses and buildings with intelligence, they look like a lot of stupid soldiers

Congratulations
- The air protection system in the missions was very good
- The cycle of secondary missions very helps the life of the administrator, very good

* Sorry for my bad English

**Comment by Vdauphin** [comment]
Hello,
Thanks

Where did you download the mission ? And what does the .X mean ?
Could you also upload the RTP server and client side ?

See you soon!

**Comment by danielmjmarques** [comment]
Hello Vdauphin
Thanks for the quick response.

The X in this case means that I tested with 1.17.1 and 1.17.2 and that until the last version of 1.16 it was all working.

I always down the missions of the site of the Developer, in this case I downloaded it here, already use its mission some time and we like very much to throw it in our server. I will send the RPTs for you to analyze.

**Comment by Vdauphin** [comment]
>  The creation of AIs is making them very close to each other and not taking advantage of houses and buildings with intelligence, they look like a lot of stupid soldiers

The creation of AIs is close but them each team  get a random waypoint. So they start to spread under small team which is intended. You can increase the AI spawn in houses or building by using this : https://forums.bistudio.com/forums/topic/165948-mp-btc-hearts-and-minds/?page=18&tab=comments#comment-3098199

Also this fearture will be improve by this : https://github.com/Vdauphin/HeartsAndMinds/pull/383

**Comment by 1kuemmel1** [comment]
Hi,
Sorry but i can't reproduce the bugs (tested with the current version - 1.17.2).

[x] documentation is available
[x] interpreter interactions (and options) are available and working for me
[x] AI creation - see below ⬆️

greetings

> Sorry for my bad English

me too 😆

**Comment by danielmjmarques** [comment]
You Testing in Dedicate Server?

**Comment by 1kuemmel1** [comment]
> You Testing in Dedicate Server?

Yes I did.  Loaded mods: CBA, ACE³, RHSUSAF

**Comment by danielmjmarques** [comment]
It is true! This working I must have changed some script that caused the documentation and the interactions to stop working, I will analyze again. Thanks a lot for the help. And sorry for any of the delays I've caused.

**Comment by Vdauphin** [comment]
No problem! Have fun now!

**Comment by danielmjmarques** [comment]
I believe I have found the problem, I am using your mission on the map of TAKISTAN and to make it more realistic I put the civilian unit being "2 -btc_militia_mod Giallustio: Afghan Civilians (Side: CIV)". When I use the vanilla pattern it works, when I use Afghan it does not work.

**Comment by Vdauphin** [comment]
> when I use Afghan it does not work.

Do you load the corresponding mod (ie: https://forums.bistudio.com/topic/188272-btc-militia-for-a3/#entry2983674)

**Comment by danielmjmarques** [comment]
Yes, I tested with MOD "0 - EricJ: Afghan Civilians (Side: CIV)" and the same thing happens, should it be something from ACE3 with these mods, or am I wrong?

**Comment by Vdauphin** [comment]
Strange. I think, I don't have all the information. 
As always a RTP will give to me all of them ;)
