### ISSUE TITLE
Feature Request: Mission Fail Condition

### ISSUE THREAD

**Issue by Doctor-Butts** [Vdauphin/HeartsAndMinds#416]
If various malus effects aren't enough for players (suicide bombs, militia in towns) to focus on getting good rep, how about a mission fail condition if the rep gets too low?

A mission parameter could be added, something like "Fail if Rep too low?" with options like "OFF","Rep value X","Rep value Y","Rep Value z".

I've implemented the fail condition on my fork as two triggers and a code line change to the ask_reputation.sqf so that the interpreter gets a numeric value to let them know the exact rep number: so they know if they're really close to the threshold.

Trigger 1 goes off if rep has reached -500, this warns the player via hint that if Rep does not improve within 20 minutes, mission will fail.

Trigger 2 will wait for 20 minutes, and if rep is still worse than -500, the mission will fail.

**Comment by Vdauphin** [comment]
Hello,


> If various malus effects aren't enough for players (suicide bombs, militia in towns) to focus on getting good rep, how about a mission fail condition if the rep gets too low?
> 
> A mission parameter could be added, something like "Fail if Rep too low?" with options like "OFF","Rep value X","Rep value Y","Rep Value z".

Good idea! why not!

> I've implemented the fail condition on my fork as two triggers and a code line change to the ask_reputation.sqf so that the interpreter gets a numeric value to let them know the exact rep number: so they know if they're really close to the threshold.

I see, the best way to implet I think also. But the numeric value is not really realistic. I think keep the normal message of cilivian but add lower message like  : 
- above 0:  "You are so low in reputation that you will fail your intervention on this island"
- above -100: "You never be so close to fail your intervention"
- above - 200 : "You will fail soon, just saying ..."
- above -500: "You fail! At least in 20 minutes."

Or stuff like that ... Sound a little more "educative" for player I think.

See you soon!

**Comment by Vdauphin** [comment]
https://github.com/Vdauphin/HeartsAndMinds/issues/738
