### ISSUE TITLE
Add NonSteerable_Parachute_F to AI passengers of RHS helicopters

### ISSUE THREAD

**Issue by Breech99** [Vdauphin/HeartsAndMinds#426]
Add in script for rhs helicopters. The passengers have gear but no chute. Should be easy enough add a chute via script additional attachment to gear and have attach to passengers when AI eject.  Helicopters right now end up getting spooked and then quickly dump passengers out to eject but have no chutes.

**Comment by Breech99** [comment]
My friend Midnight had some possible solutions to add in where it adds to classname

`/* Author: Midnight (For use in Hearts and Minds by Breech99)

   Description: Checks for damage in loop and exits if damage and ejects crew
   
   Parmater(s):
   0 - OBJECT: Air vehicle to eject crew from
   1 - NUMBER: damage threshold
   
   Returns:
   Nothing
*/
0 = [(_this select 0),(_this select 1)] spawn
{
    params[["_veh",objNull,[objNull]],["_n",0,[0]]];
    if(_veh isKindOf "Air") then
    {
        while {true} do
        {
            if(damage _veh > _n) exitWith
            {
                {
                    removeBackpack _x;
                    _x addBackpack "B_parachute";
                    _x action["Eject",vehicle _x];
                    sleep 0.5;
                    _x action["OpenParachute",_x];
                    true
                } count (crew _veh);
            };
        };
    };
};`

**Comment by Vdauphin** [comment]
Out of the scope of the H&M
