### ISSUE TITLE
Feature request : FOB with zeus function

### ISSUE THREAD

**Issue by Breech99** [Vdauphin/HeartsAndMinds#437]
Idea is to add a limited area after deploying FOB to assign Curator and have a limited area radius for zeus limited points allowed to place down small bunkers, arsenal, hesco barriers, heli pad etc. would have to add BIS_fnc_setCuratorCamera, 

			[] remoteExec ["btc_fnc_resetCuratorBuildlist"];
			cur addCuratorEditingArea [1,(position fobveh),50];
			cur addCuratorCameraArea [1,(position fobveh),50];

then when removing fob

// Remove Editing Area and curator owner
		cur removeCuratorEditingArea 1;
		cur removeCuratorCameraArea  1;
		_cobj = curatorEditableObjects cur;

**Comment by Vdauphin** [comment]
Hello, thanks for this suggestion but the use of curator is not necessary thanks to the logistic point containing all those objects.  Also the next release 1.18 will include a feature to copy and past container with their cargo (https://github.com/Vdauphin/HeartsAndMinds/pull/386). So you will be allow to quickly generate objects and lift them to the wanted position (FOB, roadblocks, player structure).

**Comment by Breech99** [comment]
Sounds good. Yeah. my friends and I enjoy doing the fun manual moving. Other folks suggested it and thought it might be interesting but might conflict with other things going on. I only wish Bohemia would include lift containers into the heavy object category so the BIS lift would work instead of the scripted. Sometimes I slip and shut the engine  off when trying to hover and use the scripted lift method to hook medium and large containers.
