### ISSUE TITLE
Database Save/Load, intended functionality

### ISSUE THREAD

**Issue by storrgie** [Vdauphin/HeartsAndMinds#449]
Is not a bug report, more of a request for clarification... or point me to a place where I can rtfm.

As an officer I can see the "save database" option, however I'm unsure of how to trigger a loading of that database. If I close down the server (e.g. close the process), then relaunch the server, I will select the Hearts & Minds mission (e.g. Altis) and it appears to load a fresh start. At this time I assume I should be triggering a load of the database, but I'm unsure of how and couldn't locate it in the documentation.

I see the [pull request here](https://github.com/Vdauphin/HeartsAndMinds/pull/448) that seems to be adding functionality for items placed on the map? Does this mean that a zeus player could "expand the FOB" and those changes would persist in the database?

Thanks a ton for this mission, it's really an incredible one to play through with a unit!

**Comment by Vdauphin** [comment]
Hello,
This mission has a database system. Enemy units, towns, hideouts, cache, objects created by players or Zeus, vehicles, players markers (not lines) on global channel are saved. All admin can save mission progress at any time with his self interaction key. (Tiny doc ^^[/core/doc.sqf#L5](https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/doc.sqf#L5), the function actually saving : [/core/fnc/db/save.sqf](https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/db/save.sqf))

When saved, you can kill arma 3 process and update your mods, missions collection and restart your server. The mission will automatically search and load data previously saved. It is entirely transparent.

The data are saved in It is in your user profile file with extension : .vars.Arma3AlphaProfile
 https://forums.bistudio.com/topic/143834-varsarma3alphaprofile/

Do not hesitate if you have more question!
See you soon!

**Comment by storrgie** [comment]
@Vdauphin thanks a ton for the fast response. It appears that my server doens't seem to load up the database. How would you suggest I debug this? I could paste in the terminal output as the server starts here, however I want to make sure that's ok before I start making a mess of the ticket.

**Comment by Vdauphin** [comment]
> How would you suggest I debug this?

Check if the mission parameter : `Load the savegame (if available)` is ON ([/core/def/param.hpp#L21](https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/param.hpp#L21))

- Spawn an object from the logistic point
- Save the game
- Restart

If the object is not here : 
- delete the data base with the interaction and test again.

If nothing happening, check your server RTP, you should see errors and may be your arma 3 server don't have right to write the .vars.Arma3AlphaProfile file

Good luck!

**Comment by storrgie** [comment]
Thank you a ton, this got me sorted. For whatever reason when I first set up my arma server on Linux it didn't create the appropriate `.local` folder hierarchy that contains the profile folder where this stuff needs to be written. For those who might have a similar problem please look at [this](https://community.bistudio.com/wiki/server.armaprofile#Linux) and [this](https://forums.bistudio.com/forums/topic/185083-solved-linux-arma3profile-not-working/).
