### ISSUE TITLE
Opposing Force not Moving

### ISSUE THREAD

**Issue by storrgie** [Vdauphin/HeartsAndMinds#450]
Likely another similar educational issue like #449. I am seeing opfor spawn in clumps, but they never leave their clumps. They will turn to engage when fired upon, but they do not move... am I missing a mod?

All mods are pulled from the workshop as of today (stable releases). Mods used are listed [here](http://steamcommunity.com/sharedfiles/filedetails/?id=1216608332).

**Comment by Vdauphin** [comment]
Hello,

I never experiencing this issue :/ and I don't see in your mods list what could create this issue.
If you want to investigate you can turn on debug on your computer (or dedicate but you will be spoil by hideouts position etc) and you will see all AI. Basically they spawn and after a few seconds they randomly start to patrol or not ([/core/fnc/mil/create_group.sqf#L33-L54](https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf#L33-L54)). When there are not patroling they looks like this : https://user-images.githubusercontent.com/14364400/34038575-1f68e6ca-e18d-11e7-8108-d954835dac37.png

Have fun!

**Comment by storrgie** [comment]
Actually, via zeus I can see that they are spawning in clumps and they have no assigned way-points.

**Comment by Vdauphin** [comment]
> Actually, via zeus I can see that they are spawning in clumps and they have no assigned way-points.

Very weird, can you add the RTP log from the dedicate server ?

**Comment by storrgie** [comment]
So I played around a little more. Both Civilians and OPFOR are not moving, many will get waypoints. The ones that get waypoints will "wiggle" in place, but won't move. The only way I could get civilians to move was to take them prisoner then release them.

With OPFOR they stand in place and don't fire until fired upon. Then they turn and fire without moving. They stay in place and return fire until they exhaust ammunition. They don't throw smoke or do any other tactics.

If I drop in OPFOR via zeus, the new assets will run around and do the 'normal' stuff like toss smoke and engage. 

On linux I assume the RPT log is just the console log... right? If so, I'm not sure how many clues are in it... but check [this out](https://gist.githubusercontent.com/storrgie/b1711bc59cfbd0e434b3cec7148ac79d/raw/0a1be3111b7b87c3c8157413332829225cb4271f/gistfile1.txt).

**Comment by storrgie** [comment]
I tried both of the last two releases. In v1.17.5 I don't see _any_ OPFOR get waypoints while looking in zeus. In v1.17.4 I can see them getting waypoints, but they still exhibit the stand/wiggle behaviour. I'm pretty perplexed on this one.

I'd happily give you the server credentials to log in and see first hand.

**Comment by storrgie** [comment]
I reduced the modset to [this](http://steamcommunity.com/sharedfiles/filedetails/?id=1216608332) and completely re-installed the system. Still having all OPFOR just "wiggle" in place

**Comment by Vdauphin** [comment]
> I'd happily give you the server credentials to log in and see first hand.

I understand but sadly I will see the same thing that you are reporting. 

The only way to find a solution is to make the problem simpler :  delete the data base, use the pbo from the last release and load only mods require for the mission. Then check if the issue is still here.
If yes, I have no idea ... may be use the debug ON, take the RPT and check for errors.

**Comment by storrgie** [comment]
Are the minimum dependencies CBA/ACE/RHSUSAF?

**Comment by Vdauphin** [comment]
Yes!

**Comment by storrgie** [comment]
I'm actually not sure what cause this to be a problem. I did narrow down the modset, so I'll dump my deployment notes for other people to see. I'm dumping the arma install and mods to a JFS volume with the `-O` flag instead of doing the find/rename that people seem to be doing for the case sensitivity issues. Alternatively if you're deploying on a system with ZFS you can flag a filesystem to be case insensitive. I wish btrfs supported case insensitivity. So `/mnt/arma` is JFS and case insensitive.

```
steamcmd +login <username> +force_install_dir /mnt/arma/srv +app_update 233780 validate \
+workshop_download_item 107410 450814997 \
+workshop_download_item 107410 463939057 \
+workshop_download_item 107410 708250744 \
+workshop_download_item 107410 751965892 \
+workshop_download_item 107410 843577117 \
+workshop_download_item 107410 843425103 \
+workshop_download_item 107410 773125288 \
+workshop_download_item 107410 773131200 \
+workshop_download_item 107410 861133494 \
+workshop_download_item 107410 1180533757 \
+workshop_download_item 107410 945476727 \
+workshop_download_item 107410 723217262 \
+workshop_download_item 107410 498740884 \
+workshop_download_item 107410 767380317 \
+workshop_download_item 107410 333310405 \
+workshop_download_item 107410 639837898 \
+workshop_download_item 107410 615007497 \
+quit
```

```
cd /mnt/arma/srv
mkdir /mnt/arma/srv/mods
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/450814997   /mnt/arma/srv/mods/cba
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/463939057   /mnt/arma/srv/mods/ace
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/708250744   /mnt/arma/srv/mods/acex
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/751965892   /mnt/arma/srv/mods/acre
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/843577117   /mnt/arma/srv/mods/rhs_usaf
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/843425103   /mnt/arma/srv/mods/rhs_afrf
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/773125288   /mnt/arma/srv/mods/ace_compat_rhs_usaf
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/773131200   /mnt/arma/srv/mods/ace_compat_rhs_afrf
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/861133494   /mnt/arma/srv/mods/jsrs
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/1180533757  /mnt/arma/srv/mods/jsrs_rhs_usaf
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/945476727   /mnt/arma/srv/mods/jsrs_rhs_afrf
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/723217262   /mnt/arma/srv/mods/achilles
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/498740884   /mnt/arma/srv/mods/st_ui
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/767380317   /mnt/arma/srv/mods/blastcore
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/333310405   /mnt/arma/srv/mods/enhanced_movement
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/639837898   /mnt/arma/srv/mods/advanced_towing
ln -s /mnt/arma/srv/steamapps/workshop/content/107410/615007497   /mnt/arma/srv/mods/advanced_sling_loading
cd /mnt/arma/srv/keys
find -type l -exec rm {} \;
ln -s /mnt/arma/srv/mods/cba/keys/*.bikey                         /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/ace/keys/*.bikey                         /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/acex/keys/*.bikey                        /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/acre/keys/*.bikey                        /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/rhs_usaf/key/*.bikey                     /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/rhs_afrf/key/*.bikey                     /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/jsrs/Keys/*.bikey                        /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/jsrs_rhs_usaf/Keys/*.bikey               /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/jsrs_rhs_afrf/Keys/*.bikey               /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/achilles/keys/*.bikey                    /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/st_ui/keys/*.bikey                       /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/blastcore/keys/*.bikey                   /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/enhanced_movement/Keys/*.bikey           /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/advanced_towing/keys/*.bikey             /mnt/arma/srv/keys/
ln -s /mnt/arma/srv/mods/advanced_sling_loading/keys/*.bikey      /mnt/arma/srv/keys/
```

```
[Unit]
Description=arma dedicated server

[Service]
Type=simple
User=arma
Group=arma
WorkingDirectory=/mnt/arma/srv
Restart=always
ExecStart=/mnt/arma/srv/arma3server -port=2302 -config=server.cfg -name=<profile> -world=empty \
-mod="mods/cba;" \
-mod="mods/ace;" \
-mod="mods/acex;" \
-mod="mods/acre;" \
-mod="mods/rhs_usaf;" \
-mod="mods/rhs_afrf;" \
-mod="mods/ace_compat_rhs_usaf;" \
-mod="mods/ace_compat_rhs_afrf;" \
-mod="mods/jsrs;" \
-mod="mods/jsrs_rhs_usaf;" \
-mod="mods/jsrs_rhs_afrf;" \
-mod="mods/achilles;" \
-mod="mods/st_ui;" \
-mod="mods/blastcore;" \
-mod="mods/enhanced_movement;" \
-mod="mods/advanced_towing;" \
-mod="mods/advanced_sling_loading;" \

[Install]
WantedBy=multi-user.target
```

With the above set everything seems to work as of today (just consume the ACE/ACEX 3.12 release).
