### ISSUE TITLE
Is it possible to insert INCONTINENTIA'S UNDERCOVER

### ISSUE THREAD

**Issue by jus61** [Vdauphin/HeartsAndMinds#491]
https://github.com/1ncontinentia/Incon-Undercover

**Comment by Vdauphin** [comment]
Hello,
I have no idea. Give it  a try!
The H&M integrate a really small feature like this see : https://github.com/Vdauphin/HeartsAndMinds/wiki/InGame-documentation#traffic .
See you soon.
