### ISSUE TITLE
Fallujah Port Errors

### ISSUE THREAD

**Issue by LukesToni** [Vdauphin/HeartsAndMinds#572]
Hello, i been trying to port the mission to fallujah. I follow your steps to do it but i just get theses errors.
 I would like to know if you can help me.
https://i.imgur.com/ETSRHIq.jpg
https://i.imgur.com/XERuk5g.jpg
https://i.imgur.com/6XSJufI.jpg
https://i.imgur.com/fqdBu3k.jpg
https://i.imgur.com/MOFtJeI.jpg
https://i.imgur.com/reudjXP.jpg
https://i.imgur.com/adUEFJI.jpg
https://i.imgur.com/neyaeaA.jpg
 Thank you.

**Comment by Vdauphin** [comment]
Hello,
If you follow the wiki no errors will appear. This is a map issue. Someone work on it, read the BI tread : https://forums.bohemia.net/forums/topic/165948-mp-btc-hearts-and-minds/?page=39&tab=comments#comment-3280136
Also, please fill the issue template if you want help.
Good luck!

**Comment by LukesToni** [comment]
Thank you it works, you could do a tutorial to help people to know how to add new locations because if you dont know is pretty hard to find information about it.

**Comment by Vdauphin** [comment]
Keep it open, I want to add a quick wiki in this part https://github.com/Vdauphin/HeartsAndMinds/wiki/Change-MAP-of-Hearts-and-Minds 

when I will have time :)
