### ISSUE TITLE
Suggestion: Multiple Side Mission at the same time

### ISSUE THREAD

**Issue by DominadorBR** [Vdauphin/HeartsAndMinds#576]
Create an option in Parameters allowing you to change the amount of Side Missions

**Comment by Vdauphin** [comment]
Hello,
Don't really understand the point to have less side mission ?
Cheers

**Comment by Vdauphin** [comment]
I see now, thanks for the clarification!
I am working on it since the start but the framework doesn't allow it. I slowly modernize it but it takes time.
See you soon!
