### ISSUE TITLE
cannot search dead insurgents for intel

### ISSUE THREAD

**Issue by MissVerstanden** [Vdauphin/HeartsAndMinds#579]
**Description:**
I run the mission on a dedicated server and that thing runs 24/7. The pbo has not been updated, yet. server was setup on July, 16th.

Yesterday we started playing again and the issue is that we cannot search dead insurgents for intel anymore. It did work yesterday. We can however still interact with civis.

I tried #restart and #mission as admin. Both did not fix the problem. Next I restarted the server and hc process on the dedicated server. Still no fix for our problem. 

before posting here we used the following mods: https://www.dropbox.com/s/f10wi8bqau9cgz9/ham_altis.html

Today I used the following mods and still could not search dead insurgents for intel after killing them:

**Mods:**

**Arma 3 Version:** `1.82.144710` (stable)
**Hearts and minds Version:** `1.18.3` (stable)
all mods from the workshop:
**CBA Version:** `3.7.1` (stable)
**ACE3 Version:** `3.12.2` (stable)
**RHS USAF Version:** `0.4.5` (stable)
**ACE USAF Compatibility Patch:** `3.12.2` (stable)

**Steps to reproduce:**
load up my server which loads my savegame. kill insurgents and ace-interact with their dead body. Interaction menu only shows medical menu but no search for intel option. I can interact with civis. Sorry did not take a screenshot :|

**mission file:**
https://www.dropbox.com/s/734lamj1c9tl741/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis.pbo.7z unedited release version:  1.18.3

**RPT log files:**
server log: https://pastebin.com/VPg86TCA
hc log: https://pastebin.com/CwKRt6wT
client log: https://pastebin.com/kcVXbAt7

**Comment by MissVerstanden** [comment]
found 2 closed issues with similar (same) problem: 
https://github.com/Vdauphin/HeartsAndMinds/issues/272
https://github.com/Vdauphin/HeartsAndMinds/issues/350

I did use the zeus interface in the past to move objects, heal and teleport players but never spawned in enemy AI. I also did not use zeus or admin in the troubleshoot session where I setup the fewer mods, started the server and connected. After a while I found some enemies to shoot and after the situation was clear I went to a dead body to check the Ace interaction menu.

I think you need my savegame. Is that saved inside the heartsandmindsaltis.vars.Arma3Profile file?

**Comment by Vdauphin** [comment]
> I think you need my savegame. Is that saved inside the heartsandmindsaltis.vars.Arma3Profile file?

Yes, send it if you can.

I checked your mission (identical to the github version as you said), your rpt (no errors) and I see nothing. Launched your mission with same mod and I have the interaction.


![20180723233437_1](https://user-images.githubusercontent.com/14364400/43105398-06afacae-8ed5-11e8-8d8c-ac7378344318.jpg)
![20180723233445_1](https://user-images.githubusercontent.com/14364400/43105401-0951a19c-8ed5-11e8-86b5-80e1d95297c5.jpg)


But I am pretty sure you changed faction between one game saved, from FIA to AAF or anything else. 
So if you saved your game with FIA.
AI saved under city will spawn as FIA even if you updated the faction selection to AAF.
The Hearts and Minds will only had interaction to the AAF but not to FIA.

That the only explanation I have.

A  `typeof cursorobject` on the dead body without interaction would help.

**Comment by MissVerstanden** [comment]
My intention is to play against Syndikat ;)
here is my config.cfg with the startup parameters for the mission: https://pastebin.com/JXdpbZyD

and here is my savegame: https://www.dropbox.com/s/ymgr6ozm4k9a8iu/heartsandmindsaltis.vars.Arma3Profile

> A typeof cursorobject on the dead body without interaction would help.

Can you explain how and where to do that?

**Comment by Vdauphin** [comment]
> Can you explain how and where to do that?

Log as Admin then press escape. You see now the debug console. Then under `watch` write  `typeof cursorobject` and target the dead body. Write the returned string just under the command.

See https://community.bistudio.com/wiki/Mission_Editor:_Debug_Console_(Arma_3)

**Comment by MissVerstanden** [comment]
gives back: "I_C_Soldier_Bandit_5_F"

I am sorry but I really do not know what I am doing here ;)

**Comment by Vdauphin** [comment]
Perfect!
No worries, I am launching your server give me time ;)

**Comment by MissVerstanden** [comment]
awesome.

![20180724214302_1](https://user-images.githubusercontent.com/26272684/43162227-a384ef7a-8f8a-11e8-8f44-8db9eb1d8855.jpg)

just for completene's sake.

**Comment by MissVerstanden** [comment]
hmm. after killing off the Syndikat guys. Other shows up not sure if AAF or FIA and those I can search.
string is "O_G_Soldier_LAT2_F"
![20180724215559_1](https://user-images.githubusercontent.com/26272684/43162824-88703c92-8f8c-11e8-9e07-afcb87fd6e36.jpg)

**Comment by Vdauphin** [comment]
I reproduced your issue thanks to your saved game. The bug come from what I said before:

- You started to play against Syndikat
- You saved your game
- Restart/update pbo
- For some reason you changed to FIA : 
![20180724215540_1](https://user-images.githubusercontent.com/14364400/43162757-59ac3cd0-8f8c-11e8-8895-221c96346ec2.jpg)
(picture took from the dedicated server loaded with the corresponding config.cfg sended)

You can clearly see it in debug mode (green Syndicat (so saved units) and red FIA (city still not visited by your team))

![20180724215102_1](https://user-images.githubusercontent.com/14364400/43162660-04e18b38-8f8c-11e8-807f-d9de4a03d300.jpg)

So you have a mix of faction: you can't search Syndicat but FIA yes.

**Comment by Vdauphin** [comment]
To avoid this issue change your config.cfg like that:
```sqf
class Missions
{
    class Mission_1
    {
        template = "=BTC=co@30_Hearts_and_Minds.Altis";
        difficulty = "custom";
            class Params
            {
              btc_p_time = 9;                      // Starting time
              btc_p_acctime = 4;
              btc_p_db = 1;
              btc_p_auto_db = 0;
              btc_p_en = 190;
              btc_p_civ = 12;
              btc_p_civ_veh = 12;
              btc_p_sea = 0;
              btc_p_side_mission_cycle = 1;
              btc_p_garage = 1;
             
             
            };
    };
 
 
};```

**Comment by Vdauphin** [comment]
Do you understand your mistake ?

**Comment by MissVerstanden** [comment]
you are listing other "startup options" so I assume here lies my config mistake ;)

**Comment by MissVerstanden** [comment]
how would I get those markers that show the faction of the enemy like in your last screenshot?

**Comment by Vdauphin** [comment]
In debug mode clic on the map, the H&M will teleport you to this position. Then AI will spawn accordingly: 
- if you never went in this city, H&M will generate CIV and ENEMY depending on selected faction in params (in your case is FIA), 
- if already visited this city, then H&M will spawn CIV and ENEMY from the database at the correct position and faction it has been saved (in your case Syndicats).

> show the faction of the enemy like in your last screenshot

Color correcpond to the Side:
- white is CIV
- blue is player if you are WEST
- red and green enemy
  - red  for EAST (6 - Bohemia Interactive: 2035 FIA (Side: EAST)") 
  - green for GUER (190 -Tank Bohemia Interactive: 2035 Syndikat (Side: GUER))

The text is the typeof`` unit (equivalent to the `typeof cursorobject` but on all units present on the battelfield)

**Comment by Vdauphin** [comment]
> I can now search Syndikat guys again. will I run into other saved guys I cannot search now?

Only if you saved your game when the FIA faction was selected and some of them have populate city :/

**Comment by MissVerstanden** [comment]
alright. thanks a lot for your help.
