### ISSUE TITLE
Feature Request: Increase time before enemy bodies disappear

### ISSUE THREAD

**Issue by bux** [Vdauphin/HeartsAndMinds#583]
**Arma 3 Version:** `1.84` stable
**CBA Version:** `3.8.0` stable
**ACE3 Version:** `3.12.2` stable
**Hearts and minds Version:** `1.8.3` stable

**Mods:**
```
- CBA_A3
- ace
- TFAR
```

**Description:**
- Enemy bodies disappear to quickly which doesn't leave enough time to salvage information from them. Especially if you fought them over long distances. At least 15 minutes should be added before the bodies disappear.

**Comment by bux** [comment]
Corpse management wasn’t activated.

It was most likely a patrol. But we were far from anything that could be a city. The enemies were killed in the hills by a CAS strike some hundred meters > 400m away from the troops that were the closest.

**Comment by Vdauphin** [comment]
> a CAS strike 

So there was a player inside a plane/helicopter patrolling and then kill those guys ? 

I think the CAS activate and desactivate a city around so the clean_up fnc has been fire and delete those enemies.

**Comment by bux** [comment]
Negative, it was the new Tomahawk missile from the Encore Update (1.84) Laser Designated by the AR-2 Darter drone.

**Comment by Vdauphin** [comment]
Honestly I think for some reason (AR-2 move close to a city may be) the clean_up has been activated. I should increase 300 to 500 for dead body clean up (https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/common/clean_up.sqf#L7)

Can you test it?

**Comment by bux** [comment]
Will do. But it might take one or two weeks.

**Comment by Vdauphin** [comment]
No worries !

**Comment by Vdauphin** [comment]
Hello,
Any feedback on this?
See you soon!

**Comment by bux** [comment]
sadly no, haven't tried yet

**Comment by Vdauphin** [comment]
I also see it. 

It happen when cities radius are overlapping. If you patrol around a city you can activate/desactivate cities overlapping the current city you are patrolling around. So if in the center you killed some enemies, those will be clean up due to the `300` m.

The fix should avoid this side case.
