### ISSUE TITLE
Ammo cache issue

### ISSUE THREAD

**Issue by sgrnit** [Vdauphin/HeartsAndMinds#596]
## Before reporting

If you have found an issue with Hearts and Minds please make sure that Hearts and Minds really is the cause of the problem. To do this try to reproduce the issue with using only `@CBA_A3`, `@ace` and `@RHSUSAF` on a stable and unchanged Hearts and minds available [here](https://github.com/Vdauphin/HeartsAndMinds/releases) on a dedicated server.

(All stable)
**Arma 3 Version:** `1.84.144.923`
**CBA Version:** `3.8.0` 
**ACE3 Version:** `3.12.3`
**RHS USAF Version:** `0.4.7`
**Hearts and minds Version:** `1.18.3` 

**Mods:**
```
3CB BAF Equipment
3CB BAF Weapons
3CB BAF Weapons (ACE compatibility)
ace
ACE Compat - RHS Armed Forces of the Russian Federation
ACE Compat - RHS United States Armed Forces
ACE Compat - RHS: GREF
ACE3 - BWMod Compatibility
ACEX
BlueHud
BWMod
CBA_A3
Clafghan
CUP ACE3 Compatibility Addon - Vehicles
CUP ACE3 Compatibility Addon - Weapons
CUP Terrains - Core
CUP Terrains - Maps
CUP Units
CUP Vehicles
CUP Weapons
Diwako's ACE Ragdolling
F-15 Eagle
F-16 Fighting Falcon
FA-18 Super Hornet
FDF Podagorsk
FIR AWS(AirWeaponSystem)id=366425329
G.O.S Leskovets
HMCS Addon
ILBE Assault Pack (TFAR)
Military Gear Pack
Multi-play Uniforms
NIArms Core
NIArms G3 Rifles
NIArms MP5 SMGs
NIArms SG550 Rifles
Redd'n'Tank Vehicles
RHSAFRF
RHSGREF
RHSSAF
RHSUSAF
Ruha
Skippy Team Roster
Specialist Military Arms (SMA) Version 2.7.1	
SU-35 Flanker E
Suppress	Steam
Task Force Arrowhead Radio (BETA!!)
TAW View Distance
TRI_compat
US Military Mod
USS Nimitz
```

**Description:**

Ammo Box not found. A marker has been exist however we couldn't find also in debug mode.

**Steps to reproduce:**
none

**Add mission file:**
- Zip your .pbo mission file, drag and drop it here.
https://www.dropbox.com/s/lxm8j4ajrov0pr2/%5BJP%5D_Co10_Hearts_and_Minds.Altis.pbo?dl=0

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and server RPT file (you can also change the file extension to a .txt file and drag and drop it here). An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
-------------------------------------------------------------------------------------------------------------------
Hi, I am a user who plays Hearts and Minds in our community server.
I feel so amaaaazing mission and thank the mother of H&M!

Well, we have problem that ammo cache not found bug.
When we destroy it, we can get some markers but can't see the target.
I have confirm about this, so I tried to find using Debug-mode...however not exist!

Anyone help us! We have to delete save data every time :(

**Comment by sgrnit** [comment]
Sorry I'm an editor also not admin, so I can't see any logs file.
Could you reproduce this problem? I will ask admin to show about h&m.

**Comment by 1kuemmel1** [comment]
I think the simplest way to find a solution to your problem is the log-file. So please ask your admin.

Anyway: a reproduce with these amount of mods is really hard. Did you really need all of these? Maybe you can lower the count?
