### ISSUE TITLE
Side missions .sqf manual

### ISSUE THREAD

**Issue by SomethingSimpl** [Vdauphin/HeartsAndMinds#627]
Hi,

Any chance of a short guide on how the side missions are handled? I would have a few ideas on custom side missions Id like to create - Id love some documentation on how locations and enemy squads are handled when your code the side missions.

Regards,

Simple

**Comment by Vdauphin** [comment]
Hello,

No sadly but I can help you. Just ask :)

A good start is to copy an existing side mission from here: https://github.com/Vdauphin/HeartsAndMinds/tree/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/side
Every side mission has a number you need to add in [core/def/mission.sqf#L165-L166](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L165-L166) and should be also add in [/core/fnc/side/create.sqf](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/side/create.sqf) and files in [/core/fnc/task](https://github.com/Vdauphin/HeartsAndMinds/tree/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/task)

See you soon!
