### ISSUE TITLE
Disable helicopters or planes spawning ai

### ISSUE THREAD

**Issue by UncreatedLemon** [Vdauphin/HeartsAndMinds#631]
Is there a way to disable enemies and civilians from spawning into the world when a plane and/or helicopter flies over head? 

I've been having some performance issues (also with disabling vehicles going faster than 190).

Thanks!

**Comment by Vdauphin** [comment]
Hello,

Change this https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L70
`(speed _x > 190)`
to:
`(speed _x > 0)` or anything between 190 to 0

Cheeers
