### ISSUE TITLE
Vehicles at the fob explote

### ISSUE THREAD

**Issue by LukesToni** [Vdauphin/HeartsAndMinds#633]
Im getting this error with he mission

> params [
["_type", "", [""]],
["_pos", [>
 9:58:30   Error position: <params [
["_type", "", [""]],
["_pos", [>
 9:58:30   Error Params: Type Array, expected String
 9:58:30 File mpmissions\__cur_mp.Kunduz\core\fnc\log\createVehicle.sqf, line 26
 9:58:30 Error in expression <teVehicle.sqf"

params [
["_type", "", [""]],
["_pos", [>
 9:58:30   Error position: <params [
["_type", "", [""]],
["_pos", [>
 9:58:30   Error Params: Type Array, expected Number
 9:58:30 File mpmissions\__cur_mp.Kunduz\core\fnc\log\createVehicle.sqf, line 26
 9:58:30 Error in expression <

private _veh  = createVehicle [_type, ASLToATL _pos, [], 0, "CAN_COLLIDE"];
_v>
 9:58:30   Error position: <ASLToATL _pos, [], 0, "CAN_COLLIDE"];
_v>
 9:58:30   Error Type Array, expected Number
 9:58:30 File mpmissions\__cur_mp.Kunduz\core\fnc\log\createVehicle.sqf, line 33
 9:58:31 Ragdoll - loading of ragdoll source "Soldier" started.
 9:58:31 Ragdoll - loading of ragdoll source "Soldier" finished successfully.
 9:58:33 Duplicate weapon rhsusf_weap_duke detected for rhsusf_M1230a1_usarmy_d
 9:58:34 Error in expression <teVehicle.sqf" 

 The mission just start with all the vehicles destroyed and burning and just respawing and exploting again.

Im using this mods
ace, http://steamcommunity.com/sharedfiles/filedetails/?id=463939057
ACE Compat - RHS Armed Forces of the Russian Federation, http://steamcommunity.com/sharedfiles/filedetails/?id=773131200
ACE Compat - RHS United States Armed Forces, http://steamcommunity.com/sharedfiles/filedetails/?id=773125288
Advanced Towing, http://steamcommunity.com/sharedfiles/filedetails/?id=639837898
Blastcore Tracers A3 - FoxFort Edit, http://steamcommunity.com/sharedfiles/filedetails/?id=647768227
CBA_A3, http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
Enhanced Movement, http://steamcommunity.com/sharedfiles/filedetails/?id=333310405
Kunduz Afghanistan - Fixed Doors, http://steamcommunity.com/sharedfiles/filedetails/?id=1188303655
Multi-play Uniforms, http://steamcommunity.com/sharedfiles/filedetails/?id=779520435
NIArms All in One, http://steamcommunity.com/sharedfiles/filedetails/?id=1208517358
Project OPFOR, http://steamcommunity.com/sharedfiles/filedetails/?id=735566597
Radio Animations for Task Force Radio, http://steamcommunity.com/sharedfiles/filedetails/?id=1480333388
RHSAFRF, http://steamcommunity.com/sharedfiles/filedetails/?id=843425103
RHSUSAF, http://steamcommunity.com/sharedfiles/filedetails/?id=843577117
task_force_radio, http://steamcommunity.com/sharedfiles/filedetails/?id=620019431
Vcom AI V3.1, http://steamcommunity.com/sharedfiles/filedetails/?id=721359761

**Comment by Vdauphin** [comment]
Hello,
Could you fill the issue template ?
Also, take a look to : http://vdauphin.github.io/HeartsAndMinds/Add-vehicle-or-boat-to-H&M-system
And delete saved game may be
Cheers

**Comment by Vdauphin** [comment]
can you send the full rtp ?

**Comment by Vdauphin** [comment]
See http://vdauphin.github.io/HeartsAndMinds/InGame-documentation#respawn
So remove the respawn script (ghst_vehrespawn.fsm) you added.
Also, Hearts and Minds has it's own respawn script only for helo (but you can add more : http://vdauphin.github.io/HeartsAndMinds/Add-vehicle-or-boat-to-H&M-system#2-add-respawn-to-vehicle-or-boat).

Good luck!
