### ISSUE TITLE
[Possible Bug] Wrong Comments in /core/def/mission.sqf

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#635]
See:
https://github.com/Vdauphin/HeartsAndMinds/blob/c7c46da54c9b63646f941040355f9a82187620ee/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L497

and:
https://github.com/Vdauphin/HeartsAndMinds/blob/c7c46da54c9b63646f941040355f9a82187620ee/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L509

I wonder if it should be btc_type_gl instead of btc_type_g.

**Comment by Vdauphin** [comment]
Hello,
> I wonder if it should be btc_type_gl instead of btc_type_g.

Yes!

See you soon!
