### ISSUE TITLE
[Crash] H&M Mission seems to cause clients crash frequently after 1.90 update

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#638]
## Before reporting

I have to say that I'm really not sure if this is H&M's problem, because before the 1.90 update, everything works fine.

**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `v3.9.1.181229` (stable)
**ACE3 Version:** `3.12.5` (stable)
**RHS USAF Version:** `0.4.8` (stable)
**Hearts and minds Version:** `1.19.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
- ACE Compat - RHS Armed Forces of the Russian Federation
- ACE Compat - RHS United States Armed Forces
- ACEX
- Arma III Chinese Localization Enhanced
- Enhanced Movement
- RHSAFRF
- task_force_radio
- Vcom AI V3.1
```

**Description:**
At the first day after the 1.90 update release, players in my server encounter crashs with the notification "Too many virtual memory blocks requested" at the same time. They all crash and drop out together at the exact same time with this same error. This situation continues to reproduce until the server saved the mission progress and restarted.

However, After the server restarted, only some of the players crash with the same error, other remains normal, and they do not crash together any more.

I've read the rpt file of all those players and see similar information related to the mission file.
I'm pretty sure that except the mission.sqf, some minor changes of parameters and safezones, and customization of enemy faction no other contents are changed.

![tim 20190306192215](https://user-images.githubusercontent.com/26923626/53877830-2d649b80-4045-11e9-9954-974ecb6c850c.png)

**Steps to reproduce:**
- Join the server, such as mine: 61.160.195.75 (Altis) or 103.26.77.4 (LYTHIUM)
- Play for a while.
- Game client crashes.

**Add mission file:**
- If needed, I'll upload the mission file.

**RPT log file:**
The RPT file with crash infos are here, the error happens at line 31512, and related infos are at the very bottom of the file:
[Wrong file has been deleted, correct files provided below.]
I also keep dump files, if it is needed, please let me know.

**Comment by Vdauphin** [comment]
Hello,
Thanks for this detailed report. I don't see any obvious answer or fix.
Can you upload the full rpt. Looks like I have only the first [13064](https://gist.github.com/GoldJohnKing/a98ce8a1b347c0f41d2ec73ffbd1d798#file-arma3_x64_2019-03-05_16-57-02-rpt-L13064) lines
As I don't see any easy answer it cool be interesting to upload also the mission file, I could run it on a server to reproduce it
I am pretty sure it is a BI issue but I will more investigate just in case
See you soon

**Comment by GoldJohnKing** [comment]
I'm providing the modified mission file on Altis instead of LYTHIUM to make it more convinent. They share the same logic and have the same problem, while the rpt file was on LYTHIUM.

Mission Files:
[LEG_Hearts_and_Minds_RHSUS.Altis.zip](https://github.com/Vdauphin/HeartsAndMinds/files/2939368/LEG_Hearts_and_Minds_RHSUS.Altis.zip)

RPT File:
[Arma3_x64_2019-03-05_16-57-02.zip](https://github.com/Vdauphin/HeartsAndMinds/files/2939377/Arma3_x64_2019-03-05_16-57-02.zip)

**Comment by GoldJohnKing** [comment]
I've collected new RPT files on both client and server "freshly" just after the carsh. The last contents of the server RPT file and the client's are at the exact same time.

[RPT Files (both server's and client's).zip](https://github.com/Vdauphin/HeartsAndMinds/files/2941259/RPT.Files.both.server.s.and.client.s.zip)

**Comment by Vdauphin** [comment]
I took a look to your RPTs and only see twice this error appear when RHS AF trow warning. Nothing really link to the mission :/ The RPT doesn't looks really help full.
Did you check files on your computer ? Sometimes those stupid crash, I experiencing, was just due to an update fail.
I will look to your mission file this week end

**Comment by GoldJohnKing** [comment]
I'm sure I've used Steam to check the files of dedicated server, it told me everything's okay.

However, in case of something, I've reinstalled the whole dedicated server program on one of my servers, to see if the error continues. And I'll use non-modified mission file on another server to see if my modification caused it,

However, the same error happens on several different servers maintained by different clan members using H&M, and we all have nothing changed on the mission file before or after the 1.90 update. This error has never happened on 1.88, 1.84 or even 1.86 version, so I think it might be compability issue with the new 1.90 game version.

**Comment by Vdauphin** [comment]
Hello,
Looks like there is some issue with 1.90 Arma 3 update. I quickly talk about it on ace3 slack, here is what I get from them:
- One of them suggest to remove cache. ch on the server (https://twitter.com/FoltynD/status/1103607813295796224), but from my side I don't really see what it is
> note: the cache is now generated at -profiles= directory into \DataCache\cache.ch 
- some people said they also see some crash on [KP-Liberation](https://github.com/KillahPotatoes/KP-Liberation/issues/570#issuecomment-469909752)
I hope this help

**Comment by GoldJohnKing** [comment]
I've removed cache.ch on both server and client side, the crash continues. By the way, this removal aims to fix "lose connection" problem caused by the new signature vadilation introduced in 1.90 update, seems to have nothing related to the crash problem.

The cache file of my location of my server is here, just at the installation directory of dedicated server: 
D:\SteamCMD\steamapps\common\Arma 3 Server\cache.ch

**Comment by GoldJohnKing** [comment]
A sudden thought came to me that the most similar part of our crash server is that we all use RHS AFRF as an enemy faction, what if it's the enemy faction's fault? So I changed the AFRF enemy to vallina Syndicate, and the server runs well this time.

So it's not the mission's problem. It seems to be some certain AFRF soldier or vehicle spawned randomly caused this error. I'll report this to RHS feedback center.

Thanks a lot for your patience. 🤝 

In case you might have some suggestions, I list my customrized faction settings in /core/def/mission.sqf below:

L486:
```
_allclasse = [[_p_en,"RHS_FACTION_MSV","RHS_FACTION_RVA","RHS_FACTION_TV","RHS_FACTION_VDV","RHS_FACTION_VMF","RHS_FACTION_VPVO","RHS_FACTION_VV","RHS_FACTION_VVS","RHS_FACTION_VVS_C"], _p_en_AA, _p_en_tank] call btc_fnc_mil_class; //Create classes from factions, you can combine factions like that: [[_p_en , "IND_F"], _p_en_AA, _p_en_tank] call btc_fnc_mil_class;
```


L520:
```
btc_type_units = btc_type_units - ["rhs_pilot","rhs_pilot_combat_heli","rhs_pilot_transport_heli","rhs_msv_emr_crew","rhs_msv_crew","rhs_vdv_crew","rhs_vdv_des_crew","rhs_vdv_flora_crew","rhs_vdv_mflora_crew","rhs_vmf_flora_crew","rhs_vdv_officer","rhs_vdv_des_officer","rhs_vdv_flora_officer","rhs_vdv_mflora_officer","rhs_vdv_recon_officer","rhs_vmf_flora_officer","rhs_vmf_recon_officer","rhs_vdv_officer_armored","rhs_vdv_des_officer_armored","rhs_vdv_flora_officer_armored","rhs_vdv_mflora_officer_armored","rhs_vdv_recon_officer_armored","rhs_vmf_flora_officer_armored","rhs_vmf_recon_officer_armored"];
btc_type_motorized = btc_type_motorized + ["C_IDAP_UAV_06_antimine_F","RHS_UAZ_MSV_01","rhs_uaz_vdv","rhs_uaz_vmf","rhs_uaz_vv","rhs_uaz_open_MSV_01","rhs_uaz_open_vdv","rhs_uaz_open_vmf","rhs_uaz_open_vv","RHS_Ural_MSV_01","RHS_Ural_VDV_01","RHS_Ural_VMF_01","RHS_Ural_VV_01","RHS_Ural_Open_MSV_01","RHS_Ural_Open_VDV_01","RHS_Ural_Open_VMF_01","RHS_Ural_Open_VV_01","rhs_typhoon_vdv","RHS_UAZ_chdkz","rhs_uaz_open_chdkz","rhs_ural_chdkz","rhs_ural_open_chdkz","rhs_ural_work_chdkz","rhs_ural_work_open_chdkz","rhs_truck","rhs_gaz66_vmf","rhs_gaz66_vdv","rhs_gaz66_vv","rhs_gaz66_msv","rhs_gaz66o_vmf","rhs_gaz66o_vdv","rhs_gaz66o_vv","rhs_gaz66o_msv","RHS_Mi24P_vvs","RHS_Mi24P_vvsc","RHS_Mi24P_CAS_vvs","RHS_Mi24P_CAS_vvsc","RHS_Mi24P_CAS_vdv","RHS_Mi24P_AT_vvs","RHS_Mi24P_AT_vvsc","RHS_Mi24P_AT_vdv","RHS_Mi24P_vdv","RHS_Mi24V_vvs","RHS_Mi24V_vvsc","RHS_Mi24V_FAB_vvs","RHS_Mi24V_FAB_vvsc","RHS_Mi24V_FAB_vdv","RHS_Mi24V_UPK23_vvs","RHS_Mi24V_UPK23_vvsc","RHS_Mi24V_UPK23_vdv","RHS_Mi24V_AT_vvs","RHS_Mi24V_AT_vvsc","RHS_Mi24V_AT_vdv","RHS_Mi24Vt_vvs","RHS_Mi24V_vdv","RHS_Mi8mt_vvs","RHS_Mi8mt_vvsc","RHS_Mi8mt_vdv","RHS_Mi8mt_vv","RHS_Mi8mt_Cargo_vvs","RHS_Mi8mt_Cargo_vvsc","RHS_Mi8mt_Cargo_vdv","RHS_Mi8mt_Cargo_vv","RHS_Mi8MTV3_vvs","RHS_Mi8MTV3_vvsc","RHS_Mi8MTV3_vdv","RHS_Mi8MTV3_UPK23_vvs","RHS_Mi8MTV3_UPK23_vvsc","RHS_Mi8MTV3_UPK23_vdv","RHS_Mi8MTV3_FAB_vvs","RHS_Mi8MTV3_FAB_vvsc","RHS_Mi8MTV3_FAB_vdv","RHS_Mi8AMT_vvs","RHS_Mi8AMT_vvsc","RHS_Mi8AMT_vdv","RHS_Mi8AMTSh_vvs","RHS_Mi8AMTSh_vvsc","RHS_Mi8AMTSh_UPK23_vvs","RHS_Mi8AMTSh_UPK23_vvsc","RHS_Mi8AMTSh_FAB_vvs","RHS_Mi8AMTSh_FAB_vvsc","RHS_Mi8amt_civilian","RHS_Ka52_vvsc","RHS_Ka52_vvs","RHS_Ka52_UPK23_vvs","RHS_Ka52_UPK23_vvsc"] - ["RHS_Ural_Flat_MSV_01","RHS_Ural_Flat_VDV_01","RHS_Ural_Flat_VMF_01","RHS_Ural_Flat_VV_01","RHS_Ural_Open_Flat_MSV_01","RHS_Ural_Open_Flat_VDV_01","RHS_Ural_Open_Flat_VMF_01","RHS_Ural_Open_Flat_VV_01","RHS_Ural_Repair_MSV_01","RHS_Ural_Repair_VDV_01","RHS_Ural_Repair_VMF_01","RHS_Ural_Repair_VV_01","rhs_gaz66_flat_vmf","rhs_gaz66_flat_vdv","rhs_gaz66_flat_vv","rhs_gaz66_flat_msv","rhs_gaz66o_flat_vmf","rhs_gaz66o_flat_vdv","rhs_gaz66o_flat_vv","rhs_gaz66o_flat_msv","rhs_kamaz5350_flatbed_msv","rhs_kamaz5350_flatbed_cover_msv","rhs_kamaz5350_flatbed_cover_vdv","rhs_kamaz5350_flatbed_cover_vmf","rhs_kamaz5350_flatbed_vmf","rhs_kamaz5350_flatbed_cover_vv","RHS_Ural_Open_Flat_VV_01","rhs_zil131_flatbed_cover_vv","rhs_kamaz5350_flatbed_vdv","rhs_zil131_flatbed_cover_msv","rhs_zil131_flatbed_msv","rhs_zil131_flatbed_cover_vdv","rhs_zil131_flatbed_vdv","rhs_zil131_flatbed_cover_vmf","rhs_zil131_flatbed_vmf","rhs_zil131_flatbed_cover_vv","rhs_zil131_flatbed_vv","rhs_gaz66_ammo_vmf","rhs_gaz66_ammo_vdv","rhs_gaz66_ammo_vv","rhs_gaz66_ammo_msv","RHS_Ural_Fuel_MSV_01","RHS_Ural_Fuel_VDV_01","RHS_Ural_Fuel_VMF_01","RHS_Ural_Fuel_VV_01","rhs_gaz66_repair_vmf","rhs_gaz66_repair_vdv","rhs_gaz66_repair_vv","rhs_gaz66_repair_msv","rhs_gaz66_r142_vmf","rhs_gaz66_r142_vdv","rhs_gaz66_r142_msv","rhs_gaz66_r142_vv","rhs_gaz66_ap2_vmf","rhs_gaz66_ap2_vdv","rhs_gaz66_ap2_vv","rhs_gaz66_ap2_msv","RHS_Su25SM_vvs","RHS_Su25SM_KH29_vvs","RHS_Su25SM_vvsc","RHS_Su25SM_KH29_vvsc","rhs_9k79","rhs_9k79_K","rhs_9k79_B"];
btc_type_motorized_armed = btc_type_motorized_armed + ["rhs_btr60_vmf","rhs_btr60_vdv","rhs_btr60_vv","rhs_btr60_msv","RHS_BM21_MSV_01","RHS_BM21_VDV_01","RHS_BM21_VMF_01","RHS_BM21_VV_01","rhs_ka60_grey","rhs_ka60_c","rhs_bmd1","rhs_bmd1k","rhs_bmd1p","rhs_bmd1pk","rhs_bmd1r","rhs_bmd2","rhs_bmd2m","rhs_bmd2k","rhs_bmp1_vdv","rhs_bmp1_tv","rhs_bmp1_msv","rhs_bmp1_vmf","rhs_bmp1_vv","rhs_bmp1p_vdv","rhs_bmp1p_tv","rhs_bmp1p_msv","rhs_bmp1p_vmf","rhs_bmp1p_vv","rhs_bmp1k_vdv","rhs_bmp1k_tv","rhs_bmp1k_msv","rhs_bmp1k_vmf","rhs_bmp1k_vv","rhs_bmp1d_vdv","rhs_bmp1d_tv","rhs_bmp1d_msv","rhs_bmp1d_vmf","rhs_bmp1d_vv","rhs_bmp2e_vdv","rhs_bmp2e_tv","rhs_bmp2e_msv","rhs_bmp2e_vmf","rhs_bmp2e_vv","rhs_bmp2_vdv","rhs_bmp2_tv","rhs_bmp2_msv","rhs_bmp2_vmf","rhs_bmp2_vv","rhs_bmp2k_vdv","rhs_bmp2k_tv","rhs_bmp2k_msv","rhs_bmp2k_vmf","rhs_bmp2k_vv","rhs_bmp2d_vdv","rhs_bmp2d_tv","rhs_bmp2d_msv","rhs_bmp2d_vmf","rhs_bmp2d_vv","rhs_brm1k_vdv","rhs_brm1k_tv","rhs_brm1k_msv","rhs_brm1k_vmf","rhs_brm1k_vv","rhs_bmp3_msv","rhs_bmp3_late_msv","rhs_bmp3m_msv","rhs_bmp3mera_msv","rhs_btr70_vmf","rhs_btr70_vdv","rhs_btr70_vv","rhs_btr70_msv","rhs_btr80_msv","rhs_btr80_vdv","rhs_btr80_vv","rhs_btr80_vmf","rhs_btr80a_msv","rhs_btr80a_vdv","rhs_btr80a_vv","rhs_btr80a_vmf","rhs_tigr_vdv","rhs_tigr_vmf","rhs_tigr_msv","rhs_tigr_vv","rhs_tigr_3camo_vdv","rhs_tigr_3camo_vmf","rhs_tigr_3camo_msv","rhs_tigr_3camo_vv","rhs_tigr_ffv_vdv","rhs_tigr_ffv_vmf","rhs_tigr_ffv_msv","rhs_tigr_ffv_vv","rhs_tigr_ffv_3camo_vdv","rhs_tigr_ffv_3camo_vmf","rhs_tigr_ffv_3camo_msv","rhs_tigr_ffv_3camo_vv","RHS_BM21_chdkz","RHS_Mi8amt_chdkz","rhs_bmd2_chdkz","rhs_bmd1_chdkz","rhs_btr70_chdkz","rhs_btr60_chdkz","rhs_t72bb_tv","rhs_t72bb_chdkz","rhs_bmd4_vdv","rhs_bmd4m_vdv","rhs_bmd4ma_vdv","rhs_t72ba_tv","rhs_t72bc_tv","rhs_t72bd_tv","rhs_t90_tv","rhs_t90a_tv","rhs_t80b","rhs_t80bk","rhs_t80bv","rhs_t80bvk","rhs_t80","rhs_t80a","rhs_t80u","rhs_t80uk","rhs_t80u45m","rhs_t80ue1","rhs_t80um","rhs_gaz66_zu23_msv","rhs_gaz66_zu23_vdv","rhs_gaz66_zu23_vmf","rhs_gaz66_zu23_vv","rhs_2s3_tv","rhs_zsu234_aa"] - ["RHS_Su25SM_vvs","RHS_Su25SM_KH29_vvs","RHS_Su25SM_vvsc","RHS_Su25SM_KH29_vvsc","rhs_9k79","rhs_9k79_K","rhs_9k79_B"];
btc_type_gl = btc_type_gl + ["rhs_D30_msv","rhs_D30_at_msv","rhs_2b14_82mm_msv","rhs_D30_vdv","rhs_D30_at_vdv","rhs_2b14_82mm_vdv","rhs_D30_vmf","rhs_D30_at_vmf","rhs_2b14_82mm_vmf"];
```

**Comment by GoldJohnKing** [comment]
I've reported this issue on RHS Feedback, they seems to have difficulty in looking into the problem... so I have to investigate by my self.

Link to RHS Feedback:
http://feedback.rhsmods.org/view.php?id=4839

And if there's nothing important, please close this issue. I'll reopen it if I have something related to H&M to report.

**Comment by Vdauphin** [comment]
> And if there's nothing important, please close this issue. I'll reopen it if I have something related to H&M to report.

Lets keep this issue open in case someone has the same issue and follow your work on this

**Comment by Vdauphin** [comment]
Does the issue still happen for yo ?

**Comment by GoldJohnKing** [comment]
Nope. Since Arma 3 pushed v 1.90-Hotfix Update, this issue had never happened anymore even with RHS AFRF as enemy faction. So I think this issue could be closed.
