### ISSUE TITLE
save and load progress

### ISSUE THREAD

**Issue by topden** [Vdauphin/HeartsAndMinds#640]
**Arma 3 Version:** last
**CBA Version:** last 
**ACE3 Version:** last
**RHS USAF Version:* *last
**Hearts and minds Version:** last

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
```
. if you save the progress of the mission, and then load it, then the vehicles base starts to drop (dup) and explode. I think this is after updating the Arma 1.90. Do you have such a problem?

http://joxi.ru/J2bBgZqCXjqj32

On the screen you can see that on the site of the vehicle when the mission is restarted, the vehicles appears again. and so on to infinity. Yes, I just changed the vehicles and the place of the base, but I did not touch the files and scripts. In your original version, the vehicles also overlaps the previous one.

all these cars with names - btc_veh_1, btc_veh_2, btc_veh_3, btc_veh_4, btc_veh_5, btc_veh_6, btc_veh_7, btc_veh_8, btc_veh_9, btc_veh_10, btc_veh_11, btc_veh_12, btc_veh_13, btc_veh_14, btc_veh_15

**Comment by Vdauphin** [comment]
Hello,
Can you fill the issue template ?
See you soon

**Comment by Vdauphin** [comment]
Also provide the vars.arma3Profil see https://community.bistudio.com/wiki/Profile ?
