### ISSUE TITLE
rpt error

### ISSUE THREAD

**Issue by topden** [Vdauphin/HeartsAndMinds#641]
>  4:44:59 Error in expression <
if (!isServer) exitWith {
[[_task_id], btc_player_side, _description, _destinat>
 4:44:59   Error position: <btc_player_side, _description, _destinat>
 4:44:59   Error Undefined variable in expression: btc_player_side
 4:44:59 File mpmissions\__CUR_MP.Tanoa\core\fnc\task\create.sqf, line 111
 4:44:59 "=BTC= HEARTS AND MINDS VERSION 1.19.2"

rpt client. but in mission on dedicate server are all ok. side missions starts and working

**Comment by Vdauphin** [comment]
Hello,
Can you fill the issue template ?
See you soon
