### ISSUE TITLE
earplugs

### ISSUE THREAD

**Issue by topden** [Vdauphin/HeartsAndMinds#642]
I wanted to add an earplug script to mission (I took the simplest one), but it doesn't work on a dedicated server. Turn them on f4 and then the sound returns, as if something had canceled it. I tried with other scripts earplug - the same thing. What could be the problem? Earplugs are needed, the sounds of helicopters and cars are sometimes strained heavily)

script for example. in rpt or debug console haven't errors.

> 
> call {0 spawn {
> 	waitUntil {!isNull(findDisplay 46)};
> 	(findDisplay 46) displayAddEventHandler ["KeyDown", {
> 		if(_this select 1 == 0x3E) then {
> 			_earplugsctrl = (_this select 0) displayCtrl 9001;
> 			if(isNull(_earplugsctrl)) then {
> 				_earplugsctrl = (_this select 0) ctrlCreate ["RscText", 9001];
> 				_earplugsctrl ctrlSetPosition [SafeZoneXAbs, SafeZoneY + (SafeZoneH - 0.05) / 2, 0.2, 0.03];
> 				_earplugsctrl ctrlSetFontHeight 0.03;
> 				_earplugsctrl ctrlSetText "Беруши";
> 				_earplugsctrl ctrlShow false;
> 				_earplugsctrl ctrlCommit 0;
> 			};
> 			_shown = ctrlShown _earplugsctrl;
> 			0.1 fadeSound (if(_shown)then{1}else{0.1});
> 			_earplugsctrl ctrlShow !_shown;
> 		};
> 	}];
> };};

**Comment by Vdauphin** [comment]
Hello,
> What could be the problem?

I don't know, why are you not using ACE Earplugs: https://ace3mod.com/wiki/feature/hearing.html

Cheers

**Comment by topden** [comment]
ACE plugs not automatically. The problem is that any of the security earplugs in the mission does not work on a dedicated server. when you turn on the earplugs, the sound is reduced, and then restored to 1. and this is regardless of what type of set it is. so I wanted to understand what can "cancel" muting the sound with a script ...okay. I'll try to figure it out. thank

**Comment by Vdauphin** [comment]
> the sound is reduced, and then restored to 1.

May be due to ACE as is already include this feature you may be have a conflict
Try to ask to ACE
