### ISSUE TITLE
Feature Request: Save vehicles' parameters when respawning vehicles wrecks

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#644]
When vehicles with ACE paremeters (such as "is repair vehicle" or "cargo space") are destroyed and repaired, the vehicle respawn without these properties. Loading a mission seems to share the same circumstances. This is really inconvenient in most cases with custom vehicles. Would you please add that feature?

**Comment by Vdauphin** [comment]
Hello
> are destroyed and repaired,
You mean by using the repair wreck feature from the logistic box ?

**Comment by GoldJohnKing** [comment]
Yes, after wreck repaired, most of the parameters lost.

**Comment by Vdauphin** [comment]
Oh I get your point

**Comment by Vdauphin** [comment]
> "cargo space"

Cargo space is overwrite by Hearts and Minds. You can add the class name of your vehicle here:
https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L408-L414

`cc` is for the cargo space
`rc` is for the size of the vehicle/object
All can be tweak here: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L379-L423

Cheers

**Comment by GoldJohnKing** [comment]
What about "is repair/medical/fuel-supply vehicle" and "dynamic weapons loading" settings?

**Comment by Vdauphin** [comment]
> is repair/medical/fuel-supply vehicle

Notes
- medical https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_moduleAssignMedicalVehicle.sqf#L26

- repair https://github.com/acemod/ACE3/blob/master/addons/repair/functions/fnc_moduleAssignRepairVehicle.sqf#L26
https://ace3mod.com/wiki/framework/repair-framework.html
- fuel https://ace3mod.com/wiki/framework/refuel-framework.html
https://github.com/acemod/ACE3/tree/master/addons/refuel/functions
