### ISSUE TITLE
Heli destroyed when using ACE fastrope system unable to respawn at logistic point

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#646]
**Arma 3 Version:** `1.86~1.90` (stable)
**CBA Version:** `newest release on steam workshop` (stable)
**ACE3 Version:** `newest release on steam workshop` (stable)
**RHS USAF Version:** `0.4.8` (stable)
**Hearts and minds Version:** `1.19.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
```

**Description:**
- When a heli using or used ACE fastropes then being destroyed, it's wreck has a chance to encounter "This is not a wreck" when repairing. However, ACE's fastrope pipe is unable to disable through Zeus, so it's sometimes unable to repair heli wrecks.
- I've made sure there's no other things alongside the heli wreck, except for 2 or 3 fastrope pipe, or none or someropes (no matter if there's ropes, ropes seem not causing it).

I've read the this:
https://github.com/Vdauphin/HeartsAndMinds/blob/1e3ecb0ebf98b1d1b3e1d1b402c88b9073d17caf/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/log/repair_wreck.sqf#L27

It seems to be handled already, but the "This is not a wreck" does frequently happen when we repair helis. I've tested on both local and dedicated servers, local server seems not having the problem (may be I did not tested enough times), but this occurs on dedicated server frequently.

**Steps to reproduce:**
- Destroy a heli using or used ACE fastropes.
- Sling load the wreck to logistic point.
- Try to repair it.
- Sometimes "This is not a wreck" occurs.
- Note the problem seems not happening on local server.

**Comment by Vdauphin** [comment]
Hello,

> It seems to be handled already

Yes :/

Can you change line :  https://github.com/Vdauphin/HeartsAndMinds/blob/1e3ecb0ebf98b1d1b3e1d1b402c88b9073d17caf/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/log/repair_wreck.sqf#L31 to:
```sqf

if (damage (_array select 0) != 1) exitWith {
    hint localize "STR_BTC_HAM_LOG_RWRECK_NOTWRECK";
    systemChat str(_array);
};

```
And take a screen shot of the output. Then we could know what is actually causing the issue
Cheers

**Comment by GoldJohnKing** [comment]
After massive amounts of tests, I finally reproduced the bug...

This problem only happens when helis with ACE fastropes are destroyed just at the same time that players are **ON** the rope. (I'm not sure if I reach the point...)

The debug output is:

![107410_20190327234000_1 - 副本](https://user-images.githubusercontent.com/26923626/55091492-e0c42b80-50eb-11e9-9794-a9a6e22276ac.png)

![107410_20190327234000_1](https://user-images.githubusercontent.com/26923626/55091407-bd997c00-50eb-11e9-80b3-5dd5b5c951c8.png)

**Comment by Vdauphin** [comment]
Could you please test the linked fix ?

**Comment by GoldJohnKing** [comment]
Yep, Fixed.
