### ISSUE TITLE
[Question]Some of the enemy AI units are spawned in "SAFE" wapoint mode that they do not auto engage players

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#650]
**Arma 3 Version:** `1.90` (stable)
**Hearts and minds Version:** `1.19.2` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
- VCOM AI 3.2.2
```

**Description:**
I've recently noticed that some of the enemy AI units are spawned with "SAFE" wapoints. Those AI has a really low willings to engage or spot players, unless they are first attacked by players. This happens especially on AI vehicles, they just drive pass standing players infantries or vehicles, chasing their waypoints far away in another city.
According to this wiki(https://community.bistudio.com/wiki/AI_Behaviour), AI should be auto changed into AWARE mode if they spot player units. However, according to my observation, Most of the AI in SAFE mode do not changed into AWARE mode when they see players, they only become AWARE when they are attacked. Some bomb UAVs even auto downgrade to CARELESS mode.
I use Achilles to see what mode are AIs in, and my server also has VCOM AI. I do not know if it is H&M's problem, but I suggest to change or force all default wapoint mode to "AWARE" in case of unexpected behaviours.

**Steps to reproduce:**
- Find a AI vehicles units with "SAFE" waypoints.
- Chase them by a car, or just teleported to the front of them.
- AI just drive pass the player, chasing their waypoints in another city, and seems to have no willings to engage players. That means you would not be engaged by those AI.

**Comment by Vdauphin** [comment]
Hello,

> I've recently noticed that some of the enemy AI units are spawned with "SAFE" wapoints.

Yes, this is intended. In safe mode, vehicles follow carefully road. In other mode, those will drive over field :/
https://community.bistudio.com/wikidata/images/0/01/Behaviour_paths.gif

>  they just drive pass standing players infantries or vehicles, chasing their waypoints far away in another city.

Never notice this

> Some bomb UAVs even auto downgrade to CARELESS mode.

This is also intended. This has been choose to be sure the drone follow the desired path without trouble due to player presence.

Cheers

**Comment by GoldJohnKing** [comment]
My server has several changes recently, so I'm not sure if it's VCOM 3.2.2 update's problem, but many players has reported that killing one of the infantry in a SAFE two-men partrol group wont cause the other one change to AWARE mode. They only engage player when they both spot and are attacked by players. I'll try to investigate deeper...

**Comment by GoldJohnKing** [comment]
VCOM has confirmed that this is their problem.
