### ISSUE TITLE
[Feature Request]Add restricted loadouts check after player exit the arsenal.

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#652]
**Version:**
**Hearts and minds Version:** `1.19.2` (stable)

**Description:**
- For now, the restricted equipments are just removed from the arsenal, but players can still get them by saving the loadouts including them in offline arsenal then loading it online. I request adding a feature of auto removing those restricted equipments upon player exiting the arsenal.

**Comment by 1kuemmel1** [comment]
Hello GoldJohnKing 👋 

I just took a look at your request and I have to say: the ACE3-Arsenal can already handle what you want.
Or do you mean the BIS-Arsenal? (please keep in mind: the BIS-Arsenal can't handle the remove only function on a full arsenal -> take a look [here](https://community.bistudio.com/wiki/Arma_3_Arsenal#Remove))

As a workaround for the BIS-Arsenal, you can try the following (just insert it at the end of [/core/fnc/eh/player.sqf](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf)):

`
[ missionNamespace, "arsenalClosed", {
    btc_custom_arsenal params ["_weapons", "_magazines", "_items", "_backpacks"];
    {if (_x in _weapons) then {player removeWeapon _x;};} forEach weapons player;
    {if (_x in _magazines) then {player removeMagazine _x;};} forEach magazines player;
    {if (_x in _items) then {player unassignItem _x; player removeItem _x;};} forEach (items player + assignedItems player);
    if (backpack player in _backpacks) then {removeBackpack player;};
}] call BIS_fnc_addScriptedEventHandler;
`

greeting 😃

**Comment by GoldJohnKing** [comment]
> 
> 
> Hello GoldJohnKing 👋
> 
> I just took a look at your request and I have to say: the ACE3-Arsenal can already handle what you want.
> Or do you mean the BIS-Arsenal? (please keep in mind: the BIS-Arsenal can't handle the remove only function on a full arsenal -> take a look [here](https://community.bistudio.com/wiki/Arma_3_Arsenal#Remove))
> 
> As a workaround for the BIS-Arsenal, you can try the following (just insert it at the end of [/core/fnc/eh/player.sqf](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf)):
> 
> `[ missionNamespace, "arsenalClosed", { btc_custom_arsenal params ["_weapons", "_magazines", "_items", "_backpacks"]; {if (_x in _weapons) then {player removeWeapon _x;};} forEach weapons player; {if (_x in _magazines) then {player removeMagazine _x;};} forEach magazines player; {if (_x in _items) then {player unassignItem _x; player removeItem _x;};} forEach (items player + assignedItems player); if (backpack player in _backpacks) then {removeBackpack player;}; }] call BIS_fnc_addScriptedEventHandler;`
> 
> greeting 😃

Nope, I donot mean BI Arsenal, I mean ACE Arsenal.

**Comment by 1kuemmel1** [comment]
>Nope, I donot mean BI Arsenal, I mean ACE Arsenal.

Oh, ok. 🤔  So you could try this: 
`["ace_arsenal_displayClosed", {
    btc_custom_arsenal params ["_weapons", "_magazines", "_items", "_backpacks"];
    {if (_x in _weapons) then {player removeWeapon _x;};} forEach weapons player;
    {if (_x in _magazines) then {player removeMagazine _x;};} forEach magazines player;
    {if (_x in _items) then {player unassignItem _x; player removeItem _x;};} forEach (items player + assignedItems player);
    if (backpack player in _backpacks) then {removeBackpack player;};
}] call CBA_fnc_addEventHandler;`

> Currently adding restricted equipments in defice_mod.sqf does not auto remove loaded restricted equipment on player exit the ACE Arsenal.

That´s a bit strange. I couldn't reproduce this. Can you send the mission files?

**Comment by GoldJohnKing** [comment]
Here's the mission file, please notice that it's not a stable modified version.
[SGLA_Hearts_and_Minds_Lingor.lingor3.zip](https://github.com/Vdauphin/HeartsAndMinds/files/3051660/SGLA_Hearts_and_Minds_Lingor.lingor3.zip)

**Comment by Vdauphin** [comment]
> I just took a look at your request and I have to say: the ACE3-Arsenal can already handle what you want.

I didn't know that so I just checked and yes, I am agree

**Comment by GoldJohnKing** [comment]
I've run a rough test, weapons and items (like GPS or UAV Terminal) can be handled correctly. However, I banned a NVG in define_mod.sqf, and player still can have it by loading from their saved loadouts. I have extremely limited time so I haven't had enough time to investigate, but I'll try to provide enough information if more circumstances are tested. But as for current info, it seems to be an ACE issue.

**Comment by GoldJohnKing** [comment]
Sure to reproduce the problem discribed above, it's sure to be an ACE issue.
