### ISSUE TITLE
[BUG]Respawned vehicles align to terrain instead of their placed rotations, causing large vehicles on custom surface stuck into the surface and crash instantly when respawned.

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#653]
**Hearts and minds Version:** `1.19.2` (stable)

**Description:**
- Respawned vehicles (like Chinook) align to terrain instead of their placed rotations, causing large vehicles (like V-44X Blackfish) on custom surface (such as aircraft carriers) stuck into the surface and crash instantly after spawned.
This does not happen on small vehicles like A-164, F22 or Chinook.

**Steps to reproduce:**
- Place a custom surface on a non-flat terrain, for example, an aircraft carrier on a non-flat seabed.
- Then place a V-44X just above the non-flat area on the custom surface, then adjust the V-44X's rotation to fit the custom placed surface.
- Add the V-44X into the btc_helo list to have it auto respawn.
- Load the mission, destroy the V-44X using Zeus.
- Wait for the respawn count and you'll see an instant crash of the V-44X. If you take a closer look, you will find it first stuck into the surface once respawned, then crash.

**Addition:**
I've noticed that Zeus placed items also auto align to terrain rather than surface, so I wonder if this is a mission fixable problem.
But as it's not happening on small vehicles, I submit the issue here.
And I wonder if this would be helpful: https://github.com/AxelMontini/zeus-surface-placing-fix

**Comment by Vdauphin** [comment]
mission.sqm exemple of fail : 
[mission.zip](https://github.com/Vdauphin/HeartsAndMinds/files/3025392/mission.zip)

**Comment by Vdauphin** [comment]
Can you test this fix?

**Comment by GoldJohnKing** [comment]
Yeah! This fix is perfect!
