### ISSUE TITLE
[Feature Request] Save auto-respawnable vehicles' (btc_helo) param and reapawn them with it.

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#654]
**Hearts and minds Version:** `1.19.2` (dev 63e421f)

**Description:**
- This request is similar to https://github.com/Vdauphin/HeartsAndMinds/issues/644 .
- The auto-respawnable vehicles (btc_helo) do not respawn with the customrized parameters set in Eden Editor, they respawn with their default params.
- I request for a feature of saving their customrized params (such as dynamic loadouts, skins and ace settings, etc) at the very first, and respawn those "btc_helo" vehicles with those params every time.
(Your mission is heavily used by our clan and we do love your mission, so there's plenty of feedbacks from us. Thanks for your efforts on this mission.)

**Comment by GoldJohnKing** [comment]
"bec_helo"'s fuel and ammo amount are still not included in the saving.
When Editor placed non-fuel or non-ammo vehicles are respawned, they always have full fuel and ammo amount.
These params are also unsaved on "btc_veh"s.

**Comment by Vdauphin** [comment]
> "bec_helo"'s fuel and ammo amount are still not included in the saving.

btc_helo_1 is crucial for the H&M because it is the only one who can recover any btc_veh's
So this is intended, this prevent player be stuck by a bug on the btc_helo_1

> When Editor placed non-fuel or non-ammo vehicles are respawned, they always have full fuel and ammo amount.
> These params are also unsaved on "btc_veh"s.

The repair wreck feature or auto-respawn respawn vehicle with full fuel and ammo amount. This make sense as those vehicles are fully destroyed (no more engine, no more cabin, no more fuel and ammo inside).

**Comment by GoldJohnKing** [comment]
I dont mean set their ammo and fuel to zero by default after they just respawn, I mean saving their Eden Editor setted condition, and respawn those vehicles with the same condition as editor setted. If editor set fuel to zero, then they respawn with zero fuel, the same for the ammo.
