### ISSUE TITLE
Map marker of the destoyed ammo cache is not saved

### ISSUE THREAD

**Issue by madpat3** [Vdauphin/HeartsAndMinds#662]
**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `3.10.1` (stable)
**ACE3 Version:** `3.12.6` (stable)
**Hearts and minds Version:** `1.19.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- After destroying an ammo cache, a marker ist placed on map (red X). After restarting the mission, the marker is gone (don't know if it's intendet).

**Steps to reproduce:**
- Destroy an ammo cache. Save the mission's progess (as Admin). Restart the mission.

**Comment by Vdauphin** [comment]
Hello,

> After destroying an ammo cache, a marker ist placed on map (red X). After restarting the mission, the marker is gone (don't know if it's intendet).

It is intended, you have an infinite number of ammo cache

Cheers

**Comment by madpat3** [comment]
ah, ok.
