### ISSUE TITLE
Error message with edited version

### ISSUE THREAD

**Issue by madpat3** [Vdauphin/HeartsAndMinds#663]
**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `3.10.1` (stable)
**ACE3 Version:** `3.12.6` (stable)
**Hearts and minds Version:** `1.19.3` (stable)

**Mods:**
```
- CBA_A3
- ace
- BW-Mod
- BWA3 Add (https://steamcommunity.com/sharedfiles/filedetails/?id=1326881314)
- GM: Demo
- Hafm Choppers
- SFPBo105
```

**Description:**
- When starting the mission, sometimes an error message occurs, saying:
**15:43:26   Error Nicht definierte Variable in Ausdruck: btc_cache_pos
15:43:26 File C:\Users\User\Documents\Arma 3 - Other Profiles\Patrick\mpmissions\=BTC=co@30_Hearts_and_Minds_Bw3.Altis\core\fnc\city\activate.sqf, line 156**.

**Steps to reproduce:**
- Play the attached mission.
- I added some additional scripts.

**Add mission file:**
- [=BTC=co@30_Hearts_and_Minds_Bw.Altis.zip](https://github.com/Vdauphin/HeartsAndMinds/files/3051586/BTC.co%4030_Hearts_and_Minds_Bw.Altis.zip).

**RPT log file:**
- https://www.dropbox.com/s/ql8h86ilfylw6dy/Arma3_x64_2019-04-07_14-57-56.rpt?dl=0.

**Comment by 1kuemmel1** [comment]
Hello 😃

First of all, thank you for your report.

This error occurs only if you are too fast. Just wait a bit on the "map-screen" (basically till the Diary log appears on the left side).

greetings
