### ISSUE TITLE
Respawn helicopter doesn't respawn, after chrashing in water

### ISSUE THREAD

**Issue by madpat3** [Vdauphin/HeartsAndMinds#664]
**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `3.10.1` (stable)
**ACE3 Version:** `3.12.1` (stable)
**Hearts and minds Version:** `1.9.3` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- While flying the chinook, i got shot by enemy infantry, and ended in the sea.
afterwards the helicopter didn't respawn. (maybe i should mention, that i managed to get out of the chopper alive, before it chrashed into the sea).

**Steps to reproduce:**
- Play mission, fly chinook and chrash in sea.

**Comment by Vdauphin** [comment]
Hello,
Ask why to BI: https://feedback.bistudio.com/T84869
Just save and restart, the helo will be back again :/
Cheers

For reference: https://github.com/Giallustio/HeartsAndMinds/issues/52
