### ISSUE TITLE
[Question]Codes in "init" field of an object execute only once, so "btc_dont_delete" value have no effect on respawned vehicles.

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#665]
**Arma 3 Version:** `1.90` (stable)
**Hearts and minds Version:** `1.9.13` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
```

**Description:**
In Eden Editor, it seems that codes in "init" field of a object execute only once on server startup or client connect, it wont execute again on vehicle respawned, so "this setVariable ["btc_dont_delete",true]" have no effect on respawned vehicles. 
I've disbaled wreck control function in Eden Editor but sill found some wrecks disappear during mission few times, I'm just wondering if this is the problem.

**Reference:**
- http://killzonekid.com/arma-scripting-tutorials-basic-multiplayer-coding-v2/
- http://vdauphin.github.io/HeartsAndMinds/Add-vehicle-or-boat-to-H&M-system

**Addition:**
I found this possibly issue when applying custom init codes to a object in H&M. Though I googled related info, as just a normal player and a non-native English speaker, I'm not sure if I'm right about it. I can only infer from my previous experience to say it may be a possible issue, and I think it worth to be checked again.

**Comment by Vdauphin** [comment]
Hello,
> it seems that codes in "init" field of a object execute only once on server startup or client connect,

Yes 

>  so "this setVariable ["btc_dont_delete",true]" have no effect on respawned vehicles.

This is a little wrong because H&M reapply it on vehicle respawn with [btc_fnc_log_createVehicle](https://github.com/Vdauphin/HeartsAndMinds/blob/1d382c7e3634ace76458b30509f6a3d9620bd28a/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/log/createVehicle.sqf#L74)

Also for vehicle, this variable is no more used by H&M it could be drop for next major release

>  wreck control function in Eden Editor 

I don't know what it is but feel like it will be in conflict with H&M werck system

> it sill found some wrecks disappear during mission few times,

Which wreck is disappearing? (` btc_vehicles` aren't suppose to disappear, other are autoclean up by [this](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/data/get_group.sqf#L77) )

Cheers

**Comment by GoldJohnKing** [comment]
>This is a little wrong because H&M reapply it on vehicle respawn with btc_fnc_log_createVehicle

Ah, I get it.

> I don't know what it is but feel like it will be in conflict with H&M werck system

It is called "Garbage Collection" in English interface of Eden Editor, under "Performance" dialog, and it does conflict with H&M werck system.
It seems no use disabling this function in Eden Editor, so I disabled it in description.ext by adding:
```
wreckManagerMode = 0;
corpseManagerMode = 0;
```
Then we never found btc_veh wrecks disappear till now, I suggest adding it to H&M's description.ext to avoid potential problem.

>Which wreck is disappearing? ( btc_vehicles aren't suppose to disappear, other are autoclean up by this )

Randomly btc_vehs' wreck seems to be disappearing, mostly happen after an hour after it changed into a wreck, and sometimes also happen instantly when mission is saved manually. Because it do happen randomly so I don't really have some certain results, but as I mentioned above, we seem to solve the problem by using the above method.

**Comment by Vdauphin** [comment]
> Then we never found btc_veh wrecks disappear till now, I suggest adding it to H&M's description.ext to avoid potential problem.

I am not sure if it will because I don't know if description.ext has a higher priority than mission.sqm

**Comment by GoldJohnKing** [comment]
I'm not sure, either. I've read all this (https://community.bistudio.com/wiki/Description.ext) but found nothing about priorities.
Though I cant be sure, I did run some tests that indicate description.ext has a higher priority than mission.sqm.
I set "respawn", "disabledAI" and "reviveMode" in description.ext and corresponding settings in mission.sqm, it shows that description.ext takes priority instead of mission.sqm. It seems that description.ext takes priority instead of mission.sqm at least in MP game mode.
Please see this test mission, notice the settings in "multiplayer settings" of Eden Editor and corresponding parameters in description.ext.
[Test-2.VR.zip](https://github.com/Vdauphin/HeartsAndMinds/files/3074386/Test-2.VR.zip)
