### ISSUE TITLE
Suggestion: Recycle objects

### ISSUE THREAD

**Issue by madpat3** [Vdauphin/HeartsAndMinds#666]
Sometimes, you build objects (red box at base), that you didn't want to built.
Or the containers, prevously filled with items, are now empty and useless.
Would be cool, if you could place the object on the helipad and have the ace-interaction to delete it.

**Comment by GoldJohnKing** [comment]
Yeah, it would be great to have a object delete function at logistic point.

**Comment by Vdauphin** [comment]
Hello,
You can use the Zeus interface to delete those objects (limited to admin)
I don't really like this thing because everybody could delete anything so on public server it could be a real issue
Cheers

**Comment by GoldJohnKing** [comment]
> I don't really like this thing because everybody could delete anything so on public server it could be a real issue

Would it be possible to restrict deletions only on those objects spawned by logistic point, or objects in the spawnable list of logistic point?

**Comment by Vdauphin** [comment]
It sound like a good compromise then (`btc_log_obj_created`)

**Comment by GoldJohnKing** [comment]
Another possibly related issue:
Now, players can respawn any wreck at logistic point, which means players can acquire enemy vehicles if they want, or duplicate btc_helos before it's wreck disappeared. I suggest adding a function to check if it's a btc_veh to avoid above issue.

**Comment by madpat3** [comment]
> Another possibly related issue:
> Now, players can respawn any wreck at logistic point, which means players can acquire enemy vehicles if they want, or duplicate btc_helos before it's wreck disappeared. I suggest adding a function to check if it's a btc_veh to avoid above issue.

![20190415221835_1](https://user-images.githubusercontent.com/15272840/56162773-0f3b7500-5fcd-11e9-8f16-36951c084ec3.jpg)
