### ISSUE TITLE
Cargo is empty after server restart

### ISSUE THREAD

**Issue by madpat3** [Vdauphin/HeartsAndMinds#667]
**Arma 3 Version:** `1.90` (stable)
**CBA Version:** `3.10.1` (stable)
**ACE3 Version:** `3.12.6` (stable)
**Hearts and minds Version:** `1.19.3` (stable)

**Mods:**
```
- CBA_A3
- ace
- BW-Mod
- BWA3 Add (https://steamcommunity.com/sharedfiles/filedetails/?id=1326881314)
- GM: Demo
- Hafm Choppers
- SFPBo105
```
**Description:**
- The object you loaded into an e.g container, are gone after mission/server restart. 

**Steps to reproduce:**
- Build a container at logi-point. Place it next to the helipad. now build several objects and load them into the container. Save the progress and restart the mission. Now check the cargo of the container.

**Add mission file:**
- [=BTC=co@30_Hearts_and_Minds_Bw4.Altis.zip](https://github.com/Vdauphin/HeartsAndMinds/files/3066599/BTC.co%4030_Hearts_and_Minds_Bw4.Altis.zip).

**RPT log file:**
- https://www.dropbox.com/s/0u8ecxkub8e0qc0/arma3server_2_2019-04-10_21-32-26.rpt?dl=0.

**Comment by Vdauphin** [comment]
Hello,
Can you fill the issue template ?
See you soon

**Comment by GoldJohnKing** [comment]
What he said seems to mean that "ACE Cargo" of a vehicle or container is not saved and restored on mission restart.

**Comment by madpat3** [comment]
yes, that's what i meant.

**Comment by Vdauphin** [comment]
And it works for me...
I will check the mission file and RPT soon

**Comment by Vdauphin** [comment]
I launched your mission file and container contents are saved.

**Comment by madpat3** [comment]
hmm?!!

**Comment by madpat3** [comment]
did you check it on dedicated?

**Comment by madpat3** [comment]
just checked it again. now it works. 
maybe got something to do with how long the server is running.?

well, that's Arma XD

**Comment by Vdauphin** [comment]
Does is it work finally?

**Comment by madpat3** [comment]
now it stacks items like wheels and chains XD

**Comment by Vdauphin** [comment]
You need to disable in ACE setting from your server the system which add automatically wheels or chains (this is disable by default in the H&M ACE setting mission)
