### ISSUE TITLE
[Question]"btc_fnc_side_capture_officer" mission use civilian vehicles and dont check vehicles capacity, cause AI walk all the way.

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#668]
**Arma 3 Version:** `1.90` (stable)
**Hearts and minds Version:** `1.19.3` (stable)

**Description:**
- "btc_fnc_side_capture_officer" mission use civilian vehicles and dont check vehicles capacity, cause AI walk all the way.
- This happens both with vallina or modded civilian factions, especially on Vans without windows. 
- Please see the picture below:
![107410_20190416171422_1](https://user-images.githubusercontent.com/26923626/56202193-13bb6880-6075-11e9-83d9-127f6a6e96fa.png)
![107410_20190416171431_1](https://user-images.githubusercontent.com/26923626/56202196-1453ff00-6075-11e9-9d2c-b7f29c9d43d1.png)

**Steps to reproduce:**
- Spawn the "btc_fnc_side_capture_officer" mission for several times, until you this happens.

**Comment by Vdauphin** [comment]
Hello,
BI fault : https://feedback.bistudio.com/T129141
Cheers

**Comment by GoldJohnKing** [comment]
Okay... BI fault again...
And this does not only happens on vans, but also happens on many other types of vehicles, like some RHS vehicles and RDS Civilian vehicles.
So would there be some way to exclude those vehicles from civilian vehicle's list, or some methods to manually prevent it temporarily?

**Comment by Vdauphin** [comment]
> And this does not only happens on vans, but also happens on many other types of vehicles, like some RHS vehicles and RDS Civilian vehicles.

Ask to the author to fix those vehicles
The testing code is in the BI feedback

> So would there be some way to exclude those vehicles from civilian vehicle's list, or some methods to manually prevent it temporarily?

Yes, just remove them from the list of available vehicle (https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L499-L520)

**Comment by GoldJohnKing** [comment]
Urr... "btc_fnc_side_capture_officer" mission uses civilian vehicles, but the avaliable vehicles list is for enemy factions, how could I change it of civilian side?

**Comment by Vdauphin** [comment]
> Urr... "btc_fnc_side_capture_officer" mission uses civilian vehicles, but the avaliable vehicles list is for enemy factions, how could I change it of civilian side?

Use the same template, here is the variable: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L239

**Comment by GoldJohnKing** [comment]
Yep, got that, thanks a lot.
Cheers
