### ISSUE TITLE
[Feature Request]Add vehicle type check on respawn wreck function at logistics point (btc_create_object_point)

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#669]
**Arma 3 Version:** `1.90` (stable)
**Hearts and minds Version:** `1.19.3` (stable)

**Description:**
- Currently players can respawn any types of wreck at logistics points, not just btc_veh. Players can duplicate huge amounts of respawnable vehicles (btc_helo), or respawn all kinds of enemy vehicles and put them into use.
- This seems also cause problems when non-btc_veh respawned, game process saved and loaded, some btc_veh seems not having map markers when they are destroyed, some may even just lost after server restart (though I'm not sure).
- I think adding a function of vehicle type check on respawn wreck function at logistics point (btc_create_object_point).

**Comment by Vdauphin** [comment]
Hello,
> Currently players can respawn any types of wreck at logistics points, not just btc_veh. Players can  respawn all kinds of enemy vehicles and put them into use.

This is a feature, people like capture vehicle from enemies

> Players can duplicate huge amounts of respawnable vehicles (btc_helo),

The vehicle respawn very quickly (30s), how could they have time to move them to the logistic point and repair it to duplicate ?

>  This seems also cause problems when non-btc_veh respawned, game process saved and loaded, some btc_veh seems not having map markers when they are destroyed, some may even just lost after server restart (though I'm not sure).

Strange, there are inside the H&M system so they should have the exact same behavior
Cheers

**Comment by GoldJohnKing** [comment]
> The vehicle respawn very quickly (30s), how could they have time to move them to the logistic point and repair it to duplicate?

They destroy it just at the respawn point then respawn it... I used to wonder how they did it, too... So at least ban the btc_helos' respawn is needed.

> Strange, there are inside the H&M system so they should have the exact same behavior.

According to my observation, those strange things only happen if players respawn enemy wrecks then the next time mission is loaded, and those strange things not only happens on captured enermy vehicles, but also on original btc_vehs, though I do not have certain proof.
Players respawn enemy wrecks -> Mission saved -> Mission loaded -> Strange things happen

**Comment by GoldJohnKing** [comment]
Hi, I've see the commit of FIX-wreck_helo branch, the Simplified Chinese translation is:
此残骸将会重生

I'll run the change on my server and test it recently.

Cheers

**Comment by GoldJohnKing** [comment]
Hi, I've run the test and this commit works well on my server.

**Comment by GoldJohnKing** [comment]
Fixed by https://github.com/Vdauphin/HeartsAndMinds/pull/670 .
