### ISSUE TITLE
QUESTION How to set the AI to refresh when the region is activated

### ISSUE THREAD

**Issue by teemo0803** [Vdauphin/HeartsAndMinds#676]
![6PN~KYY(QA N MX@EBH}`LX](https://user-images.githubusercontent.com/49296645/57121396-d4e21e00-6da9-11e9-9405-6e3be51d6d70.png)
Too many AIs where there are no players, resulting in very low server frames

**Comment by teemo0803** [comment]
Now,we are using the Map-Lythium the frames enven lower

**Comment by Vdauphin** [comment]
Hello,
Could you fill up the issue template?
I need more information
Cheers

**Comment by teemo0803** [comment]
I FIX THE PROBLEM BY STTEING THE Spawn city radius offset higher


Cheers

**Comment by Vdauphin** [comment]
Hello,
The spawn city radius offset just increase the radius of the trigger detecting players
I don't really see how it could resolve the issue
Cheers

**Comment by teemo0803** [comment]
thanks ive already solve the issue by reedit the mission.


 
---Original---

**Comment by Rinzler2400** [comment]
Any more specific details on how you fixed this? Running into a very similar issue currently and have been unable to really remedy it in any meaningful way.
