### ISSUE TITLE
Suggestion:Garbage delete

### ISSUE THREAD

**Issue by teemo0803** [Vdauphin/HeartsAndMinds#705]
if possible,please add auto garbage clean function to the mission in order to prevent low fps

**Comment by Vdauphin** [comment]
Hello,

There is already a working system (https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/common/clean_up.sqf)

Cheers

**Comment by teemo0803** [comment]
Does this script automatically clean the objects dropped from player?

cheers

**Comment by Vdauphin** [comment]
yes (https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/common/clean_up.sqf#L27)

**Comment by teemo0803** [comment]
it must help a lot

cheers
