### ISSUE TITLE
Suggestion/Support

### ISSUE THREAD

**Issue by danielmjmarques** [Vdauphin/HeartsAndMinds#707]
Olá  Giallustio,

Antes de mais nada quero agradecer pelo ótimo trabalho de criação e atualizações desta missão, nosso grupo joga ela desde as primeiras versões. A tradução para português Brasileiro foi compartilhada por nós através do nosso parceiro @EckoMoire. Pois bem, gostaria de saber como faço para enviar a você a atualização da tradução para PTBR pois encontramos alguns ajustes a serem feitos e também um arquivo da missão (ask_reputation.sqf) que ele está prejudicando a tradução ao perguntar a reputação aos civis. Em todo caso vou deixar aqui o link para download dos arquivos, desculpe postar em português pois meu inglês é péssimo.

Desde já agradeço seu apoio.

ENGLISH VERSION (Google Tradutor - Sorry)
Hello Giallustio,

First of all I want to thank for the great work of creation and updates of this mission, our group plays it from the first versions. The Brazilian Portuguese translation was shared by us through our partner @EckoMoire. Well, I would like to know how I can send you the PTBR translation update as we found some adjustments to be made and also a mission file (ask_reputation.sqf) that it is hurting the translation by asking the reputation of civilians. In any case I will leave here the link to download the files, sorry to post in Portuguese because my English is very bad.

Thank you in advance for your support.

**Comment by danielmjmarques** [comment]
**Previous Code ask_reputation.sqf**

_private _info_type = switch (true) do {
    case (_rep < 200): {localize "STR_BTC_HAM_CON_INFO_ASKREP_VLOW"}; //very low
    case (_rep >= 200 && _rep < 500): {localize "STR_BTC_HAM_CON_INFO_ASKREP_LOW"}; //low
    case (_rep >= 500 && _rep < 750): {toLower localize "str_a3_firing_drills_rule_normal"}; //normal
    case (_rep >= 750): {localize "STR_BTC_HAM_CON_INFO_ASKREP_HIGH"}; //high
};_

Updated Code

private _info_type = switch (true) do {
    case (_rep < 200): {localize "STR_BTC_HAM_CON_INFO_ASKREP_VLOW"}; //very low
    case (_rep >= 200 && _rep < 500): {localize "STR_BTC_HAM_CON_INFO_ASKREP_LOW"}; //low
    case (_rep >= 500 && _rep < 750): {localize "STR_BTC_HAM_CON_INFO_ASKREP_NORMAL"}; //normal
    case (_rep >= 750): {localize "STR_BTC_HAM_CON_INFO_ASKREP_HIGH"}; //high
};

**Comment by danielmjmarques** [comment]
File for Download: http://www.gbat.com.br/Downloads/Hearts And Minds_1.19.5_update.zip

**Comment by Vdauphin** [comment]
Hello,
> Hello Giallustio,

Giallustio does not work on it but you can thanks all contributors: https://github.com/Vdauphin/HeartsAndMinds/graphs/contributors

> Well, I would like to know how I can send you the PTBR translation update 

Just do a Pull Request from the master branch see: http://vdauphin.github.io/HeartsAndMinds/For-developer-and-tester#branches

> (ask_reputation.sqf) that it is hurting the translation by asking the reputation of civilians.

Here is a BI translation, doesn't look that bad actually: 

Language | Text
-- | --
Original | Normal
Chinese | 普通
French | Normal
Spanish | Normal
Italian | Normale
Polish | Normalne
Russian | Обычные
German | Normal
Czech | Normální
English | Normal
Portuguese | Normais
Korean | 보통
Chinesesimp | 正常
Japanese | 通常
Turkish | Normal

Will you do the pull request?

**Comment by danielmjmarques** [comment]
> Hello,
> 
> > Hello Giallustio,
> 
> Giallustio does not work on it but you can thanks all contributors: https://github.com/Vdauphin/HeartsAndMinds/graphs/contributors
> 
> > Well, I would like to know how I can send you the PTBR translation update
> 
> Just do a Pull Request from the master branch see: http://vdauphin.github.io/HeartsAndMinds/For-developer-and-tester#branches
> 
> > (ask_reputation.sqf) that it is hurting the translation by asking the reputation of civilians.
> 
> Here is a BI translation, doesn't look that bad actually:
> 
> Language	Text
> Original	Normal
> Chinese	普通
> French	Normal
> Spanish	Normal
> Italian	Normale
> Polish	Normalne
> Russian	Обычные
> German	Normal
> Czech	Normální
> English	Normal
> Portuguese	Normais
> Korean	보통
> Chinesesimp	正常
> Japanese	通常
> Turkish	Normal
> Will you do the pull request?

Yeah, But the translation BIS for civilian's conversations on the Hearts is wrong. Look

With BIS
English: I think your reputation is normal
Portuguese: Eu acredito que sua reputação é normais

This Correct (Withou BIS):
English: I think your reputation is normal
Portuguese: Eu acredito que sua reputação é normal. (or change normal for BOA ->good)

**Comment by Vdauphin** [comment]
I see, then use: str_3den_display3den_menubar_visionmodenormal_text


Language | Text
-- | --
Original | Normal
English | Normal
Czech | Normální
German | Normal
Russian | Нормальное
Polish | Normalny
Italian | Normale
Spanish | Normal
French | Normale
Chinese | 普通
Japanese | 標準
Korean | 일반
Portuguese | Normal
Chinesesimp | 常规
Turkish | Normal

may be ?

**Comment by danielmjmarques** [comment]
Perfect!

**Comment by Vdauphin** [comment]
Are you working on the pull request?

**Comment by EckoMoire** [comment]
Hello, is the translation problem, only one line?

**Comment by Vdauphin** [comment]
I am guessing not: 
> some adjustment**S** to be made

**Comment by EckoMoire** [comment]
Well, I'll check everything in stringtable and version changelog just to be sure and I'll send you the pull request.

**Comment by danielmjmarques** [comment]
No, i not.

 

I try but not success.

 

Atenciosamente,
﻿
Daniel Marques
Consultoria em Infraestrutura de TI

Site:  <http://www.infraworld.com.br/> http://www.infraworld.com.br
Skype: danielmjmarques
Tel: (47) - 98816-6062
Twitter: @InfraWorldBR
Curta no Página no Facebook:  <http://facebook.com/InfraWorldBrasil> http://facebook.com/InfraWorldBrasil
”Antes de imprimir este documento pense nos custos e no seu compromisso com o meio ambiente”

 

De: Vdauphin [mailto:notifications@github.com] 
Enviada em: quarta-feira, 26 de junho de 2019 11:43
Para: Vdauphin/HeartsAndMinds
Cc: danielmjmarques; Author
Assunto: Re: [Vdauphin/HeartsAndMinds] Suggestion/Support (#707)

 

Are you working on the pull request?

**Comment by EckoMoire** [comment]
My pull request is almost done, before this, I just wanna clarify the 'outcome' of it:

If you ask the civilian about your reputation he will say something like:
> Hey, your reputation is normal (for english players)

and that's fine, nothing changed here.

And then for portuguese players (before the edit):
> Hey, your reputation is commons (plural)

And after the edit:
> Hey, your reputation is normal (for portuguese players)

With the new edit, it _works_ and everyone can understand, not perfect, but Portuguese isn't only for Brazil and so it can't be perfect without confusion.

(Portuguese has some noticeable differences in between Portugal and Brazil)
