### ISSUE TITLE
Suggestion/Support - Multiple Respawns

### ISSUE THREAD

**Issue by nonsindeads** [Vdauphin/HeartsAndMinds#720]
### Suggestion/Support

Was muss ich abaendern wenn ich mehrere Respawn Points haben will. 

```
respawn = "BASE";
respawnDelay = 10;
respawnTemplates[] = {"MenuPosition"};
respawnOnStart = 1;
```

Diese Einstellung funktioniert aktuell nicht. Ich spawne immer wieder an der Stelle an der die AI im Editor plaziert wurde, auch der respawnDelay wird nicht uebernommen.

Danke fuer die Hilfe!

**Comment by Vdauphin** [comment]
Bonjour,

Je ne parle pas votre langue.

Cordialement.
