### ISSUE TITLE
[Suggestion] Add more detailed descriptions to side-mission.

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#752]
**Hearts and minds Version:** `1.19.7` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
```

**Description:**
- I've noticed that the description of side-missions are much too brief for new players to understand what to do.
- For example, the hack mission need to use ACE Interation function to interact with the terminal in order to active the terminal, and keep at least one person in the house or the mission may fail. Besides the description words, adding a picture of the terminal would be even better.
- The second example is the difference among rescue hostage mission, capture enemy office mission and rescue pilot mission. For rescue hostage mission, access to the hostage and release him would finish the mission. But for capture enemy office mission and rescue pilot mission, players need to bring them back to btc_logic_point. This causes many confusion to new players. Besides, most player would think bringing them back to base would finish the mission, but it's actually the actual btc_logic_point. Though I could modify the condition manually, it still cause inconvience to new players. I wonder if changing the mission's finish trigger center to btc_base would be better.
- Another example is repair vehicle mission. Many new players might think bringing a Toolkit would be ok, but they may not realize what they need is a wheel.
- So I suggest add more descriptions to side-missions.

**Comment by Vdauphin** [comment]
This is a [Feature Requests](https://github.com/Vdauphin/HeartsAndMinds/issues/738)

> For example, the hack mission need to use ACE Interation function to interact with the terminal in order to active the terminal, and keep at least one person in the house or the mission may fail. Besides the description words, adding a picture of the terminal would be even better.

Already done for the next major release see https://github.com/Vdauphin/HeartsAndMinds/pull/689

> The second example is the difference among rescue hostage mission, capture enemy office mission and rescue pilot mission. For rescue hostage mission, access to the hostage and release him would finish the mission. But for capture enemy office mission and rescue pilot mission, players need to bring them back to btc_logic_point. This causes many confusion to new players. 

This is intended, the idea is that player need to read and understand carefully the objective. This will be way more intuitive in the next release as you will have subtasks for each step 

> Besides, most player would think bringing them back to base would finish the mission, but it's actually the actual btc_logic_point. Though I could modify the condition manually, it still cause inconvience to new players. I wonder if changing the mission's finish trigger center to btc_base would be better.

I notice btc_logic_point is never changed by mission maker but btc_base is removed (for the flag they want). So here it is more. In the next major released you will have a picture of the helipad from btc_logic_point

> Another example is repair vehicle mission. Many new players might think bringing a Toolkit would be ok, but they may not realize what they need is a wheel.

A vehicle with a missing wheel doesn't need repair? :p 

I would suggest you to test (not on your dedicated, really unstable right now) the master-daily and give me feedback if you want to
