### ISSUE TITLE
[BUG] Side-mission "btc_fnc_side_kill" wont fail if the body carrying the dog tag is deleted

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#757]
**Arma 3 Version:** `1.94` (stable)
**CBA Version:** `3.12.0` (stable)
**ACE3 Version:** `3.12.6` (stable)
**RHS USAF Version:** `0.4.9` (stable)
**Hearts and minds Version:** `master_daily branch` (commit e6832f8)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
```

**Description:**
- I've been playing the master_daily for a while, and I found a problem about side-mission "btc_fnc_side_kill".
- If the dog tag was deleted, the mission wont fail and will last forever.
- There's many situation causing dog tag being deleted:
1. The officer or his body deleted by zeus manually.
2. The officer's body deleted by garbage collecting system (for example, a mod named AGC).
2. The player's body who is carrying the dog tag was deleted, such as disconnect from the server (ACE will automatically delete the player's body on disconnect).
(Unexpected things always happens...)
- I think it would be better if the task is automatically canceled if the dog tag was disappeared or player who's carrying it was dead and no other player is close to him.

**Steps to reproduce:**
Just provide the easiest way to reproduce the issue:
- Spawn the mission "btc_fnc_side_kill".
- Automatically delete the target on zeus.
- The dog tag wont return base forever so the mission will last forever.

**Comment by Vdauphin** [comment]
> The officer or his body deleted by zeus manually.

The Zeus isn't suppose to delete a body used by player to complete a mission...

> the officer's body deleted by garbage collecting system (for example, a mod named AGC).

Do you know there is already a H&M system removing safely body, weapons, veh?

> The player's body who is carrying the dog tag was deleted, such as disconnect from the server (ACE will automatically delete the player's body on disconnect).

That's true

I will fix it as much as I can

Thanks for the feedback!

**Comment by GoldJohnKing** [comment]
> The Zeus isn't suppose to delete a body used by player to complete a mission...

> Do you know there is already a H&M system removing safely body, weapons, veh?

Yep, I get that. I'm just providing likely-happen situations... As I said above, though not expected, unexpected things always happen... 😅

**Comment by GoldJohnKing** [comment]
Another question:
What if the dog tag is dropped on the ground by a player then garbage collected by btc system or deleted by zues accidentally? Or the player who's carrying the dog tag is dead and it's body being garbage collected? Does the commit include these two situations?

**Comment by Vdauphin** [comment]
Nop :p

**Comment by GoldJohnKing** [comment]
Another situation:
Player put the dog tag in a vehicle then the vegicle exploded.
I think we'd better find a way to relate the mission condition directly to the dog tag itself, instead of who's carrying it.

**Comment by Vdauphin** [comment]
> I think we'd better find a way to relate the mission condition directly to the dog tag itself

You can't, dog tag is just a string
