### ISSUE TITLE
[BUG]Helicopters can not sling load some vehicles.  

### ISSUE THREAD

**Issue by Sparta01** [Vdauphin/HeartsAndMinds#769]
Arma 3 Version:1.94.145977
CBA Version: 3.12.2 (stable)
ACE3 Version: 3.12.6 (stable)
Hearts and minds Version: 1.19.2

Mods:

- CBA_A3
- ace

Description:
I found that helicopters can not sling load some kinds of vehicles such as wreck and truck.

**Comment by Vdauphin** [comment]
Hello,
Please update your mission
This has been fix https://github.com/Vdauphin/HeartsAndMinds/pull/761
Cheers

**Comment by Sparta01** [comment]
Roger that,let me try
