### ISSUE TITLE
P3D ERROR

### ISSUE THREAD

**Issue by teemo0803** [Vdauphin/HeartsAndMinds#776]
CHEMICAL WARFARE P3D FILE ERROR
![TIM图片20191020094307](https://user-images.githubusercontent.com/49296645/67153556-0e89ef80-f31e-11e9-84ca-7edb122d6552.png)

**Comment by Vdauphin** [comment]
Hello,

You need 1.96 (https://github.com/Vdauphin/HeartsAndMinds/pull/771#issue-320000482)

Cheers
