### ISSUE TITLE
Headless Client Not Loaded

### ISSUE THREAD

**Issue by teemo0803** [Vdauphin/HeartsAndMinds#813]
![`Y8% QD8ODU3KEX@A@Y852L](https://user-images.githubusercontent.com/49296645/73149601-12879380-40fd-11ea-83e5-f9fa34002bd0.png)
![{_TM)6U~H7H ({F97%(%@V2](https://user-images.githubusercontent.com/49296645/73149605-13b8c080-40fd-11ea-9f1a-fdb3c54178c4.png)
![M)P4H@$@ )6N0PMX~ZLEB}5](https://user-images.githubusercontent.com/49296645/73149606-15828400-40fd-11ea-8eae-f85a1d1a7eea.png)
![O@L$@%L~`FOW1NLZPS~TDIV](https://user-images.githubusercontent.com/49296645/73149607-161b1a80-40fd-11ea-8953-b7e7289b0a0c.png)
![UR_D9X1RICS23 C4F~C_V09](https://user-images.githubusercontent.com/49296645/73149608-16b3b100-40fd-11ea-8ef2-a4c22d79e79c.png)

**Comment by teemo0803** [comment]
![`Y8% QD8ODU3KEX@A@Y852L](https://user-images.githubusercontent.com/49296645/73149639-3e0a7e00-40fd-11ea-8bf4-3ab864fabb93.png)

**Comment by teemo0803** [comment]
![M)P4H@$@ )6N0PMX~ZLEB}5](https://user-images.githubusercontent.com/49296645/73149643-42cf3200-40fd-11ea-9b01-d82f371b451e.png)
![{_TM)6U~H7H ({F97%(%@V2](https://user-images.githubusercontent.com/49296645/73149644-4367c880-40fd-11ea-9a94-6704aeae85a0.png)

**Comment by teemo0803** [comment]
i tried the same para and apply it to <KP Liberation> AND IT WORKS

**Comment by teemo0803** [comment]
when i applied it to hearts and minds, the headless client is always not loaded

**Comment by teemo0803** [comment]
Thanks xD

**Comment by Vdauphin** [comment]
fill the issue template
