### ISSUE TITLE
 Error in expression

### ISSUE THREAD

**Issue by jus61** [Vdauphin/HeartsAndMinds#817]
(Use English only.)

`19:45:59 Error in expression <; 
private _allclasse = [[_p_civ]] call btc_fnc_civ_class; 
btc_civ_type_units>
19:45:59   Error position: <btc_fnc_civ_class; 
btc_civ_type_units>
19:45:59   Error Undefined variable in expression: btc_fnc_civ_class
19:45:59 File mpmissions\__cur_mp.Enoch\core\def\mission.sqf..., line 321
19:46:00 Error in expression <er_side)
)
});
([_rearming_static] call btc_fnc_find_veh_with_turret) params ["_>
19:46:00   Error position: <btc_fnc_find_veh_with_turret) params ["_>
19:46:00   Error Undefined variable in expression: btc_fnc_find_veh_with_turret
19:46:00 File mpmissions\__cur_mp.Enoch\core\def\mission.sqf..., line 389
19:46:00 Error in expression <F"
],
[
"ACE_Wheel",
"ACE_Track"
]
] + _rearming_magazines
];
publicVariable "b>
19:46:00   Error position: <_rearming_magazines
];
publicVariable "b>
19:46:00   Error Undefined variable in expression: _rearming_magazines
19:46:00 File mpmissions\__cur_mp.Enoch\core\def\mission.sqf..., line 458
19:46:00 Error in expression <array select 1;
btc_log_def_loadable = (_c_array select 0) + (_c_array select 1)>
19:46:00   Error position: <_c_array select 0) + (_c_array select 1)>
19:46:00   Error Undefined variable in expression: _c_array
19:46:00 File mpmissions\__cur_mp.Enoch\core\def\mission.sqf..., line 465

 `

**Arma 3 Version:** `NEUW` (stable )
**CBA Version:** `NEUW` (stable )
**ACE3 Version:** `NEUW` (stable )
**RHS USAF Version:** -----
**Hearts and minds Version:** `1.20` (stable )

**Mods:**
```
- @CBA
- @ace
- @TFAR
- @CFP
- @CUP_Units
- @CUP_Vehicles
- @CUP_Weapons
- @CFP
- @MLO_All_In_One
- @NIArms_All
- @NIArms_All
- @NIArms_All_ACE_C
- @BWMod;@ReddnTank
- @BW_Kleidera
- @T_BW_Retex
- @BWMod_ACE
- @BackpackOnChest
- @Movement
- @ADV_ACE_CPR
- @CFP_ReddnTank

```

**Description:**
- RPT Log.

**Steps to reproduce:**
- Server Start 

**Add mission file:**
[Hearts_and_Minds1.Enoch.zip](https://github.com/Vdauphin/HeartsAndMinds/files/4239797/Hearts_and_Minds1.Enoch.zip)

**RPT log file:**
- https://pastebin.com/GqREK6jn

**Comment by Vdauphin** [comment]
Hello,

Fix this warning before: 19:45:43 Warning Message: Config : some input after EndOfFile.

Cheers

**Comment by Vdauphin** [comment]
Check your description.ext you added an extra `};` line 36.
Remove it and your modification should works.

**Comment by jus61** [comment]
THX
