### ISSUE TITLE
ace Vehicle Lock

### ISSUE THREAD

**Issue by jus61** [Vdauphin/HeartsAndMinds#819]
We use the Vcom AI and she steals our vehicles every time.
How do I add the car keys to the ACE arsenal 

Parameter:
Type of the arsenal: 4
Restricted arsenal (See /define_mod.sqf): 3

**Comment by Vdauphin** [comment]
Hello,
I don't know, never use that
Ask this to the ACE Team
Cheers

**Comment by jus61** [comment]
The standard ACE arsenal includes the vehicle keys.
Not with H&M

**Comment by Vdauphin** [comment]
Can you share a mission with the standard ACE arsenal containing vehicle keys?

**Comment by jus61** [comment]
I was just told that this function was disabled before 2 or 3 updates !
Can you tell me how I can add an Itam ["ace_key_west]; to the arsenal ?

Sorry me English ;)

**Comment by Vdauphin** [comment]
> I was just told that this function was disabled before 2 or 3 updates !

I didn't disable this... This is a feature from ACE may be it is just a bug from ACE Arsenal not displaying keys. You should ask to ACE

Use https://ace3mod.com/wiki/framework/arsenal-framework.html#11-adding-virtual-items
So your `"ace_key_west"` should be use like that:
`[btc_gear_object, ["ace_key_west"]] call ace_arsenal_fnc_addVirtualItems;`

Add it [/core/init_player.sqf#L1](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/init_player.sqf#L1) at the first line. Then you will see that H&M doesn't remove it at all even added before H&M loaded player side.

**Comment by jus61** [comment]
THX 

> [btc_gear_object, ["ace_key_west"]] call ace_arsenal_fnc_addVirtualItems;

Add it /core/init_player.sqf#L1 at the first line. Then you will see that H&M doesn't remove it at all even added before H&M loaded player side.
