### ISSUE TITLE
helicopters insert 

### ISSUE THREAD

**Issue by jus61** [Vdauphin/HeartsAndMinds#820]
I have been trying to insert helicopters for the enemies but they do not appear!
Can you tell me if I did the right thing?

        case "OPF_G_F" : {
        btc_type_motorized = btc_type_motorized + ["I_Truck_02_transport_F", "I_Truck_02_covered_F"];
        btc_type_motorized_armed = btc_type_motorized_armed + ["CUP_AirVehicles_UH1H", "CFP_B_KEARMY"];
    };
    case "IND_C_F" : {
        btc_type_motorized = btc_type_motorized + ["I_G_Offroad_01_repair_F", "I_G_Offroad_01_F", "I_G_Quadbike_01_F", "I_G_Van_01_fuel_F", "I_Truck_02_transport_F", "I_Truck_02_covered_F"];
        btc_type_motorized_armed = btc_type_motorized_armed + ["CUP_AirVehicles_UH1H", "I_G_Offroad_01_F"];
        btc_type_units = btc_type_units - ["I_C_Soldier_Camo_F"];
    };

**Comment by Vdauphin** [comment]
Hello,
The `btc_type_motorized_armed` is only use if the Add armed vehicles in Side mission/Cache mission parameter is true
Cheers

**Comment by jus61** [comment]
Yes that is also active

class btc_p_AA { // Anti-Air infantry:
        title = __EVAL(format ["      %1", localize "STR_BTC_HAM_PARAM_FAC_EAA"]);
        values[]={0,1};
        texts[]={$STR_DISABLED,$STR_ENABLED};
        default = 1;
    };
    class btc_p_tank { // Enemy uses Tank:
        title = __EVAL(format ["      %1", localize "STR_BTC_HAM_PARAM_FAC_ETANK"]);
        values[]={0,1};
        texts[]={$STR_DISABLED,$STR_ENABLED};
        default = 1;
    };

**Comment by Vdauphin** [comment]
> class btc_p_AA { // Anti-Air infantry:
> title = __EVAL(format [" %1", localize "STR_BTC_HAM_PARAM_FAC_EAA"]);
> values[]={0,1};
> texts[]={$STR_DISABLED,$STR_ENABLED};
> default = 1;
> };
> class btc_p_tank { // Enemy uses Tank:
> title = __EVAL(format [" %1", localize "STR_BTC_HAM_PARAM_FAC_ETANK"]);
> values[]={0,1};
> texts[]={$STR_DISABLED,$STR_ENABLED};
> default = 1;
> };

This isn't the mission parameter I am talkng about:
This one: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/param.hpp#L104-L108

**Comment by jus61** [comment]
`    class btc_p_veh_armed_ho { // Add armed vehicles in Hideout:
        title = __EVAL(format ["      %1", localize "STR_BTC_HAM_PARAM_SPAWN_ARMEDHIDEOUT"]);
        values[] = {0,1};
        texts[] = {$STR_DISABLED,$STR_ENABLED};
        default = 1;
    };
    class btc_p_veh_armed_spawn_more { // Add armed vehicles in Side mission/Cache:
        title = __EVAL(format ["      %1", localize "STR_BTC_HAM_PARAM_SPAWN_ARMEDOTHER"]);
        values[] = {0,1};
        texts[] = {$STR_DISABLED,$STR_ENABLED};
        default = 1;
    };
`
My mistake while copying sorry! Yes this is enabled

**Comment by Vdauphin** [comment]
Then the `_p_en` doesn't contain the faction you expect.
add a line outside the `switch` `case` to log what is in the `_p_en`
`diag_log str(_p_en);`
Then check your log

**Comment by Vdauphin** [comment]
> Enemy type is 35 "CFP Drew: Islamic State (Side: GUER)",

This is not the "OPF_G_F" or "IND_C_F" faction

**Comment by jus61** [comment]
case "CFP_O_IS" : {
        btc_type_motorized = btc_type_motorized + ["I_Truck_02_transport_F", "I_Truck_02_covered_F"];
        btc_type_motorized_armed = btc_type_motorized_armed + ["CUP_AirVehicles_UH1H", "CFP_B_KEARMY"];
    };

**Comment by Vdauphin** [comment]
This looks okay

**Comment by jus61** [comment]
did not work

**Comment by Vdauphin** [comment]
Check if `"CUP_AirVehicles_UH1H" in btc_type_motorized_armed`
