### ISSUE TITLE
Headlessclient Not Loaded

### ISSUE THREAD

**Issue by teemo0803** [Vdauphin/HeartsAndMinds#828]
(Use English only.)

**ALL MODS ARE LATEST IN WORKSHOP** `latest` (stable)

**Hearts and minds Version:** `1.20.2` (stable)

**Mods:**
```
@ace;@ACEX;@ACE Compat - RHS United States Armed Forces;@CBA_A3;@Project OPFOR;@RHSAFRF;@RHSGREF;@RHSUSAF;@Specialist Military Arms (SMA) Version 2.7.1;@Task Force Arrowhead Radio (BETA!!!);@MLO All-In-One Collection;@CUP Terrains - Core;@CUP Terrains - Maps;@ACE Compat - RHS GREF;@PTS_FLIGHT;@PTS_PLUGIN;@3CB BAF Equipment;@3CB BAF Weapons;@RKSL Studios Attachments v3.01;@ACE Compat - RHS Armed Forces of the Russian Federation
```

**Description:**
the headless client is succcessfully loaded when i using altis,but when i change to takistan,the headless client is not loaded
**Steps to reproduce:**
i loaded and unloaded acex to check the problem if caused by acex but it proved not
also i unloaded all mods except ace cba acex rhsusaf rhsafrf rhsgref same thing happend

**Add mission file:**
- 
[=BTC=co@30_Hearts_and_Minds_RHSUS.Takistan.zip](https://github.com/Vdauphin/HeartsAndMinds/files/4412694/BTC.co%4030_Hearts_and_Minds_RHSUS.Takistan.zip)

**RPT log file:**
no crash

**Comment by Vdauphin** [comment]
Please, fill the issue template

> the headless client is succcessfully loaded when i using altis,

The issue is from your side then
