### ISSUE TITLE
change the radiation detector device ?

### ISSUE THREAD

**Issue by canprod** [Vdauphin/HeartsAndMinds#831]
Hello again,

Can we change the tool to detect radiation and where is the file to change it ?

**Comment by Vdauphin** [comment]
Sadly this isn't possible, you need to rewrite specifically to your detector (
Here is where it is handle: 
https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/chem/ehDetector.sqf
https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/chem/updateDetector.sqf

**Comment by canprod** [comment]
ok thanks for the reply
