### ISSUE TITLE
Problem loading Saves

### ISSUE THREAD

**Issue by ECHO-4193** [Vdauphin/HeartsAndMinds#832]
Hello,

My mate Canpr0d contacted you yesturday for some issues on our server.
I am currently trying to fix it but have no Idea how to. 
The problem is : As we first launch, things work prety well. we can play without any trouble (almost). However, as we shutdown the server, and relaunch it, it takes ages to load the previous saved game. When it does, all vehicules on the map glich with themself (two vehicules spawn at the same place : The vehicule I placed on the Editor, and, the vehicule saved by the latest save). I let you guess what happens next. 

My english isnt too good, and i'd rather discuss problems on discord or teamspeak if you can.

There is our  TS3 : ts13.verygames.net:51250

Thanks in advance. 

JOHN

**Comment by Vdauphin** [comment]
Hello,

I see your mistakes
Are you french ?

Cheers

**Comment by ECHO-4193** [comment]
[arma3server_x64_2020-04-09_23-24-06.txt](https://github.com/Vdauphin/HeartsAndMinds/files/4461477/arma3server_x64_2020-04-09_23-24-06.txt)

**Comment by ECHO-4193** [comment]
Hello, yes I am. Is my english that bad? :p

**Comment by Vdauphin** [comment]
> Hello, yes I am. Is my english that bad? :p

Not at all ;) just guessing
Your project name is "Projet" which sound french ^^

**Comment by ECHO-4193** [comment]
well we have a remake of Sherlock Holms here ;)
