### ISSUE TITLE
Vehicles Duplicating on MIssion Reload and questions

### ISSUE THREAD

**Issue by 4idChurch** [Vdauphin/HeartsAndMinds#855]
(Use English only.)

## Before reporting

If you have found an issue with Hearts and Minds please make sure that Hearts and Minds really is the cause of the problem. To do this try to reproduce the issue with using only `@CBA_A3`, `@ace` and `@RHSUSAF` on a stable and unchanged Hearts and minds available [here](https://github.com/Vdauphin/HeartsAndMinds/releases) on a dedicated server.

**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)
**RHS USAF Version:** `0.x.x` (stable / dev + commit hash)
**Hearts and minds Version:** `1.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF

[rpt file.zip](https://github.com/Vdauphin/HeartsAndMinds/files/4536673/rpt.file.zip)


```

**Description:**
Hello, I am having an issue where when my server attempts to load a save mission after a restart . It seems that the vehicles are being loaded from the mission, and then being loaded by the map itself. This is causing them to spawn inside of each other and massive explosions. This has made it impossible for progress to be saved. I have made no modifications to the mission file aside from changing the vehicles to RHS. 

On an unrelated note, I would like to add RHS static weapons to the logic point, how could I do this? 

Also, is there anyway that I could also have the position of the player saved and it load the players back in with their load-outs and positioning? 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
- Add screenshots by drag and drop it here.
1. Load the mission (This should work with Vanilla, but I have attached my mission file) and save it. 
2. Load the server again and set it to load the save. The vehicles all explode from duplication. 

**Add mission file:**
- Zip your .pbo mission file, drag and drop it here.
[mission.zip](https://github.com/Vdauphin/HeartsAndMinds/files/4536652/mission.zip)

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and server RPT file (you can also change the file extension to a .txt file and drag and drop it here). An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

[rpt file.zip](https://github.com/Vdauphin/HeartsAndMinds/files/4536677/rpt.file.zip)

**Comment by Vdauphin** [comment]
Hello,
Your server complain line 32188 that `btc_veh_9` is undefined. I am guessing you don't know there is a 9 after the 8 and before 10.

> On an unrelated note, I would like to add RHS static weapons to the logic point, how could I do this?

They should appear automatically normally. If not:
Add your class name here: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L382

> Also, is there anyway that I could also have the position of the player saved and it load the players back in with their load-outs and positioning?

No, we also need to save medical player statue which is not possible.

Have fun!

**Comment by 4idChurch** [comment]
That was the issue. Thank you for the help!

**Comment by 4idChurch** [comment]
Hi, it actually was working the first time but I'm not sure if I did something wrong to cause it again.  If you happen to have a moment would you mind taking a look again? I'm not seeing another undefined variable in the server logs. I appreciate your help!

[rpt file.zip](https://github.com/Vdauphin/HeartsAndMinds/files/4537233/rpt.file.zip)

**Comment by Vdauphin** [comment]
The rpt is full of errors. I don't see where your mistake is but I see error from your mod list. You should start again and pay attention to each error appearing in your rpt and resolve them as I did. You can also allow `-showScriptErrors` in arma, turn on the debug from mission parameter and start the game in a mpmission for quick test

If you want to add new vehicle see this: http://vdauphin.github.io/HeartsAndMinds/Add-vehicle-or-boat-to-H&M-system 

Good luck!
