### ISSUE TITLE
ThingX recently errors

### ISSUE THREAD

**Issue by valdirsegadas** [Vdauphin/HeartsAndMinds#861]
Hello, recently i got to meny errors on my server.
Like this line:

> 22:34:46 ThingX 2861f286b00# 2666349: canopener_f.p3d was falling under terrain! Position corrected to ground [10.44, -21.95, 0.55]. Disable simulation to keep object under terrain.

And I don't know why that kind of error is happening, the same thing hasn't happened before.
I know there are many mod errors, but now my server is consuming a lot of memory like 5400Mb of RAM, does anyone know why this happens?

[arma3server_x64_2020-04-26_14-40-56.zip](https://github.com/Vdauphin/HeartsAndMinds/files/4562224/arma3server_x64_2020-04-26_14-40-56.zip)

**Comment by Vdauphin** [comment]
Hello,

I don't know, never saw that
What does this command return when it is executed locally in the debug console:
```sqf
underGroundObjects =(allMissionObjects "All") select {!(isObjectHidden _x) && (getpos _x) select 2 < -5};
```

Cheers

**Comment by valdirsegadas** [comment]
Almost find the problem...a modpack i build recently, someone inside couses the bug.
