### ISSUE TITLE
No way to talk to civilians

### ISSUE THREAD

**Issue by Grim5667** [Vdauphin/HeartsAndMinds#869]
**Description:**
- There's no way for the interpreter to talk to civilians, the ace interaction doesn't show.

**Steps to reproduce:**
- Don't know how
- 
![unknown](https://user-images.githubusercontent.com/39709033/81481256-9ab22480-9226-11ea-8db5-f26ae1efa84e.png)

[=BTC=co@30_Hearts_and_Minds_RHSUS_v4.Tanoa.zip](https://github.com/Vdauphin/HeartsAndMinds/files/4604222/BTC.co%4030_Hearts_and_Minds_RHSUS_v4.Tanoa.zip)

**RPT log file:**

[Untitled-2.txt](https://github.com/Vdauphin/HeartsAndMinds/files/4604225/Untitled-2.txt)

**Comment by Vdauphin** [comment]
Hello,
Please select `1 - Bohemia Interactive: Civils (Side: CIV)` in mission parameters for `Civil type:` and `Civil vehicle type:` if you want to play with BI civilians
Cheers

**Comment by Grim5667** [comment]
> Hello,
> Please select `1 - Bohemia Interactive: Civils (Side: CIV)` in mission parameters for `Civil type:` and `Civil vehicle type:` if you want to play with BI civilians
> Cheers

still not working

**Comment by Vdauphin** [comment]
It is working for me.

**Comment by Grim5667** [comment]
Ah nvm, I was stupid, thank you
