### ISSUE TITLE
Civ pop and interaction

### ISSUE THREAD

**Issue by EmperorJosh** [Vdauphin/HeartsAndMinds#875]
First off, thanks for keeping this mission alive, it's fun and simple. My two questions revolve around civilians. Firstly, the civilian population is very lax or not existent, I've mostly only seen them populate in cars and even then, its one or two a town. Is there a way to increase this?
Secondly, everyone we interact doesn't understand us, is there an interpreter option we are missing or are we just unlucky?
Thanks for your time and again thanks for keeping this mission going.

**Comment by Vdauphin** [comment]
Hello,

> Is there a way to increase this?

The number is random but you can above 100% here: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/param.hpp#L90

> is there an interpreter option we are missing or are we just unlucky?

There is an interpreter slot: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/mission.sqm#L1060

Cheers

**Comment by EmperorJosh** [comment]
Thank you for your reply! Gtreat info! Now to increase it over 100, do I just increase the default line or also add it to the values and the text?

Also, can I copy over  "this setVariable [""interpreter"",true]" to other units to make them all interpreters? I play with a small group and not having it an option to assign or train as a terp makes life difficult for us, I see the benefit of limiting the role for larger groups. 
Also, I can't tell which unit the interpreter is on the role selection list, I assume the 3rd slot down. 

Thank you!

**Comment by Vdauphin** [comment]
> Thank you for your reply! Gtreat info! Now to increase it over 100, do I just increase the default line or also add it to the values and the text?

I don't think it is necessary but you can do both

> can I copy over "this setVariable [""interpreter"",true]" to other units to make them all interpreters? 

Yes, personally I choose the medic

> Also, I can't tell which unit the interpreter is on the role selection list, I assume the 3rd slot down.

![20200519124338_1](https://user-images.githubusercontent.com/14364400/82317393-772d6d80-99ce-11ea-8130-f005f7a263b6.jpg)

**Comment by EmperorJosh** [comment]
Ahh see that is where I had the issue, for some reason I don't have the labels. 

![image](https://user-images.githubusercontent.com/65570225/82317791-b2ef1580-9983-11ea-98ca-8ab59ba79095.png)


Thanks for clearing all this up though! I don't think I have any further questions! Thanks for your time!
