### ISSUE TITLE
Unable to detect IED's?

### ISSUE THREAD

**Issue by dundonator** [Vdauphin/HeartsAndMinds#877]
Hello, I am using the latest version of ACE3, latest version of RHS, and your latest version of HAM. I for some reason am unable to detect IED's of any kind. I am am playing as an engineer (ACE engineer that is_, and tried using hte VMM3 and the VMMH3. I am ensuring the mine detector is in fact on. They blow up when I am this close (see image). I am unsure if I am doing it wrong, or if perhaps the new RHS update could have caused this?
![image](https://user-images.githubusercontent.com/28844187/82542060-36d10b00-9b06-11ea-82e4-f6d25504d881.png)

**Comment by Vdauphin** [comment]
Hello,
> They blow up when I am this close (see image).

See http://vdauphin.github.io/HeartsAndMinds/InGame-documentation#ied
Cheers

**Comment by dundonator** [comment]
Unfortunately I have been doing this the past few hours and i am unable to detect them. I am aware of how to use the ACE mine detectors but I am having no luck.

**Comment by Vdauphin** [comment]
>  approach it carefully (DO NOT rotate while you are walking: prefer walk, stop, rotate, walk again etc).

**Comment by dundonator** [comment]
Yes I understand the concept of it. I am not receiving any audio detection from the mine detector, and visually can't identify an IED (looked around it in Zeus aswell)  I noticed when the IED's detonate it turns into what appears to be a missile/bomb for a spot second, then explodes. Could there be an issue with the new RHS update perhaps?

**Comment by Vdauphin** [comment]
>  I noticed when the IED's detonate it turns into what appears to be a missile/bomb for a spot second, then explodes.

If you approach carefully the IED never detonate

> I am not receiving any audio detection from the mine detector,

Some IED are fake

> and visually can't identify an IED (looked around it in Zeus aswell)

Decrease the spotting difficulty then https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/param.hpp#L134-L138 

> Could there be an issue with the new RHS update perhaps?

No

**Comment by dundonator** [comment]
Just tweaked the visibility and I see them now. Only way I can approach them is by tapping W to move. Even when I can see it clear as day, seeming to walk for more than 2 seconds continuously causes them to detonate.

**Comment by Vdauphin** [comment]
> approach it carefully (DO NOT rotate while you are walking: prefer walk, stop, rotate, walk again etc).

Mean at least don't stand UP

**Comment by dundonator** [comment]
Is there a way to change them from the scripted activation distance to pressure plated?

**Comment by Vdauphin** [comment]
The main consequence of this approach is those IED will never be triggered
