### ISSUE TITLE
Increasing amount of hideouts and end conditions?

### ISSUE THREAD

**Issue by 4idChurch** [Vdauphin/HeartsAndMinds#896]
Hello,

I was wondering what files I would need to modify in order to have more then five hideouts. 

I'm edition, I was hoping to change the end conditions to require a certain reputation as well as all hideouts destroyed. 

I'm still learning SQF, and I would appreciate any assistance you could provide.

**Comment by Vdauphin** [comment]
Hello,

> I was wondering what files I would need to modify in order to have more then five hideouts.

Change `5` to the number you want here: 
https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/param.hpp#L161-L162

> I'm edition, I was hoping to change the end conditions to require a certain reputation as well as all hideouts destroyed.

Add: 
```sqf
if (btc_global_reputation < 300) exitwith {};
```
here: https://github.com/Vdauphin/HeartsAndMinds/blob/4041d163ef78f787d82def06db2fc7745bd5b905/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/common/final_phase.sqf#L21

and add:
```sqf
if (btc_hideouts isEqualTo [] && !btc_final_phase) then {
    btc_final_phase = true;
    [] spawn btc_fnc_final_phase;
};
```
here: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/rep/change.sqf#L31

"Should works"

Good luck!

**Comment by 4idChurch** [comment]
This seems to be working out nicely. Thank you so much! My unit has really enjoyed this mission and it's been a lot of fun learning to script based on modifying the code.
