### ISSUE TITLE
Use Scripts...

### ISSUE THREAD

**Issue by valdirsegadas** [Vdauphin/HeartsAndMinds#900]
Dear, I am trying to use a script to block chat with H&M and an error occurs whenever I add it to H&M ... how can I solve it.

**Comment by valdirsegadas** [comment]
https://forums.bohemia.net/forums/topic/207816-disable-sideany-chat-channels-not-working/
By KiloSwiss

**Comment by valdirsegadas** [comment]
every time i got error on execute the create_hideout.sqf

**Comment by Vdauphin** [comment]
Hello, 
You need to read your .rpt file (https://community.bistudio.com/wiki/Crash_Files#Arma_3) and resolve error you make.
Cheers.

**Comment by valdirsegadas** [comment]
???, i just #include myFunctions, and i got this error in RPT... i dont know what i do wrong.


[arma3server_x64_2020-06-10_15-34-43.txt](https://github.com/Vdauphin/HeartsAndMinds/files/4775597/arma3server_x64_2020-06-10_15-34-43.txt)
15:37:05 [ACE] (medical_engine) INFO: Preload done for (Peral_B_600)
15:37:05 "### fox_backpack_zip init "
15:37:05 Error in expression <hideout.sqf"



























params [
["_pos", [], [[]]],
["_id_hideo>
15:37:05   Error position: <params [
["_pos", [], [[]]],
["_id_hideo>
15:37:05   Error Params: Type Array, expected Number
15:37:05 File mpmissions\__cur_mp.lythium\core\fnc\mil\create_hideout.sqf, line 28

**Comment by Vdauphin** [comment]
The error is saying you are passing an array instead of a number. You should pass a number then
