### ISSUE TITLE
handle Shower

### ISSUE THREAD

**Issue by nanhu888** [Vdauphin/HeartsAndMinds#903]
I want to add a handle Shower, what do I need to do? I only add it to the editor, is there no effect?

**Comment by Vdauphin** [comment]
Hello,
In editor you must add it manually to https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L164

In game, you have nothing to do.
Cheers
