### ISSUE TITLE
Headless Client Questions

### ISSUE THREAD

**Issue by teemo0803** [Vdauphin/HeartsAndMinds#904]
Hi,I want to host a zues mission and I usually spawn units in eden editor.Will the headless client automatically load those unit that spawn in the editor itself?
What's more,If I spawn units in in-game zues,will the headless client load it?
Last but no least,I found that if I edit the mission with ACEX,the headless client will not load.
Thanks

**Comment by Vdauphin** [comment]
Hello,
> Will the headless client automatically load those unit that spawn in the editor itself?
> What's more,If I spawn units in in-game zues,will the headless client load it?

I have no idea, ask this to the BI forum, they should know
Cheers

**Comment by SgtKrunch** [comment]
For H&M, I know it only has 1 headless client set up. Is it possible to add more? What would I need to change other than adding more headless clients to the mission?
