### ISSUE TITLE
Should we use newer syntax of createUnit on side mission rescue?

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#905]
Should we use newer syntax of createUnit ` _group createUnit [_crew, _pos, [], 100, "NONE"];` to give a random placement radius and avoid collision instead of older `_crew createUnit [_pos, _group];` syntax here:
https://github.com/Vdauphin/HeartsAndMinds/blob/af69c515f1a46790b815ad0a9e7ad9f4e3de3dce/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf#L66
Reference: https://community.bistudio.com/wiki/createUnit

If not, why? Is it because of created unit's side could be different with the btc_player_side(_group) side?

**Comment by Vdauphin** [comment]
Hello,

The newer syntax I guess. But in this case the `_pos` is find with `btc_fnc_findsafepos` so there should not be any collision

Cheers

**Comment by Vdauphin** [comment]
> If not, why? Is it because of created unit's side could be different with the btc_player_side(_group) side?

Those syntax should work the same

**Comment by GoldJohnKing** [comment]
So the second paragraph on Killzone_Kid's note at the botton of the [reference](https://community.bistudio.com/wiki/createUnit) do not cause side effect at H&M?

**Comment by Vdauphin** [comment]
I don't see any as the group and unit is local to the server
May be I missed something
Let's say we should drop this syntax when we have the time...

**Comment by GoldJohnKing** [comment]
Okay, I get your point. Thanks for your reply.
