### ISSUE TITLE
A few new Questions 

### ISSUE THREAD

**Issue by 4idChurch** [Vdauphin/HeartsAndMinds#908]
Hello Again, 

I had a few new questions I'd appreciate your help and clarification on:

1. I thought I had seen where there is now a notification when a player does something that effects reputation. I have not seen that so far and I am on the latest framework. Is there something I have to do to enable it?

2. Is there a way to increase reputation via script? Basically, I want to have it set rep decreases on player death, but have that reputation decrease removed if the player's body is bodybagged through ACE and placed in a certain area via repatable trigger.

3. Is there a way I can disable divers and water missions from spawning BUT still have boats spawn? (I have the parameter set to off at this time)

4. Does the IED mission parameter control only Roadside IEDs or does it control suicide bombers and drone UAVs as well? How would I modify the frequency of only the bombers and UAVs?

5. Is there a way to increase the amount of civillians spawning besides the parameters at mission start? My playerbase would like more civ interaction but state they never really see any even though I have it set to 10.

Thank you again for all of your help!

**Comment by Vdauphin** [comment]
Hello,

> 1.

This is in development and not available in 1.20

> 2.

Yes, see this https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/rep/change.sqf#L15

> 3. 

Not easy, activate the option and set this https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf#L38 to false may be

> 4. Does the IED mission parameter control only Roadside IEDs or does it control suicide bombers and drone UAVs as well? 

Roadside IED

> 4.  How would I modify the frequency of only the bombers and UAVs?

https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf#L202

> 5.

https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf#L131

The number of civilian is fully random and depend on `_max_number_group` defined for each type of city, you can force at least 4 civilians plus the random part like this
```sqf
[_city, _radius/3, 4 + round (_p_civ_group_ratio * random _max_number_group)] call btc_fnc_civ_populate;
```

Cheers
