### ISSUE TITLE
btc_veh and btc_helo's inventory is not restored when respawn

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#909]
**Arma 3 Version:** `1.98` (stable)
**Hearts and minds Version:** `master-daily`

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
```

**Description:**
- The inventory of btc_veh and btc_helo set by eden editor is always reset to default when they respawn.
- I've read the code of btc_fnc_getVehProperties, it seems not implement any code of restoring inventory of an vehicle.

**Steps to reproduce:**
- Set btc_veh or btc_helo's default inventory item setting in eden editor.
- Start game and destroy the vehicle, then wait or make it respawn.
- Check the inventory, it's reset to default.

**Comment by GoldJohnKing** [comment]
Hi, I read the code and was shocked by what we need to do to save those properties. I've seen the vehicles' properties in mission.sqm are set by a bunch of code, so I wonder if there's any way to save all variables on btc_veh and btc_helo at once. It's just a question, not a suggestion or a feature request.

**Comment by Vdauphin** [comment]
Hello,
> Hi, I read the code and was shocked by what we need to do to save those properties.

That why it wasn't implemented before I guess. It is tricky

> I've seen the vehicles' properties in mission.sqm are set by a bunch of code, so I wonder if there's any way to save all variables on btc_veh and btc_helo at once. 

I don't see how it will be simpler. You need to know that vehicles in the mission.sqm aren't used after the first save so you need to keep data in the database and not in mission.sqm

Cheers
