### ISSUE TITLE
Saving and deleting game progress

### ISSUE THREAD

**Issue by nanhu888** [Vdauphin/HeartsAndMinds#911]
Thank you very much for making such a perfect map!!!. I want to get a license to try out the data saving and deleting functions of the map for my personal map

**Comment by nanhu888** [comment]
And hope to tell me which is the data saving and deleting function

**Comment by Vdauphin** [comment]
Hello,
`btc_fnc_db_save` and `btc_fnc_db_delete`
Cheers
