### ISSUE TITLE
Possible performance hit on city activation?

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#915]
I encountered huge performance hit on my low end server when city activates, players' clients receive severe stuck during city activation. I've tried to decrease unit amount but still get stuck.

I'd like to increase the duration of `CBA_fnc_waitAndExecute` which controls unit creation process during city activation. I've read the code but still confused, would you please tell me which and how should I change the code? Thanks for your help!

**Comment by Vdauphin** [comment]
Hello,

If you are using master-daily you need to replace all `0.3` to the number you want in both files:
https://github.com/Vdauphin/HeartsAndMinds/blob/master_daily/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/delay/createUnit.sqf
https://github.com/Vdauphin/HeartsAndMinds/blob/master_daily/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/delay/createVehicle.sqf
now

But this will not resolve your issue because AI spawn in order and separated by a delay of 0.3s so if your sever stuck when a single AI is created just drop the server

Cheers

**Comment by GoldJohnKing** [comment]
You are right, infrease the duration seems not resolve the issue at all.

I use Arma Script Profiler to analyze the performance issue, and those `ace_interact_menu_fnc_addActionToClass` when city activates seem to cause the performance issue, but I'm not sure about that.

Do you have any idea?

![屏幕截图(82)](https://user-images.githubusercontent.com/26923626/86425121-e0ff9d80-bd16-11ea-9aa5-d75a1cbcba8e.png)

**Comment by Vdauphin** [comment]
> when city activates seem to cause the performance issue,

On city activation there is many thing initializing.
When a unit is created, ACE add action to him:
![image](https://user-images.githubusercontent.com/14364400/86461515-63458d00-bd2a-11ea-81dc-ddab66b58625.png)

For my test here, the time execution for `ace_interact_menu_fnc_addActionToClass` is around 292µs in average which is close to what you have.

Here is the trace of what H&M execute when a unit is created:
[single_createUnit.zip](https://github.com/Vdauphin/HeartsAndMinds/files/4869315/single_createUnit.zip)
code executed in debug console: `[createGroup btc_enemy_side, getPosATL player, 1] call btc_fnc_mil_createUnits;`
![image](https://user-images.githubusercontent.com/14364400/86463266-7443cd80-bd2d-11ea-991f-29d8c73cfb3a.png)

**Comment by GoldJohnKing** [comment]
Okay, I get your point. Thanks for your help!

And I should have dropped my server... 😭

**Comment by GoldJohnKing** [comment]
I've tested on a better server (i7-7700H), and I found another possible performance hit, the core/fnc/mil/create_group.

**Comment by Vdauphin** [comment]
Well, if you are using the master_daily the result in master would be worst.
You should fill up the issue template.
