### ISSUE TITLE
Side mission chemicalLeak, mines & supply tends to spawn outside inland terrain if target city is near terrain border

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#929]
**Arma 3 Version:** `1.98` (stable)
**CBA Version:** `3.15.1` (stable)
**ACE3 Version:** `3.13.3` (stable)
**RHS USAF Version:** `0.5.2` (stable)
**Hearts and minds Version:** `master_daily` (b7b2470, migrate to inland terrain like Lythium and Kujari)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
- RHS AFRF
```

**Description:**
- Side mission chemicalLeak, mines and supply tends to spawn outside terrain if target city is near terrain border.
- The "tends" means that in almost every cases, the mission assets would spawn outside the terrain. That is to say, the spawning location would choose location outside terrain in priority.
- See the screenshot, it would better explain everything.

**Steps to reproduce:**
- Spawn chemicalLeak, mines and supply side mission to a city near terrain border and its radius cross the terrain boarder.
- The mission assets would spawn outside the terrain in almost all cases.

**Screenshot**
![107410_20200727151849_1](https://user-images.githubusercontent.com/26923626/88515821-ddfa8300-d01e-11ea-8c97-8f05c8c89cab.png)

![107410_20200727153613_1](https://user-images.githubusercontent.com/26923626/88515863-ece13580-d01e-11ea-8c5c-fe03632550b8.png)

![107410_20200727175449_1](https://user-images.githubusercontent.com/26923626/88529277-5a4a9180-d032-11ea-9f84-4ef2c6a80fbd.png)

**Comment by Vdauphin** [comment]
From my point of view, city should not be that close from terrain border. It looks just ugly.
I don't want to put a lower because for map like Tanoa, the density of tree is so hug that the function will not find a "safe" place to spawn those side mission

**Comment by GoldJohnKing** [comment]
> I don't want to put a lower because for map like Tanoa, the density of tree is so hug that the function will not find a "safe" place to spawn those side mission

I agree with your idea, that is the conflict.

I wonder if it's implementable to have some way to detect if the position are outside terrain then exclude them. It could be a better way to keep tight for both types of terrains. However, I've search the BI wiki and google but did not found any possible solution.
