### ISSUE TITLE
Helicopters as btc_helo sank into water wont respawn

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#946]
**What I need to say very first:**
I'm not sure if I should report it here or to BI issue tracker, and I'm not sure if this issue should be feature request or bug report. So at the moment, please consider this more like a discussion than a typically bug report.

**Arma 3 Version:** `1.98` (stable)
**CBA Version:** `3.15.1` (stable)
**ACE3 Version:** `3.13.3` (stable)
**RHS USAF Version:** `0.5.2` (stable)
**Hearts and minds Version:** `master_daily` (mission.sqm and mission.sqf modified, based on c6a29ff)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
```

**Description:**
- When `btc_helo` is sank into water, they wont respawn anymore. "Sank" means destroyed by the water then sank, instead of destroyed first then dropped into the water.
- I've tested vanilla UH-80 and CH-47I, as well as RHSUSAF UH-60M, UH-1Y, CH-47... and RHSGREF UH-1H, it seems all helicopters are affected.

**Steps to reproduce:**
- Drive a helicopter which belongs to `btc_helo`, hover it on water then reduce height until its bottom touch the sea surface.
- Shutdown engine, then wait for it sinking into water.
- Wait forever and the helicopter wont respawn.

**Add mission file:**
[Test.Altis.zip](https://github.com/Vdauphin/HeartsAndMinds/files/5123031/Test.Altis.zip)

**My Guesses:**
- I've googled and I think this is more likely to be BI's issue.
- During the sinking process, you can notice first the engine becomes red and the rotor is tilted, then it gradually sinks into water, finally when it touches the sea bed, it changes into a wreck.
- So there could be no "Killed" event, the helicopter is just sank into water but not killed, then replaced by a wreck.
- The helicopter is more likely to be "Deleted" instead of "Killed". If this is true, I **guess** we can change the respawn method from "Killed" to "Deleted" to solve the issue.
- I **guess** we can use Event Handler to realize it. If it's "Killed", delete the wreck after some time. If it's deleted, then respawn it immediately.
- Otherwise there could be no "Deleted" event at all, the sank helicopter just becomes dead while not triggering "Killed" event, or just got a texture replacement.
- I need to emphasis the behavior of UH-1H from RHSGREF. From my test result, the UH-1H hardly becomes destroyed or killed. When it gets critical hit, it just catches fire instead of fully explodes, then hit the ground and finally destroyed. When it finally hits the water instead of land, it would be regarded as sank. So if a UH-1H hit the sea, it will never respawn.

**Comment by Vdauphin** [comment]
Hello
See https://github.com/Vdauphin/HeartsAndMinds/issues/664
Cheers

**Comment by GoldJohnKing** [comment]
Okay, these truly resolves my question! Thanks!
