### ISSUE TITLE
"Killed" event may be fired twice on players, what about "Killed" event on civilians and "MPKilled" event on vehicles?

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#979]
I've read #974 and have a question.

I sometimes run into an issue that one killed btc_helo will trigger two respawn at the same position, then it will keep respawn and explode and respawn like forever...

This is much more likely to be happen when a UH-1Y (btc_helo) is killed and respawned at its respawn location, while there are some other objects there, so they crash and trigger UH-1Y respawn again, then two UH-1Y will respawn together and crash again....

Could it be the same issue? Cheers!

![107410_20201016001956_1](https://user-images.githubusercontent.com/26923626/96332904-33cc4d80-1099-11eb-953c-91e77c38c9b0.png)

**Comment by Vdauphin** [comment]
Hello,

> and "MPKilled" event on vehicles?
> I sometimes run into an issue that one killed btc_helo will trigger two respawn at the same position, then it will keep respawn and explode and respawn like forever...

Here is the fix : https://github.com/Vdauphin/HeartsAndMinds/pull/973/files

Cheers

**Comment by GoldJohnKing** [comment]
Ah, my bad... 😭

**Comment by Vdauphin** [comment]
Also please drop Achilles, use Zeus Enhanced (https://steamcommunity.com/sharedfiles/filedetails/?id=1779063631)

**Comment by GoldJohnKing** [comment]
Ohhhhh, I'll give a try!
