### ISSUE TITLE
bug hideout 

### ISSUE THREAD

**Issue by rgk11** [Vdauphin/HeartsAndMinds#997]
hi... admin ... iam enjoy using you mission ... but one tiny problem... your hideout hard to exploded... pls advice me...iam using =BTC=co@30_Hearts_and_Minds.Song_bin_tan   .....

**Comment by Vdauphin** [comment]
Hello,
Just put a charge under the red flag.
Cheers

**Comment by rgk11** [comment]
> Hello,
> Just put a charge under the red flag.
> Cheers

allready do everything  ... example put any bomb only place destroy but flag not destroy... can help me?
